table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVrbUuPGFv0VFc9BhRkIM2/TlhvTRFY7kkVNSOWhbQvTRJaILq4Jr+chdb5rfuys3bKxPaeMmoyYqQKVsVy9vG9rr73F778f9Y5+OjrD78mZczyJxwwv2YgFA+awMQu5J/DK4z4fyEBI3FRLlc2VO0vSZJ5nOv94V+hFnpRVkaR4O1+60wIf6x3ToUd//LSP4KwhbsREhgIns5Hw/d+cAXekL264CIHr3/AIn1npKi+0clW6Sko7mN6puQAnlAG+sRzjVDrrMmSBJ7jvC2fEPBjjXPIwJDjcvCtUNtNJmmr3LimKRBfqIJxBaMe7jn3BAuZMuPhkjBrIyIlYMJF096FOtcqUW6qsyg+b9hXWe3MB1g3zRXBlThqHIvKED6BQDKUzlCPjusdClzON0xb58gXfmSMNgLHj5Ky5AiL68h/p+LG4xZHBLRuSm/phHOwaQp68YgNKimlRw5ylmt2ref5RpXqZkGX/B3l63IBYY/7CQhFwBzkYCf+GOb/48RBv/6kKnSXun2m9eB3aeXMFmriOBQVKhgMK1ID58GIoI+b05eUlBSkv5hSkaX531wJyvgGhFxen5gIIyaMJxx9DLiLknnA8RGuCvOD76bBIdIn005t8oFAlhZqpXGV6qdIt2PnxxTYnyLSLC3MB2CW75VS1kzjsC/8KvjQh+40FDkc9BzH3nWsexRHV2giV0MTtb5W5S6T+fh333Dxb6lmRl/ldRfDktrNjg2YNHrJLBtBLWD7mzljAWmfMN0VXqDuVpO5jsq439ZSAV6q6mOr0XuU7abqHS+Z/eH/SXIlPWF8iB52QffmngfVjjyE38X14tMsruJXWM1W6eapXbZinxw2ILShKkhOf7VRHn/n4CN6m+yuVJsRluOb2uJRe9AtIlDxMonORVCH3mSEZqn2OdBoxUMxYeEwadqHaT1Afjxo5dLD6T21xTE2CLwO0hYY4Gf3tg3MCYdyqn8CcaYWi1N8Ody0j7vBBzEKgeWyCdw3MA6rPnakK59rCfN12LllfSOc6RisLnQk6WkD0r6Y6dys0s+wbuwwVGtVZX4ZDJN+G/HEnQdeske5Voj930V8oxfDtJTGjJ6MJcy5Rd6Y/Z8aS3L1Dbh0Ofu9FP3ks9Ckm6yB8YjeCh1RMhkHwgZkq0rx0H5KytmjNNkyPdJJBw/LkrxRWuKVOV8qW4NvSak1HRPFb+gHDHY6FfYGwONzVSzcCdECFoepCuSuN4n8R5OSk556cnLpoJDZwOPyTY6okkoCkeADhs1vmqnih2+8hnVlWvod2JTeUFjAQTjyZNEU/g4bJ3UyBbeqqerkifzju+bZtNT/DGFVzI50RKgr9f8QmUTySEyqhRV1WapW7S3SK7FB67DWHbo88IFW+9fg9pdLeW8CRaCtNng24DExngeBfqsKdJ/lhrtzz+8WWy+iX0AajHRw+5LfQRuD5ED30Sn7VsZNF8gRptNOzD/EZgQLzHcH+AMx3LZg+R/MM5TNJ4FVMAaXopQlGqiJ3VU1xfIGz13hnFjayQWiEZiObBzFZCkkS9pnpH2oONQKFMK8LSJNWxHMg9loQ0RoiKBBnyPohvMueRTslTlKW0CJrQu8CrVv7frZAXPcPRqWyHVLXfeTlGfU1MJGE3BnynW5iBFdIDFDmkD6LxEypmIA6wevekW2p2ZEj22C6dmQb3rVkmAhQAaSYxhh6oqgBe8gh8R8x35WlDdaFRdBwOqklCAGAGF7pAw4cRvSVatJOU8CBwTqBC/kQHYfGmedBfGeQSxboOek8t6zuH2Bfa0bGfUENlSa4PvOuBDeStKinGNmmanavk4WdYa1IXXuytQriW+E0NQ4LZcihoqjfRTK+pftl/aQhHOundrj31kUgB2YbtdMAHFMERT4njE6QqMCovv1d4T2WoJSADKRtji/6vOnoqD2qd6A95ln10vj4mq8whO73KHFoCKf8GUJNMNo6bA1fYAaAYLWMqA0qBXLMB+GGrImkM2VL0O8ttEp3QTxrQYKGveJxtNkRDQSLnOjXWJDCxe2lqu6TunTLv2pNyrYTzAESxAdDh2absa2+OdIiBVEXEGPt1n2woc2vXEgMMxGB6XaNE01WuFDUlc7au54N5uCKNs/NItiJxjISRmLO72nl7JaPgLRQmB8s8rDZszXLh0j8Gu/t2Er9V22lnW2QuotYW+ZvFh6GHXetSua1Kgwxv8Ku9jqjPcgnGr4QLOauF1MbyfCZ1h7tYqh3YpEW3zo7btF637V99959X7iz7w9n0ei6grORXvSUR263vWvi4rR9/PIPfYCe9SBbEtRcNmvPFxtM4UewsM8mgsgEGtoj43RawrZCz2bdWNaxI9vi9haObMPsxpHfOSPbaPItHNmG2Y0jW1Ei1jcCNmTxNXExZOqUzlOFqh9aWtpps3hqzfqbJkTPIqTPbm8JK1k1W6epenqyg2rLi7WKe36Q77F+yEif3iErHunZzbRok6hgxFMLq3yMNWQYPZXYPAFBY/PMvyikmGnIuKRw0dFmOv+4UnOVV9AJEEBFlZT/FnaIMUpgvlgnI7p2PzbOXGhokUy707rNl5ZIxjbKQbN/ZUOy8IiUPqyiJFQQj1VLrp/ZZcj6cdh2M+nLMW/+TSHTeeGm+WObCrFE6ihBbJr0GySIDSyi9eW/znrD5TGMZx4LJnxvF9o8xsSwNlNZdfjB0GtgO3Kszb7wDRxrA9tN5dkgdeRLm2HtDXxpA9uNL9dIf/wP", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

