table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVlNc+JIEv0rCp/HCpt1h723LkSByy1UjD6IHibmUECB5RaSRx9Ej69zmNjf1X9sX5bAgGcBeayIPaAApKhHVuV7LzP59deL64ufLm7wurqxLsNoxPCWDZnXYxYbMZ87Au8c7vKe9ITETbVS6VzZM53oeZbG2edFHi8zXZS5TvB1trKnOR67vqRFL3776RDB2kCMRSh9gZXZULjuL1aPW9IVYy584LpjHuCZdVxmeaxslax10QzmumMuwPGlh18sR1iV1ur7zHMEd11hDZmDYKw+932Cw81FrtJZrJMkthc6z3Wcq6NwBuE83kPkCuYxK+TiqwmqJwMrYF4o6e5TlcQqVXah0jI7HtobrDtzAdaYucK7NyuNfBE4wgWQLwbSGsih2brnPC5mMVZbZqsTe2eWNAAmjqub+gqI4Mef0nIjMcGS3oQNaJu6fuTtB0I7ec96lBTTvEI4KzV7VPPss0rilabI/gbZuaxBGmN+Yb7wuIUcDIQ7ZtYXNxrg628qj1Ntf0uq5fvQPtVXoImHSNBBSb9HB9VjLnbRlwGzurLfp0PK8jkd0jRbLM6AfNqC0JvbjrkAQvIg5Pgw4CJA7gnLwWmFyAt+mA5LHRdIv3ibD3RUOlczlak0XqlkB/bp8naXExTa7a25AKzPJpxYG0Z+V7j32EtzZL8wz+Lgsxdx13rgQRQQ14ZgQn1uf6jUXiH1D3l8bWfpKp7lWZEtSoKnbbu5NGiNwX3WZwDtI/IRt0YC0VojviVdrhZKJ/az3vBNvWjoSlnl0zh5VNlemh7gUvj/vruqr6QnrCuRg5bPfvxVw7qRw5Cb+D082NcV3EqqmSrsLInXhDmNjxGjc1lDNIUEITmp2R43uszFI/ia7q9VoknJcM1ORXqIS8lFL0CC8AiI1kVK+dxlRmKI+RzJNGQQmJFwmDTaQszXYMdzjAw6yv1OUxzDSKilB1OoZZPRZxeK4wmzqfELdDMpQcmjO9oc7kEG3OK9iPlAc1iIbw3ME7hnz1SJdZvCvDWdPusKaT1EMDLfCuFnHok/8iCzS1hZ+kGPIZoRy7rSHyD1ttKPOxqeWSHZSx1/b8NdKMXw6yXpoiODkFl9sM64c2oiyewFcuv44V+f3CeH+S6dyeYQvrKx4D5RyegHHpipPMkK+0kXVQNjbqLzSCfp1RpP+5UgCvsoPw90/Vw+bVSIlH2nOhC244fQnBks8vfLpLGADhAjVJUrex2D9SdBrq6u7aurjg3/aAKHxb9ahh6BBCQdBBC+20Wm8hMmf4B005DyDlxKbrXMY1CaKAxrts9QumR2qiAzVVmepuL/HffTKe8fRKDOWFpD0AolwJCFQTSUIfFoWRWlWmf2CmaRHkuVA+s/L9eQHSh1fYI9Lj0j1qigVyq35zo7Lj8HEd3u5IFehNYb7uHwAZ+g2IB0+rCle/nGAvVSv6DWeDXB4xLxCorX9RlQl8McfPnKBbyLaHdpKxONhiHPbFXRpp7QpPcAsp5v6qi6KuxFFCs81+8yI5BqDruFBc6rHN7bDiTEL4DHWgPW9bHB7LUopXPURQG3tYs4Wbe0pRvdYpRIu55oo1+nW6J34QQSBjvgezJmLN4nghQZzHapTVeEirulfZQMtRN2krxlhOIwCGq0pwzF0DPq4KJoDcznA1CbSrHXFmKvBNVLkDuZZ62eW9QVpCVUD3bRIAluDC6vpigAp+iQYr1sCSqIJsKqmQBE6XNIJdE9kNGE7hfVC3qKrHppCa8+OdkzreZe9lvm5PJsTiDtQFFaUFq6+/46kqCCRyFSr+aKLq8lDRlDaQq45ywtT5WH7/oNA/i7Q2dJVTYd6QB6yqip2IW+hNfDmNpMIDrMEe/5W1kjOUMb2qaUwenuOTrBTWvWE2iYgp8jQT6I2ytVPuqqsIvfq5j8rx1QtNnCBeN900fsWIgmO05A/Bw20VL2vM1RomMoPCOgdZaa87LhvGWctiSkvXua+dQjGCsYyUAY+5s/0rDHLp6B2Zb71S1uXfkH4ufooL0t4t+r9px92wQYTdkH0/NK5UY624R7kNQcfKXyCbvI7E23tnWH7zSFacv5Plr+vROOxmdy10hvEpNTY/fjL3qAhmiA1KBBOmsJVLgB+qouCwXlClzXIaeNkwL9VR7PZi1JJcS6a7TaZ9EDbSAUeUoLqlxVTw2zvnMuFcd1kfnK6i6bTAhMr+sKc6peXlrC2ijj60zaQdFnpHgBt3mmQcQ0b6rGN2fZPBEUGvXY234eCemYcXsCD6fwdG4jE2dx9nmt5ioroZaQlLzUxT/GHaBuELDTTUqCb93I7OcStXOcxva0arqd56BMdJSJpvlhA4rR+BriolRUUOSyYcqfw9rMd3atiCtHvJ66o9nK7SR7bqogZ6Fk8OM/1qZSdxjM2kHnyg86g3psBeueqbQ8Pg/4X7jnB48flrDDiWODoe6HEf82Rb77l7nsA9ZxtoNmlj/9J8pHs/NuH6Fzay7bOdeIRWbS/kGMzu1FwznDx1h9MGq4O5P+91RjbWstNKqwFwJ6rJbo9lca/vJu+TgVGYo4iCMAUfeH5KQeakjn/oIK1nyWFWhTU53r2eN7BymnQOuZMbF5+2ehmRdT/Xiy6vkHUF84/RNa/0fkHYwXvukk+eNMj/EW8Lf/Ag==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

