table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVlNc+JGEP0rKp9jlU28Zee2IzHgcYSGSIjakNrDAIIdr5AcfVAbX3NI5XftH8vrERjYDSDHqsqBKYyoeXRPv/e6x7/9dnF98cPFDV5XN9blKBoyvGUD5neZxYYs4K7AO5d7vCt9IfFQrVQ6V/YsTuJ5lurs/SLXyywuyjxO8HG2sqc5vnZ9SZtefPzhEMHaQIzFSAYCO7OB8LxfrS63pCfGXATA9cY8xHfWusxyrWyVrOOiGcx1xyzACaSPXyyH2JX26gXMdwX3PGENmItgrB4PAoLDw0Wu0pmOk0TbizjPY52ro3AG4TzeQ+QJ5jNrxMUHE1RXhlbI/JGkp49VolWq7EKlZXY8tG+w7swCrDHzhH9vdhoGInSFB6BA9KXVlwOTuqdcFzON3ZbZ6kTuzJYGwMRxdVOvgAi//iktLxITbOlPWJ/S5ASRvx8IZfKedakopnmFcFZq9knNs/cq0auYIvsOsnNZgzTG/JkFwucWajAU3phZP3tRHx9/VrlOY/tzUi1fh/auXoEmHiJBByWDLh1Ul3nIYiBDZjmy16NDyvI5HdI0WyzOgLzbgtCb245ZACF5OOL4o89FiNoTlovTGqEu+GE5LGNdoPz0th7oqOJczVSmUr1SyQ7s3eXtriYotNtbswCsxyacWDuKAkd498ilObJfmW9x8NmPuGc98DAKiWsDMKE+tz9Uaq9Q+oc8vrazdKVneVZki5LgKW03lwatMXjAegygPUQ+5NZQIFpryLeky9VCxYn9FG/4pp5j6EpZ5VOdfFLZXpke4FL4P91d1SvpCXMkatAK2Ne/algvchlqE7+Hh/u6gkdJNVOFnSV6TZhTfYwYncsaoikkCMlJzfa44TAPX8HH9HytkpiUDGt2KtJDXCouegEShEdAtC9KKuAeMxJDzOcopgGDwAyFy6TRFmJ+DHY8aVTQUe53muIYRkItfZhCLZuM/vagOL4wSdXP0M2kBCWPZrQ53IMMucW7EQuA5rIRPjUwj+CePVMl9m0K863p9JgjpPUQwcgCawQ/80n8UQeZXcLK0jd6DNGMWObIoI/S20o/nsTwzArFXsb6SxvuQiWGXy9JF10ZjpjVA+uMO6cmksxeoLaOH/71yTy5LPDoTDaH8IGNBQ+ISkY/8IWZypOssB/jompgzE10HuUk/VrjKV8JorCP8vNA18/V00aFSNl3qgNhO34IzZnBomC/TRoL6AAxQlW5stcarD8JcnV1bV9ddWz4RxM4bP7BMvQIJSDpIIDwxS4ylZ8w+QOkm4aUd+FScqtlPoPSRKNRzfYZWpfMThVkpirL01T833HfnfL+fgTqjKU1AK3QAgzYKIwGckQ8WlZFqdaZvYJZpMdK5cD6z8s1ZAdKXZ9gl0vfiDU66JXK7XmcHZefg4hud/JAL0LrDvZweJ9P0GxAOgPY0r38xgLjZfyMXuPFBI9LxAsoXtdnQD0OcwjkCxfwLqLsUiqTGANDntmqoqSe0KTXALJuYPqouivsRhQrPDdwmBFINYfdwgLnVQ7vbQcS4hfCY60+cwIkmL00pXSOcVHAbe1CJ+uWUrrRLUaFtJuJNvp1eiR6FU4oYbB9vidjxuIDIkiRwWyXsZmK0HG3lEfJ0Dshk+QtQzSHYVijPWZohp7QBxdFa2DYnowF0gkUU6IO8MAH4zK6tpkCcbaEF/A+pIRav5eRZa/ljZcQk2SetVonkSNIu6j/dDCQCW4MNa+maDinmMh0vGwJKowmwqqZB0QZcEgzyUsoowk9L6pnzDBZ9dwSXl0psmtG2z22WaZS8mxOIK3VSUg08Pb9fChBPZ9CpNnQEw6vJRQVSrQA3FOWlqfa0Vf9hj76CZfOkrp6OtI+9JvRELMLfYneAkbYZgHRYQ55N9jKKMknxt42pRPOes8xeW5Gwa7AgBb+EgnyXTxeqfJTXBV28XulyW/bAcVYLzwoTGDmlh0LMdTrBEKTw5Zaqp5va5ToOBK+Eey6Ss152XD6UqctCXf3nu6Y6isfKxzKUBi7nX+iyyW7eAJmW25bj9T1pBGKX6KDcbrQv1ftdRLbocNoyj5YPK9UbqSzTbgHScPIB2rXkEVmb6bDrRt9oVuftpz2re3mK+Houk7uBvdNYXIaJL/+RV+gSztAxqBBOmsJVHgh7NZhI0G1Apd3yWl1UsBocz2btSSVEGvHaHXAogdKIBR5ShuqXFWPDau+c64Ux3XH8MJqh00mBBav6452qp6fW8LaKOPLHbiLJtNI8QJu80QXH9O8qRrfnGXzRFBoNNNv7w9QkK653k/g4RRenNuoxJnO3q/VXGUl1BKSkpdx8Z9x++gbBOx0U5LgmxOZfC7Rq+tU29OqaTrPQZnoqBLNsMX6FKPxNcRFpaigyGXDkj+HtblP2o0+nhzy+pYfw11uJ9lTUwU5CyXDr39bm8nAZTBrF5MyP5hE6msyWPdMpeXx+4d/wz1/0flmCTu84WxwifxmxO9ure9+NMs+YB1nO2hm+9P/tHlrdd7tI3RuzbK9VxuyyNzsvxGjc3vR8F7jbaw+uNq4u/j48R8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

