table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("7VrbcuLGFv0VlZ9jle3ylJO3aYkGtyPURBdqQioPDQjcjpAcXag5fj0PqfNd82Nn7RYYmFMY+YxqMklcNagYRPVi39Zee8u//HJ2efbd2TVeF9fWeRSPGN6yIfN7zGIjFnBX4J3LPd6TvpC4qVYqmyt7lqTJPM90/n5R6GWelFWRpPg4X9nTAl+7PKdDz3797hDB2kCMRSQDgZPZUHjez1aPW9ITYy4C4HpjHuI7a13lhVa2StdJ2Q7m8spcgBNIH79YjnAqndUPmO8K7nnCGjIXxlh9HgQEh5uLQmUznaSpthdJUSS6UEfhDMJpvLvYE8xnVsTFB2NUT4ZWyPxI0t2HOtUqU3apsio/btpnWN+bC7DGzBP+rTlpFIjQFR6AAjGQ1kAOjeseC13ONE5b5qsXfGeONADGjovr5gqI8NO/peXFYoIj/QkbkJucIPb3DSFP3rIeJcW0qGHOSs3u1Tx/r1K9Ssiy/4G8Om9AWmP+yALhcws5GApvzKwfvXiAj39Thc4S+7e0Xr4O7V1zBZq4iwUFSgY9ClSPefBiIENmObLfpyDlxZyCNM0XixMg77Yg9ObmylwAIXkYcfxnwEWI3BOWi2hFyAt+mA7LRJdIP73NBwpVUqiZylWmVyrdgb07v9nlBJl2c2MuAOuzCaeqjeLAEd4tfGlC9jPzLY569mPuWXc8jEOqtSEqoYnbv1Rmr5D6h3V8aefZSs+KvMwXFcGT267PDVpr8ID1GUD7sHzErZGAtdaIb4uuUAuVpPZjsqk39ZSAV6q6mOr0XuV7aXqAS+b/8P1FcyU+YY5EDloB+/RHA+vFLkNu4vfwcJ9XcCutZ6q081SvT2FenTcgbUFRkpz4bK86HObhK/iY7q9VmhCX4Zq3x6X0ohcgUfIwic5FUgXcY4ZkqPY50mnIQDEj4TJp2IVqP0F9PGrk0NHqv2qLY2oSfOmjLTTEyej/HjjHF8at+gnMmVYoSv3lcHcy5BbvxSwAmssifGpgHlB99kxVOLctzOdtp88cIa27GK0ssCJ0NJ/oX011bldoZtkXdhkqNKozRwYDJN+W/HEnQdeske5Voj920V8oxfDrJTGjK8OIWX3UnenPmbEktxfIrePBv3zRTy4LPIrJJggf2FjwgIrJMAi+MFNFmpf2Q1LWLVpzG6ZHOkm/YXnyVwor7FKna9WW4E+l1YaOiOJ39AOGOx6L9gXC4mBfL40F6IAKQ9WFstcaxf8iyMXFpX1xcWWjkbSBw+EfLFMloQQkxQMIH+0yV8UL3f4A6bpl5btoV3JLaT4D4cRR1BT9DBomtzMFtqmr6uWK/NNx3+3aVvNvEKNqxtIaoqLQ/4csCuOhjKiElnVZqXVur9ApsmPpcdAcuj3yiFT50uMPlMrp3gKORFtp8qzHpW86CwT/ShX2PMmPc+WB3292XEYvQusN93D4gE+gjcDzAXrorfysYyfL5AnSaK9nH+OzZ1C8Lr9FUI+jfQbymSbwLqaQUvzSBENVkduqpki+wNqvAWS9wGjNRjn3YrIVqiRwmGkhag5BApEwrwuok24g0R5CqBBrwJwADmbPwp2SJylL6JENqf9VLdx0EUYFsxtVN93k5Un1VTihhOoZ8L2mYnRXQERQ5lBAy8QMqxiE3nz5rfnyTjIMBygEEk8jzD9h2KA95FD7jxj1yrIzMBxPygmiACiGYRzggc6IyVJNOmoKPJBZR1HjA7Qfmm2ep/K9qS5ZogGl87zLMv/qFsaOoP5KA53D3FvBjUIt6ikmuKma3etk2ZFpX9+ZYTwRVlPssFEGHLKK+l8o4wndL+snDSVZP3WE19SC7Jn91F47sEwtFPmcQDrLk5AK3dvX4iMJcvHJRFrweMLhTY9HDVLhA+4xz6qXJspX/YYBZgGXsocGc0qiAQQGo03EzvQl5gKI2E47oU+J0wu2zE2Mnalue/vXCySk7S2Pw+3qqCdYaIU/xYKEL26vVHWf1KVd/l5rErzdgPaQJR7oOjBbjl0VzpEbKVi7gETryL7PvUhcEwnfdL/GjyY1bEjtSmcddcHeLe2kmxWxFY5kKIz0nN/TMtouH4HZlfJsVnDNXiIUP8UH67dS/153p6q/YtS22xDDlPt2JfNaFYalu7TsTtKW5AONZggYszdrq62K+EhLka4U0peOlt94Q3/D6xaPngTJ3UZ4w2GcNpSf/qAv0PMgpEyC2stmHSWN8ELY6LBIEK1AXbtknk5LWFfo2ezNl2++/Bv7EtLWMco2YPEdETP065QOVIWqH1q2uKtTARs3YXoWJg6bTAgsWTcLqql6euoIayPunh/7u8wJGAnXBVLjkZ70TIu22vX6pCCZCDKNHmJsH5ig0bnmLxpSTDxkXlLY6HAznb9fq7nKK0gHqKKiSsr/G3eAKUtg+NikJPq4Ext/LjX0Sabtad3WnaegjHWUiWZhywZk4xlNAbCLUlFBVFYtU/4U1uYB2m6T6ckRb/6wIdN5Yaf5Y1tlcgrqn5AliNin/1ibbZjLML65zI/4wfK0efaJYW6msur406Q33/55Ffjmzte689f/Ag==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

