table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVlNc+JGEP0rKp9jlY29Zee2gxhgvEJDJETtktrDAGMsr5AcfVC7vuaQyu/aP5bXIzCwCSDHquSAykaUHj3d773u5tdfzy7Pfjq7xuvi2jofhUOGP9mAeR1msSHzuSPwl8Nd3pGekLipliqZK3umYz1Pkyh9f59Fi1TnRaZjvJ0u7WmGj12e00PPPv+0j2CtIcZiJH2BJ7OBcN1PVodb0hVjLnzgumMe4DOrqEizSNkqXum8Hsxly1yA40sP31gO8VR6VtdnniO46wprwBwEY3W57xMcbt5nKplFOo4j+15nmY4ydRDOIJzGuwtdwTxmjbj4aILqyMAKmDeSdPexjCOVKDtXSZEeDu0HrFtzAdaYucLrmycNfRE4wgWQL3rS6smBObqnLMpnEZ62SJdHzs480gCYOC6uqysggu+/S8sNxQSP9CasR8fU9kNvNxA6yT7rUFFMsxLhLNXsQc3T9yqOlpoi+xtk67wCqY35gfnC4xZqMBDumFkf3LCHt7+oLEq0/SUuF69De1ddgSbuQkGJkn6HEtVhLk7RlwGz2rLbpSSl2ZySNE3v70+AvNuA0B83LXMBhOTBiOOfHhcBak9YDrI1Ql3w/XJY6ChH+UWbeqBU6UzNVKqSaKniLdi785ttTVBoNzfmArAum3Bi7Sj028Lt4yxNyj4xz+Lgsxdy17rjQRgQ1wZgQpW3byqxlyj9fR5f2mmyjGZZmqf3BcHTsV2fG7Ta4D7rMoB2EfmQW0OBaK0h35AuU/dKx/aTXvNNPWvoSlFm0yh+UOlOme7hUvg/315UV9IT1paoQctn3/+oYN3QYahNfB8e7OoKbsXlTOV2GkcrwpxGh4jROq8g6kKCkJzUbIcbbebiI3ib7q9UrEnJcE2PRbqPS8VFL0CC8AiInouS8rnLjMQQ8zmKacAgMEPhMGm0hZivwY6nCBV0kPutujiGkVBLD6ZQySaj/10ojifMoUbP0M24ACUPnmh9uDsZcIt3QuYDzWEjvGtgHsE9e6YKPLcuzI+m02VtIa27EEbmWyP4mUfijzpI7QJWlrzRY4hmxLK29HsovY30446GZ5Yo9kJHX5twFyoxfHtJuujIYMSsLlhn3DkxkaT2PWrrcPIvj56Tw3yXcrJOwkc2FtwnKhn9wAdmKovT3H7UeVnDmOvoPMpJepXG03nFiMI+yM89XT9VT2sVImXfqg6E7XAS6jODhf5umzQW0AFihCozZa8isP4oyMXFpX1x0bLhH3Xg8PCPlqFHIAFJiQDCVztPVXbE5PeQrmtS3oFLyY2WeQxKE45GFdtnaF1SO1GQmbIojlPxf8d9d8z7eyGoM5bWALRCCzBgoyAcyBHxaFHmhVql9hJmkRwqlT3rPy3XkB0odZXBDpeeEWt00EuV2XOdHpafvYhutvJAL0LrDHZweI9P0GxAOn3YUl/+YIF6oZ/Ra7yY4GGJeAHF6/IEqMthDr584QL+Cul06ShjjYEhS21V0qEe0aTXALKOb/qoqivshBQrPNdvMyOQag67hQXOywze2wwkxC+Ax1o91vZxwOylKaU86jyH29p5FK8aOtK1bjEqpO1MtNav4yPRq3ACCYPt8R0ZMxbvE0HyFGa70GYqQsfd0DlKht4JJ0neMkRzGAQV2mOKZugJfXCeNwbm8x6oTa3Yywix04LqBcgdz9NG8xa2BWkJ9YNtDEiCG4PLyikawCkmpEgvGoIKwomwKiYAUfocUkl0D2Q4oft5+YyZIi2fG8KrMic7ZtTcqX7LZC5L5wTSDBSVBZWlu+uvQwkqeBQizWquaPNK0lAxVKaAe0qT4lh7+Krv0IO/O5RL6rIppT3oKaOhYhv6Al4PY2qygCiZQ97xN7JGcoYxtEkpg9P1OSbB9WjWERiYgl9CQT6I20tVPOgyt/Pfyoj8rxlQjNnCBeN9M0dsWYghO4pB/Aw20VD1/FijRMeR8IyAVlVq8mXDeYsoaUhIO33a+VQrGCsYykAY+5s/0LLHzp+A2ZT7VSNu1fkH4pdwb7zNo9/K5px9MwQYTdkF0/NSZUY6m4S7kzQcfKT2CafI7PW0tnGHr7SFacr53tr+vRKO1mdyO0ivC5PTYPf9D/oALdEAqUGDZNYQqHADzFVtNhJUK3Bdh5w2inPMV1k0mzUklRDrttFqn4V3dIBQ5Ck9UGWqfKxZ9a1TpTiumswXVrfZZEJgelV1mFP1/NwQ1loZX3bSDpo+I8X3cJsnWkRMs7pqfH2SzRNBodGMvZnnUZCOWbfH8HAKT2c2KnEWpe9Xaq7SAmoJSckKnf9r3B76BgE7XZck+NYOzXku0DtHSWRPy7rHeQrKREeVaIYf1qMYja8hLipFBUUuapb8Kaz1fmc7irhyyKutO4atzI7Tp7oKchJKBt//tNadusNg1g4mV743GVRrK1j3TCXF4X3AP+GeXjy+WcL2N441lrpvRvzbFvn2ylx2Aas4m0Ezjz/+I8pbq/N2F6F1Yy6bPdeQhWbT/kaM1s1ZzT3D21i9t2q4PVH+feqxNr0WBlXYCwE9lAtM+0sNf3m1fByLDE0cxBGA6PtH5KQeekinf0YNazZLc4ypic707OG1i5RjoNXOmNi8+bHQ7Iupfzza9fwLqA+cfgmtfiPy9tYLX3QcfzsxYxwAvKou9GtUOPKB1xXoUl3LvE+5+4Tcrdtj2rs5fb5pk78hjRisZg9H5PLqJY9Xe23Cfwp7dfb5818=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

