table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVlNc+LGFv0rqlnHKpvnKU9204gGtyPUTAtRE1JZNCCYdoTk6IOaePsWqfe75o+9c1tgYBJAjlWVBV0YUX24t8895972L7+8u3n3w7tbvK5vnatxNGJ4y4Ys6DGHjZjinsA7j/u8JwMh8VCvdbrQ7jxO4kWWmuzjMjerLC7KPE7wcbZ2Zzm+dnNFm7779YdjBGcLMRFjqQR2ZkPh+z87Pe5IX0y4UMD1JzzEdzamzHKjXZ1s4qIZzE3HLsBRMsAvliPsSnv1FQs8wX1fOEPmIRinz5UiODxc5jqdmzhJjLuM8zw2uT4JZxEu4z1EvmABc8ZcfLZB9WTohCwYS3r6WCVGp9otdFpmp0P7DuuDXYA1Yb4I7u1OIyVCT/gAUmIgnYEc2tQ95aaYG+y2ytZncme3tAA2juvbegVE+O2/0vEjMcWWwZQNKE1dFQWHgVAm71mPSDHLK4Sz1vMvepF91IlZxxTZXyA7VzVIY8yfmBIBd8DBUPgT5vzkRwN8/JvOTRq7vyXV6nVo7+sVaOIhEnRQUvXooHrMRxaVDJnTlf0+HVKWL+iQZtlyeQHk/Q6E3tx17AIIycMxxx8DLkJwTzgeTmsMXvBjOqxiU4B+ZscHOqo413Od6dSsdbIHe391t+cEhXZ3ZxeA9dmUU9WOI9UV/j1yaY/sZxY4HPUcRNx3HngYhVRrQ1RCfW5/6NRdg/rHdXzjZunazPOsyJYlwVPabq8sWmNwxfoMoH1EPuLOSCBaZ8R3RZfrpY4T9yne1pt+jqErZZXPTPJFZwc0PcKl8H/8cF2vpCesK8FBR7Fvf9awfuQxcBO/h4eHuoJHSTXXhZslZnMJs3NVgzQFRUly0rOD6ugyH1/Bx/R8o5OYtAxr1hyX6EUvQKLkERLtC1Ip7jMrMlT7HHQaMkjMSHhMWnWh2o9RH08GHDpZ/Z2mOLYmoZcBbKEWTkZ/+9CcQNi0mmcoZ1KiKM3b4R5kyB3ei5gCmsfG+NTCPKL63LkusW9TmO9tp8+6QjoPEaxMOWM4WkDyr2cmc0uYWfpGl6FCozrrSjUA+XbijycxXLMC3cvYfG3DX4hi+PWSlNGT4Zg5fdSd9efURpK5S3Dr9OHfnM2Tx5RPZ7I9hM9sIriiYrIKgi/MdZ5khfsYF1UDa26i9KCTDGqVp3wliMKdnTrmI2W/xKetDpG273UH0nb6EJpXBovUYaM0EdABqghd5drdGFT9WZDr6xv3+rrjwkGawGHzz44tj1ACkg4CCF/dItP5GZs/QrptWPIefErutCxgUJpoPK6rfY7mJXNTDZmpyvJ8Kf7ruO/Puf8gQulMpDNEWaEJGLJxGA3lmOpoVRWl3mTuGnaRnqLKkflflmvIDpS6PsEel4EVa/TQa527izg7LT9HEd3t5YFehNYbHuDwAZ+i3YB0KtjSvfzOBONV/Ixu48AGT0nECyheNxdAfQ5zUPKlFvAuouxSKpMYI0OeubqipJ7RpNcAsp6ynVTdF/YiihWeq7rMCqRewG5hgYsqh/e2AwnxC+GxzoB1FRLMXtpSOse4KOC2bmGSTUsp3eoWIyLtp6Ktfp0fil6FE0oY7IAfyJi1eEUFUmQw21Vs5yL03C3lUTL0TsgkecsI7WEY1miPGZqhJ3TCRdEaGLYnY4F0AsVStAs81IN1GVPbTIE4W8JTfAApodbvZWg5aHrjFcQkWWSt8iTqCtIu6j+7GMkEt4aaVzM0nDPMZCZetQQVRlPh1JUHRKk4pJnkJZTRlJ4X1TOmmKx6bgmvZors2eH2oNocy5Q8WxBIazwJqQz8Qz8fSZReQCHSdOiLLq8lFAylsgDcU5aW59rRV/2GAfoJj86Suno60gH0m9EYsw99hd4CRtgmgegwR7yndjJK8onBt03phLPec8ye22GwJzCihZ8iQb6Lx2tdfomrwi1+rwz5bTugGOyFD4VRdm7ZVyHGepNAaHLYUkvs+Z6jVI5jEVjBrllqz8uF05cmbUm4e/d0y1Rf+jjhSIbC2u3iC10vucUTMNty23qorieNUHyKjgbqwvxetddJ7IYOqymHYPGi0rmVzjbhHiQNI5+pXUMWmbudDndu9JXufdpy2re2m6+Eows7uR/ct8TkNEh++5O+QNd2gIxRBum8JVDhh7DbLhsL4gpc3iOnNUkBo83NfN6SVEKsu1arFYseKIFQ5BltqHNdPTZkfecSFSd1x/BS1V02nRJYvKk72pl+fm4Ja6uML7fgHppMK8VLuM0TXXzM8qZqfHuxmqeCQqOZfnd/AEJ69oI/gYdTeHHugolzk33c6IXOSqglJCUv4+If4w7QNwjY6ZaSqLduZPO5Qq9uUuPOqqbpvARloyMm2mGLDShG62uIi6ioochlQ8pfwtreJ+1HH1+OeH3Pj+Eud5PsqamCXISS4bf/OdvJwGMwaw+TMj+aROprMlj3XKfl6fuHv8O9fNH5Zgk7vuFscI38ZsS/3Ft/+I9dDgHrONtBs9uf/7fNW9n54RChc2eX3b3aiEX2bv+NGJ06Z7/+Hw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Exception

