table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVlNc+LGFv0rqlnHKpvnKU9204gGtyPUjISoCaksGmiYdoTk6IOaePsWqfe75o+9c1tgYBJAjlWVBV0YUX24t+855972L7+8u3n3w7tbvK5vnatxPGJ4y4Ys6DGHjVjIPYF3Hvd5TwZC4qFaq3Sh3LlO9CJLTfZxmZtVposy1wk+ztbuLMfXbq5o03e//nCM4GwhJmIsQ4Gd2VD4/s9OjzvSFxMuQuD6Ex7hOxtTZrlRrko2umgGc9OxC3BCGeAXyxF2pb36IQs8wX1fOEPmIRinz8OQ4PBwmat0bnSSGHep81ybXJ2EswiX8R5iX7CAOWMuPtugejJyIhaMJT19rBKjUuUWKi2z06F9h/XBLsCaMF8E93anUSgiT/gACsVAOgM5tKl7yk0xN9htla3P5M5uaQFsHNe39QqI6Nt/pePHYootgykbUJq6YRwcBkKZvGc9KopZXiGctZp/UYvso0rMWlNkf4HsXNUgjTF/YqEIuIMajIQ/Yc5PfjzAx7+p3KTa/S2pVq9De1+vQBMPsaCDkmGPDqrHfGQxlBFzurLfp0PK8gUd0ixbLi+AvN+B0Ju7jl0AIXk05vhjwEWE2hOOh9Maoy74cTmstClQfmZXD3RUOldzlanUrFWyB3t/dbevCQrt7s4uAOuzKSfWjuOwK/x75NIe2c8scDj4HMTcdx54FEfEtSGYUJ/bHyp11yj9Yx7fuFm6NvM8K7JlSfCUttsri9YYPGR9BtA+Ih9xZyQQrTPiO9Llaql04j7pLd/Us4aulFU+M8kXlR2U6REuhf/jh+t6JT1hXYkadEL27c8a1o89htrE7+HRoa7gUVLNVeFmidlcwuxc1SBNQUFJTnp2wI4u8/EVfEzPNyrRpGVYs+a4VF70AiQoj5BoXxRVyH1mRYa4z1FOQwaJGQmPSasuxH0NfjwZ1NBJ9nea4lhOQi8D2EItnIz+9qE5gbBpNc9QzqQEKc3b4R5kxB3ei1kINI+N8amFeQT73LkqsW9TmO9tp8+6QjoPMawsdMZwtIDkX81M5pYws/SNLkNEI551ZThA8e3EH080XLNCuZfafG3DX6jE8OslKaMnozFz+uCd9efURpK5S9TW6cO/OZsnj4U+ncn2ED6zieAhkckqCL4wV3mSFe6jLqoG1txE6VFOMqhVnvKVIAq3MMlGNRX4S2W1lSOS+L38QOFOn0VzgrA4POyXJgJyQMRQVa7cjQH5z4JcX9+419cdF0bSBA6bf3YsSyIJSDoPIHx1i0zlZ9z+COm2IfM92JXcSVrAIDjxeFyTfo4eJnNTBbWpyvI8I/913PfnmoBBDAZNpDMEu9ALDNk4iodyTHRaVUWpNpm7hmukp0rlqAe4rNpQHwh2fYI9LgOr2Wil1yp3Fzo7rUJHEd3tVYJehNYbHuDwAZ+i64CChnCne/mdF+qVfkbTceCGp5TiBRSvmwugPodHhPKFC3gXU3YplYnG5JBnrqooqWek6TWArBfahqpuD3sxxQrrDbvM6qRawHXhhIsqhwW3AwkNjGC1zoB1QySYvXSndI66KGC6W+VqBW6rW4wKaT8cbfXr/Gz0KpxIwmcH/EDGrNOHRJAig+eutB2P0Hq3lEfJ0EIhk2QxI3SJUVSjPWboiZ7QEBdFa2DYnvwF0gkUW6Jd4IEP1mwMuc0MeGBDS6fGB5AS6gBfZpeD3levICbJImu1TuKuIO2iNrSLyUxw66t5NUPfOcNoZvSqJagongqnZh4QZcghzSQvkYyn9LyonjHMZNVzS3h1pcienXEP2ObYSsmzBYG0VicR0cA/9PORBPUCCpGGRF90eS2hqFCiBeCesrQ815W+6jcM0E94dJbU3NORDqDfjKaZfegr9BYwwjYLiA5zxHvhTkZJPjH/timdcNZ7jhF0OxP2BCa16FMsyHfxeK3KL7oq3OL3ypDftgOK+V74UJjQji97FmK6NwmEJocttVQ939co0XEsAivYdZXa83Lh9KVJWxLu3j1dNtV3P040kpGwdrv4QrdMbvEEzLbctp6t64EjEp/io7m6ML9X7XUSu9nDasohmF5UKrfS2Sbcg6SZ5DO1a8gic7dD4s6NvtII0pbTvrXdfCUc3dvJ/fy+LUxO8+S3P+kLdHsHSA0apPOWQIUfwW67bCyoVuDyHjmtSQoYbW7m85akEmLdtVodsviBEghFntGGKlfVY8Oq71wqxUndMbywusumUwLTm7qjnann55awtsr4chnuocm0UryE2zzR/ccsb6rGtxfZPBUUGo32u2sEFKRn7/kTeDiFp3MXlTg32ceNWqishFpCUvJSF/8Yd4C+QcBOtyUJvnVjm88VenWTGndWNU3nJSgbHVWiHbbYgGK0voa4qBQVFLlsWPKXsLbXSvvRx5cjXl/3Y7jL3SR7aqogF6Fk9O1/znYy8BjM2sOkzI8mkfq2DNY9V2l5+v7h73Av33e+WcKOLzob3Ca/GfEv19cf/mOXQ8A6znbQ7Pbn/3vz1ur8cIjQubPL7nptxGJ7xf9GjE6ds1//Dw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

