table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVldc+JGFv0rKj/HKpv1lL1v04gGtyPURELUhFQeGmhjOULt6IOa+HUfUvu75o/tuS0wMAkgx6raB1QYUTrc7vNxb/uXXy6uL364uMHr6sa5HMcjhrdsyIIec9iIhdwTeOdxn/dkICRuqpXKFsqd61QvTJaYz495sjS6KHOd4mOzcmc5vnZ9SQ+9+PWHQwRnAzERYxkKPJkNhe//7PS4I30x4SIErj/hEb6zTkqTJ8pV6VoXzWCuO/YCnFAG+MVyhKfSs/ohCzzBfV84Q+ahGKfPw5DgcPMxV9k80WmauI86z3WSq6NwFuE83kPsCxYwZ8zFF1tUT0ZOxIKxpLvPVZqoTLmFykpzvLTvsO7sBVgT5ovg3j5pFIrIEz6AQjGQzkAO7dK95EkxT/C0pVmdWDv7SAtg67i6qa+AiL79Rzp+LKZ4ZDBlA1qmbhgH+4XQSt6zHpFillcoZ6XmT2phPqs0WWmq7C+QncsapDHmjywUAXfAwUj4E+b86McDfPybypNMu7+l1fJ9aJ/qK9DEQyxoo2TYo43qMR+rGMqIOV3Z79MmmXxBmzQzj49nQD5tQejNbcdeACF5NOb4Y8BFBO4Jx8NujcELfkiHpU4K0C/Z8oG2SudqrozKkpVKd2CfLm93nKDSbm/tBWB9NuWk2nEcdoV/j7W0W/YzCxwOPQcx950HHsURaW0IJdT79ofK3BWof6jja9dkq2Sem8I8lgRPy3ZzadEag4eszwDaR+Uj7owEqnVGfCu6XD0qnboveqM39arhK2WVz5L0SZk9mh7gUvn/vruqr+QnrCvBQSdk3/6sYf3YY+Amfg+P9n0Ft9JqrgrXpMmaMGfJMWF0LmuIppAQJCc329NGl/n4Cj6m+2uVanIyXM2pSg9xiVz0AiQEj4LouaBUyH1mLYaUz0GmIYPBjITHpPUWUr6GOl4SMOio9jtNcawi4ZYBQqG2TUZ/+3CcQNhFTV7hm2kJSR5d0eZwDzLiDu/FLASax8b41MI8Q3vuXJV4blOY70Onz7pCOg8xgix0xsizgMwfPDBuiSjLPpgxJDNSWVeGA1Bva/24o5GZFche6uRrG+lCFMOvl+SLnozGzOlDdTadM1uJcR/BreObf31ynTwW+rQnm034wiaChyQl6x/4wlzlqSncZ11UDYK5ic+DTjKoPZ7WK0UV7lF9Hvj6OT5tXIicfec6MLbjm9BcGSwO99ukiYAPkCJUlSt3nUD1J0Gurq7dq6uOi/xoAoeHf3GsPCIJSNoIIHx1C6PyEyF/gHTTUPIeUkpuvSxgcJp4PK7VPkfrYtxMwWaqsjwtxf877qdT2T+IIZ2JdIaQFVqAIRtH8VCOSUfLqijV2rgrhEV2jCoH0X/ermE7cOp6B3tcBtas0UGvVO4utDluPwcV3e7sgV6E1hvu4fABn6LZgHWGiKV7+V0E6qV+Ra/xFoLHLeINFK/rM6A+RziE8k0LeBfT6tJSphoDQ25cVdGinvCk9wCyXmj7qLor7MVUKzI37DJrkGqBuEUELqoc2dsOJMwvQsY6A9YNscDsrSmlfdRFgbR1iyRdt7SkG99iRKTdTLTxr9Mj0btwIomAHfA9G7MRH5JACoOwXWo7FaHjbmkdJUPvhJWkbBmhOYyiGu3ZoBl6QR9cFK2BhXwAaVMr9jZC7LWgeglxpwvT6r7FXUFeQv1gFwOS4Dbg8mqGBnCGCSnRy5agongqnFoJQJQhh1WS3CMZT+l+Ub1ipjDVa0t49c7Jnh0199jv2J3LzYJA2oEiWhAt/f18HUlIIaASaVbzRZfXlgbGEE0B92Ky8lR7+K7fMEC+e7SX1GXTlg7gp4yGil3pS2Q9gqlNAtFmjngv3Noa2RnG0DatDEl3zzEJbkaznsDAFP0UC8pB3F6p8klXhVv8XiWUf+2AYswWPhQf2jlip0IM2UkK4eeIiZbY8z1HSY5jEVgDrVlq98tF8pZJ1pKR9u7pzKc+gnGikYyEjb/FEx32uMULMNtKv3rErTv/SPwUH4y3RfJ71V6yb4cA6yn7YHpRqdxaZ5twD5KGgy/UPmEVmbuZ1rbp8JVOYdpKvo+2f++Eo+MzuRukN8TkNNh9+5O+QIdogNSQQTZvCVT4EeaqLhsL4gpS16OkTdIC81WezOctWSXMumu9OmTxAy0gHHlGD1S5qp4bsr5zjoqTusl8U3WXTacEptd1hzlTr68tYW2c8e1M2kPTZ634EWnzQgcRs7ypG9+cVfNUUGk0Y2/neRDSs8ftKTKcytO5CybOE/N5rRbKlHBLWEpe6uIf4w7QNwjE6YaS0Fs3tuu5RO+cZIk7q5ou5zkoWx0x0Q4/bEA12lxDXURFBUcuG1L+HNbmfGc3ivhyxOtTdwxbuZual6YOchZKRt/+62w6dY8hrD1MrvxgMqiPrRDdc5WVx88D/g73/MHjhy3s8MSxwaHuhxH/cop89y972Qes62wHzT7+9D9RPsrOu32Ezq29bM+5Riy2J+0fxOjcXjQ8Z/iYqg+OGu7O0P+eeqxtr4VBFfFCQE/VEtP+SiNfmtvHr/8D", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

