table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVlNc+JGEP0rKp9jlU28Zee2IzHgcYSGSIjakNrDAIIdr5AcfVAbX3NI5XftH8vrERjYDSDHqsqBKYyoefRMv/e627/9dnF98cPFDV5XN9blKBoyvGUD5neZxYYs4K7AO5d7vCt9IfFQrVQ6V/YsTuJ5lurs/SLXyywuyjxO8HG2sqc5vnZ9SZtefPzhEMHaQIzFSAYCO7OB8LxfrS63pCfGXATA9cY8xHfWusxyrWyVrOOiGcx1xyzACaSPXyyH2JX26gXMdwX3PGENmItgrB4PAoLDw0Wu0pmOk0TbizjPY52ro3AG4TzeQ+QJ5jNrxMUHE1RXhlbI/JGkp49VolWq7EKlZXY8tG+w7swCrDHzhH9vdhoGInSFB6BA9KXVlwNzdE+5LmYauy2z1YmzM1saABPH1U29AiL8+qe0vEhMsKU/YX06JieI/P1A6CTvWZeSYppXCGelZp/UPHuvEr2KKbLvIDuXNUhjzJ9ZIHxuIQdD4Y2Z9bMX9fHxZ5XrNLY/J9XydWjv6hVo4iESdFEy6NJFdZmHUwxkyCxH9np0SVk+p0uaZovFGZB3WxB6c9sxCyAkD0ccf/S5CJF7wnJxWyPkBT9Mh2WsC6Sf3uYDXVWcq5nKVKpXKtmBvbu83eUEhXZ7axaA9diEE2tHUeAI7x5naa7sV+ZbHHz2I+5ZDzyMQuLaAEyo7+0PldorpP4hj6/tLF3pWZ4V2aIkeDq2m0uD1hg8YD0G0B4iH3JrKBCtNeRb0uVqoeLEfoo3fFPPMXSlrPKpTj6pbC9ND3Ap/J/uruqV9IQ5EjloBezrXzWsF7kMuYnfw8N9XcGjpJqpws4SvT6H2bmsQZqCgpKc9GyPHQ7z8BV8TM/XKolJy7BmzXEpvegFSFAeIdG+SKqAe8yIDHGfI50GDBIzFC6TRl2I+zH48aSRQ0fZ32mKYzgJvfRhC7VwMvrbg+b4whyrfoZyJiVIqd8O9yBDbvFuxAKguWyETw3MI9hnz1SJfZvCfGs7PeYIaT1EsLLAGsHRfJJ/NdWZXcLM0je6DBGNeObIoI/k24o/nsRwzQrpXsb6Sxv+QimGXy9JGV0ZjpjVA++MP6cmksxeILeOX/71yXNyWeDRnWwu4QMbCx4QmYyC4AszlSdZYT/GRdXAmpsoPdJJ+rXK03kliMKeHrvmA2U/l08bHSJt3+kOpO34JTRnBouC/UJpLKADxAhV5cpea7D+JMjV1bV9ddWx4SBN4LD5B8vQI5SApIsAwhe7yFR+wuYPkG4aUt6FT8mtlvkMShONRjXbZyheMjtVkJmqLE9T8X/HfXfK/fsRqDOW1gC0QhEwYKMwGsgR8WhZFaVaZ/YKdpEeS5UD8z8v15AdKHV9g10ufSPWqKFXKrfncXZcfg4iut3JA70IrTvYw+F9PkG5AekMYEv38hsTjJfxM6qNPRs8JhEvoHhdnwH1OMwhkC9cwLuITpeOMonRMuSZrSo61BOa9BpA1g1MJVXXhd2IYoXnBg4zAqnmsFtY4LzK4b3tQEL8Qnis1WdOgANmL2Up3WNcFHBbu9DJuqUj3egWo0TadUUb/TrdFL0KJ5Qw2D7fkzFj8QERpMhgtsvY9EWouVs6R8lQO+EkyVuGKA/DsEZ7zFAMPaESLorWwLA9GQukEygmRR3ggQ/GZXRtMwXibAkv4H1ICZV+L03LXtEbLyEmyTxrNU8iR5B2Uf3poCUT3BhqXk1RcE7Rk+l42RJUGE2EVTMPiDLgkGaSl1BGE3peVM/oYrLquSW8OlNk1zS3e2yzTKbk2ZxAWsuTkGjg7fv5UIJ6PoVI3aEnHF5LKDKUaAG4pywtT5Wjr/oNfdQTLt0lVfV0pX3oN6M2Zhf6ErUFjLDNBKLLHPJusJVRkk80vm1KJ5z1nqP33DSDXYEWLfwlEuS7eLxS5ae4Kuzi90qT37YDisZeeFCYwPQtOxairdcJhCaHLbWUPd/mKNFxJHwj2HWWmvuy4fSlTlsS7u49TZnqoY8VDmUojN3OP9F4yS6egNmW29ZNdd1phOKX6KChLvTvVXuVxLbpMJqyDxbPK5Ub6WwT7kFSM/KByjWcIrM33eHWjb7Q3Kctp31ruflKOBrYyV3jvklMTo3k17/oCzS2A2QMGqSzlkCFF8JuHTYSlCtweZecVicFjDbXs1lLUgmxdoxWByx6oAOEIk9pQ5Wr6rFh1nfOpeK4rhheWO2wyYTA4nVd0U7V83NLWBtlfJmCuygyjRQv4DZPNPiY5k3V+OYsmyeCQqOefjs/QEK6ZsCfwMMpvDi3kYkznb1fq7nKSqglJCUv4+I/4/ZRNwjY6SYlwTcnMue5RK2uU21Pq6bHeQ7KREeZaJot1qcYja8hLkpFBUUuG6b8OazNPGnX+nhyyOs5P5q73E6yp6YKchZKhl//tjadgctg1i46ZX7QidRjMlj3TKXl8fnDv+GeH3S+WcIOJ5wNxshvRvxubn33o1n2Aes420Ez25/+t81bs/NuH6Fza5btXG3IIjPbfyNG5/ai4Vzjbaw+GG3cXXz8+A8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

