table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVnLcuJGFP0VldexysaesrObRjTQHqEmelAzpLJoRBvLI5AjIWribRapfNf8WM5tgQ2TAeRBlSxQAaL6cF/n3Hv1669nl2c/nV3jdXFtnYfRkOEtGzCvwyw2ZD53BN453OUd6QmJm2quFlNlxzrV02yRZO/v82SW6WKZ6xRfZ3N7kuNnl+d06NlvP+0iWGuIkQilL3AyGwjX/WR1uCVdMeLCB6474gF+s0qWWZ4oW6UrXdSDuWyZC3B86eEfyyFOpbO6PvMcwV1XWAPmwBiry32f4HDzPleLONFpmtj3Os91kqu9cAbhON5d5ArmMSvk4qMxqiMDK2BeKOnuY5kmaqHsQi2W2X7TvsG6NRdgjZgrvL45aeiLwBEugHzRk1ZPDozrnvKkiBOcNsvmB3xnjjQAxo6L6+oKiODrn9JyIzHGkd6Y9chNbT/ytg0hT/ZZh5JikpcwZ67iBzXN3qs0mWuy7F+QrfMKpDbmB+YLj1vIwUC4I2Z9cKMevv6s8mSh7c9pOXsb2rvqCjRxFwkKlPQ7FKgOc+FFXwbMastul4KU5VMK0iS7vz8C8m4DQm9uWuYCCMmDkONDj4sAuScsB9EKkRd8Nx1mOimQfskmHyhUOlexytQimav0Fezd+c1rTpBpNzfmArAuG3Oq2jDy28Ltw5cmZJ+YZ3HUsxdx17rjQRRQrQ1QCXT/Xj1rquZJsi9Hrs8NRG1En3UZkLowd8itoYCJ1pBvKi1X9yq9h6lPui4m2fvz7UV1JQJhbYmks3z29a8K0o0chmTEf+HBNpHgVlrGqrCzNFlRUe9HbJ1XEHUhUYGc6GurGNrMxU/wNd1fqVQTdeEKgqycvCzzSZI+qGwvLmUTvQCJCodBdC5yyOcuM5xCpc6RPQMGRhkKh0lDJlTqGuXwlCBl9hZ7qy6OKUHQowcVqHiS0WcXFOMJ49TkGUSZLlGDez1aH+5OBtzinYj5QHNYiG8NzCOKzY7VEufWhflWZbqsLaR1F0G5fCuEgHkm5ydJZi+hXYsTRYXqisqqLf0eUm/D9bijIZKlTu2lTr40ISeUYvj3kojQkUHIrC4qzsjxwliS2ffIrf3BvzzoJ4f5LsVkHYSPbCS4T6VkCAM/iFWeZoX9qIuyhhLXIXakk/QqUid/pbBiPyPsEPmxfFozEFH5mnEQiDwr9gehfmWwyN/ui0YCPEAVocpc2asEVX8Q5OLi0r64aNkQjDpwOPyjZcojkICkQADhi11kKj+g6jtI1zVL3oEsyQ2XeQxME4VhVe0xepXMXijQTLlcHi7F/x333SGx70UonZG0BigraP6AhUE0kCHV0awslmqV2XOIxWJfquxo/XG6Bu2AqasIdrj0DFmjZZ6r3J7qbD/97Fh080oP9CK0zmALh/f4GN0FqNOHLPXlNxKoZ/oZzcWLCO6niBdQvC6PgLoc4uDLl1rAu4i8S65MNSaEPLNVSU49wElvAWQd3zROVRvYichWaK7fZoYg1RRyCwmcljm0txlIkF8AjbV6rO3DweylC6U46qKA2tpFkq4acumatxgl0usQtOavwzPQm3ACCYHt8S0aMxLvU4EUGcR2ps0YhBa7IT9Kht4JniRtGaIxDIIK7TFDM/SEbrAoGgPzeQ+lTa3Yy8yw1X7qGYo7nWaNxi1qC+IS6gfbmIgENwKXlxM0gBOMRImeNQQVRGNhVZUAROlzUCWVeyCjMd0vymcMEVn53BBeFTnZMbPlVvZbJnJ5NiWQZqAoLSgt3W19HUqUgkcm0nDmijavKA0ZQ2kKuKdssTzUHr7pP/Sg7w7FkrpsCmkPfMpoqHg1fQathzA1mUAUzCHv+BtaIzrD3NkklUHp+hyj33os6wgMTMEvkSAdxO25Wj7osrCL38uE9K8ZUMzVwkXF+2aOeK1CTNVJisLPIRMNZc+3OUrlGArPEGiVpSZeNpR3mSwaItJOn5Y81c7FCoYyEEb+pg+03bGLJ2A2pX7ViFt1/oH4JdoZb4vk97I5Zd8MAYZTtsH0tFS5oc4m4e4kDQcfqX2CF5m9ntY26vCF1i5NKd+p7d8b4WhfJl8H6XVichrsvv5FP6CtGSA1ymARNwQq3ABzVZuFgnIFquuQ0iZpgfkqT+K4IaoEWbcNV/ssuiMHgpEndKDKVflYM+tbx1JxVDWZL1XdZuMxgelV1WFO1PNzQ1hrZnxZQjto+gwVr7dVsZrkddn4+mg1jwWZRjP2Zp5HQjpmv55Cw8k8ndvIxDjJ3q/UVGVLsCUoJV/q4odxe+gbBOR0nZKot3Zk/DlD75wsEntS1nXnMShjHWWiGX5Yj2w0uga7KBUVGHlZM+WPYa33O6+jiCuHvFqzY9jK7TR7qssgR6Fk8PVva92pOwxi7WBy5TuTQbW2gnTHarHcvw/4Hu7xxePJFLa7cayx0D0Z8V8b5Nsrc9kGrOxsBs0cf/ipyanZebuN0Loxl82ea8gis1o/EaN1c1Zzz3BaVe+sGm6PpH+feqxNr4VBFfJCQA/lDNP+XENf3kwfhyxDEwdyBCD6/pCU1EMP6fTPqGHN46zAmLrQuY4f3rpIOQRa7YypmjdPB82+mPrHg13PD0B94PTos3oo5O2sFz7rNP3jyIyxB/CqutDjpyj0gdcV6FJdy3xPsfuE2K3bY9q7OX2+aZP/QBgxWMUPB+jy6iWOVzttwn8Ke1UPlvKHHnRZm/EHX6CdDdYJBB9nNBGgnW3Y3uaBr44OeKcj7uuXvsegjeDdbgAvb3cXt4cfHZyOvXmeQKWDd8e7w9MT+C3ObQDtB117KvL3HPvbPw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

