table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("lZTBbuIwEIZfxeJcooKo6N46BEPdmjhyCNq26sGAod4mceUA0u61h32wvtjOhFalWnXLHjJK4uj/MjP/zN1dq9M6afXwOu2x9jRPAW9hAskQGKSgeSzwLuaSD1UiFB6a0lRLEy1sYZe+cv5iFdza23oTbIGvfRnNA37Wafda9ycf5dmr/kxMlRYoCxMh5Q0bcqakmHGhESpnPMNvdm7jgzORKXa2PoLR6TYBIVol+K8qRUkSGmlIYsGlFGwCMabBRlxrYuHhKphq4WxRuGhlQ7AumE9ZSPgSdpVLAQmwKRffm3SGKmMZJFNFpz+2hTOViWpTbfznSR2CzpuAoBlIkVw2MqkWWSwkUrQYKzZWk6ZiT8HVC4dSa1/+o2QoSepNBqe9fUT97OVZMZmLW9RLbmFM1RnoPDlMgQp4CUNywTxsMZHSLB7M0l+YwpWWcvqL120T5FjgNWiRcIaOy4ScAbuW+RhfP5rgKhs9Ftv1f6DO9hFR4ioX1Bylh9ScIUgsnlYZsIEajagxPiypMXO/Wn1BOGsIpN3vNgH1Fc+mHB/GXGToNMFi7NAUjcA/9n9tXY1mc28GoPbYYBbGm8qVpngnnbX7ryaggvX7TUDSCG45jeY01wMhL7GETZtuIGEchzbJuWRXPMszmqkJmn7fq5+mikp0+cdh7US+Kt0i+NqvNsSmgvXaSDuWrGEESBxhzilnqcA8WcrfhiuYlbFF9GRf58r8srg5Ntswd8WD8QemfIdSTb+dn+4jbQwYKHQc0/Dye8+UeQzoRPwZnh1uDjwqtgtTR75wu6+A3TZBjiTi6HFaVweDMACJn+BrOt+ZwtKqwuiPhJKZ6EIezjUmQ6LoIs0lNGuEBpyjfyaASyQVMahmf9CAWxyFJ4em+XTE0Tr3fwA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

