table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVlNc+LGFv0rKq9jlc3zlJ3dNKLB7Qg1kRA1ITWLBmSmHaF29EFNvM0ild81f+yd2wIDkwfIz6rKgi6MqD7c2/ecc2/7118vri9+uLjB6+rGuRzHI4a3bMiCHnPYiIXcE3jncZ/3ZCAkHqqVyhbKnSdpsjCZNh8fc700SVHmSYqPzcqd5fja9SVtevH5h0MEZwMxEWMZCuzMhsL3f3F63JG+mHARAtef8AjfWevS5Fq5Kl0nRTOY645dgBPKAL9YjrAr7dUPWeAJ7vvCGTIPwTh9HoYEh4ePucrmOklT7T4meZ7oXB2Fswjn8R5iX7CAOWMuPtmgejJyIhaMJT19qlKtMuUWKivN8dC+w7qzC7AmzBfBvd1pFIrIEz6AQjGQzkAObeqec13MNXZbmtWJ3NktLYCN4+qmXgERfftTOn4sptgymLIBpakbxsF+IJTJe9ajopjlFcJZqfkXtTAfVapXCUX2D8jOZQ3SGPMnFoqAO6jBSPgT5vzkxwN8/JvKdZa4v6XV8m1oH+oVaOIhFnRQMuzRQfWYjyyGMmJOV/b7dEgmX9Ahzczj4xmQD1sQenPbsQsgJI/GHH8MuIhQe8LxcFpj1AU/LIdloguUn97WAx1Vkqu5MirTK5XuwD5c3u5qgkK7vbULwPpsyom14zjsCv8eubRH9gsLHA4+BzH3nQcexRFxbQgm1Of2h8rcFUr/kMfXrslWep6bwjyWBE9pu7m0aI3BQ9ZnAO0j8hF3RgLROiO+JV2uHlWSus/Jhm/qJYGulFU+0+kXZfbK9ACXwv/x7qpeSU9YV6IGnZB9+6uG9WOPoTbxe3i0ryt4lFZzVbgm1WvCnOljxOhc1hBNIUFITmq2x40u8/EVfEzP1ypNSMmwmlORHuJScdELkCA8AqJ9UVIh95mVGGI+RzENGQRmJDwmrbYQ8xOw41mjgo5yv9MUxzISahnAFGrZZPS3D8UJhE2qfoFupiUoeTSjzeEeZMQd3otZCDSPjfGphXkC99y5KrFvU5jvTafPukI6DzGMLHTG8LOAxB91YNwSVpa902OIZsSyrgwHKL2t9ONJAs+sUOxlor+24S5UYvj1knTRk9GYOX2wzrpzZiMx7iNq6/jhX5/Mk8dCn85kcwif2ETwkKhk9QNfmKs8NYX7lBRVA2NuovMoJxnUGk/5ShGFe5SfB7p+rp42KkTKvlMdCNvxQ2jODBaH+23SREAHiBGqypW71mD9SZCrq2v36qrjwj+awGHzT46lRyQBSQcBhK9uYVR+wuQPkG4aUt6DS8mtlgUMShOPxzXb52hdjJspyExVlqep+K/jfjjl/YMY1JlIZwhaoQUYsnEUD+WYeLSsilKtjbuCWWTHSuXA+s/LNWQHSl2fYI/LwIo1OuiVyt1FYo7Lz0FEtzt5oBeh9YZ7OHzAp2g2IJ0hbOlefmeByTJ5Qa/xaoLHJeIVFK/rM6A+hzmE8pULeBdTdimVaYKBITeuqiipJzTpLYCsF9o+qu4KezHFCs8Nu8wKpFrAbmGBiyqH97YDCfGL4LHOgHVDJJi9NqV0jklRwG3dQqfrllK60S1GhbSbiTb6dXokehNOJGGwA74nY9biQyJIYWC2y8RORei4W8qjZOidkEnylhGawyiq0Z4MmqFn9MFF0RpYyAegNrViryPEXguaLEHudGFaPbe4K0hLqB/sYkAS3BpcXs3QAM4wIelk2RJUFE+FUzMBiDLkkEqieyTjKT0vqhfMFKZ6aQmvPjnZs6PmXvU79uRysyCQdqCoLKgs/X1/HUlQIaAQaVbzRZfXkoaKoTIF3LPJylPt4Zt+wwD+7tFZUpdNRzqAnjIaKnahL+H1MKY2C4gOc8R74VbWSM4whrYpZXC6e45JcDOa9QQGpujnWJAP4vFKlV+SqnCL3ytN/tcOKMZs4YPxoZ0jdizEkK1TED+HTbRUPd/XKNFxLAIroHWV2vNy4bylzloS0t493fnUVzBONJKRsPa3+EKXPW7xDMy23K8ecevOPxI/xwfjbaF/r9pz9u0QYDVlHyxZVCq30tkm3IOk4eATtU/IInM309rWHb7SLUxbzvfe9u+NcHR9JneD9KYwOQ123/6iL9AlGiAT0CCbtwQq/AhzVZeNBdUKXNcjp9Vpgfkq1/N5S1IJse5arQ5Z/EAJhCLPaEOVq+qpYdV3zpXipG4yX1ndZdMpgSXrusOcqZeXlrA2yvh6J+2h6bNS/Ai3eaaLiFneVI1vzrJ5Kig0mrG38zwK0rPX7Sk8nMJLcheVONfm41otlCmhlpCUvEyK/xt3gL5BwE43JQm+dWObzyV6Z51pd1Y1Tec5KBsdVaIdftiAYrS+hrioFBUUuWxY8uewNvc7u1HElyNe37pj2Mrd1Dw3VZCzUDL69rez6dQ9BrP2MLnyg8mgvraCdc9VVh6/D/hfuOcvHt8tYYc3jg0udd+N+I9b5Lv/2GUfsI6zHTS7/el/ory3Ou/2ETq3dtnec41YbG/a34nRub1oeM/wPlYfXDXcXXz+/F8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

