table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVnLcuJGFP0VldexysaesrObRjTQHqFm9KBmSGXRiDaWRyBHQtTE2yxS+a75sZzbAhsmAeRBlSxQAaL6cF/n3Hv1yy9nl2c/nV3jdXFtnYfRkOEtGzCvwyw2ZD53BN453OUd6QmJm2quFlNlxzrV02yRZO/v82SW6WKZ6xRfZ3N7kuNnl+d06NmvP+0iWGuIkQilL3AyGwjX/Wx1uCVdMeLCB6474gF+s0qWWZ4oW6UrXdSDuWyZC3B86eEfyyFOpbO6PvMcwV1XWAPmwBiry32f4HDzPleLONFpmtj3Os91kqu9cAbhON5d5ArmMSvk4pMxqiMDK2BeKOnuY5kmaqHsQi2W2X7TvsO6NRdgjZgrvL45aeiLwBEugHzRk1ZPDozrnvKkiBOcNsvmB3xnjjQAxo6L6+oKiODbH9JyIzHGkd6Y9chNbT/ytg0hT/ZZh5JikpcwZ67iBzXN3qs0mWuy7B+QrfMKpDbmB+YLj1vIwUC4I2Z9cKMevv6i8mSh7S9pOXsb2rvqCjRxFwkKlPQ7FKgOc+FFXwbMastul4KU5VMK0iS7vz8C8m4DQm9uWuYCCMmDkONDj4sAuScsB9EKkRd8Nx1mOimQfskmHyhUOlexytQimav0Fezd+c1rTpBpNzfmArAuG3Oq2jDy28Ltw5cmZJ+ZZ3HUsxdx17rjQRRQrQ1QCXT/Xj1rquZJsi9Hrs8NRG1En3UZkLowd8itoYCJ1pBvKi1X9yq9h6lPui4m2fvz7UV1JQJhbYmks3z27c8K0o0chmTEf+HBNpHgVlrGqrCzNFlRUe9HbJ1XEHUhUYGc6GurGNrMxU/wNd1fqVQTdeEKgqycvCzzSZI+qGwvLmUTvQCJCodBdC5yyOcuM5xCpc6RPQMGRhkKh0lDJlTqGuXwlCBl9hZ7qy6OKUHQowcVqHiS0WcXFOMJ49TkGUSZLlGDez1aH+5OBtzinYj5QHNYiG8NzCOKzY7VEufWhfleZbqsLaR1F0G5fCuEgHkm5ydJZi+hXYsTRYXqisqqLf0eUm/D9bijIZKlTu2lTr42ISeUYvj3kojQkUHIrC4qzsjxwliS2ffIrf3BvzzoJ4f5LsVkHYRPbCS4T6VkCAM/iFWeZoX9qIuyhhLXIXakk/QqUid/pbBiPyPsEPmxfFozEFH5mnEQiDwr9gehfmWwyN/ui0YCPEAVocpc2asEVX8Q5OLi0r64aNkQjDpwOPyTZcojkICkQADhq11kKj+g6jtI1zVL3oEsyQ2XeQxME4VhVe0xepXMXijQTLlcHi7F/x333SGx70UonZG0BigraP6AhUE0kCHV0awslmqV2XOIxWJfquxo/XG6Bu2AqasIdrj0DFmjZZ6r3J7qbD/97Fh080oP9CK0zmALh/f4GN0FqNOHLPXldxKoZ/oZzcWLCO6niBdQvC6PgLoc4uDLl1rAu4i8S65MNSaEPLNVSU49wElvAWQd3zROVRvYichWaK7fZoYg1RRyCwmcljm0txlIkF8AjbV6rO3DweylC6U46qKA2tpFkq4acumatxgl0usQtOavwzPQm3ACCYHt8S0aMxLvU4EUGcR2ps0YhBa7IT9Kht4JniRtGaIxDIIK7TFDM/SEbrAoGgPzeQ+lTa3Yy8yw1X7qGYo7nWaNxi1qC+IS6gfbmIgENwKXlxM0gBOMRImeNQQVRGNhVZUAROlzUCWVeyCjMd0vymcMEVn53BBeFTnZMbPlVvZbJnJ5NiWQZqAoLSgt3W19HUqUgkcm0nDmijavKA0ZQ2kKuKdssTzUHr7pP/Sg7w7FkrpsCmkPfMpoqHg1fQathzA1mUAUzCHv+BtaIzrD3NkklUHp+hyj33os6wgMTMHHSJAO4vZcLR90WdjFb2VC+tcMKOZq4aLifTNHvFYhpuokReHnkImGsuf7HKVyDIVnCLTKUhMvG8q7TBYNEWmnT0ueaudiBUMZCCN/0wfa7tjFEzCbUr9qxK06/0B8jHbG2yL5rWxO2TdDgOGUbTA9LVVuqLNJuDtJw8Enap/gRWavp7WNOnyltUtTyndq+/dGONqXyddBep2YnAa7b3/SD2hrBkiNMljEDYEKN8Bc1WahoFyB6jqktElaYL7KkzhuiCpB1m3D1T6L7siBYOQJHahyVT7WzPrWsVQcVU3mS1W32XhMYHpVdZgT9fzcENaaGV+W0A6aPkPF621VrCZ5XTa+PlrNY0Gm0Yy9meeRkI7Zr6fQcDJP5zYyMU6y9ys1VdkSbAlKyZe6+GHcHvoGATldpyTqrR0Zf87QOyeLxJ6Udd15DMpYR5lohh/WIxuNrsEuSkUFRl7WTPljWOv9zuso4sohr9bsGLZyO82e6jLIUSgZfPvLWnfqDoNYO5hc+c5kUK2tIN2xWiz37wP+Dff44vFkCtvdONZY6J6M+I8N8u2VuWwDVnY2g2aOP/zU5NTsvN1GaN2Yy2bPNWSRWa2fiNG6Oau5ZzitqndWDbdH0r9PPdam18KgCnkhoIdyhml/rqEvb6aPQ5ahiQM5AhB9f0hK6qGHdPpn1LDmcVZgTF3oXMcPb12kHAKtdsZUzZung2ZfTP3jwa7nB6A+cHr0WT0U8nbWC190mv5+ZMbYA3hVXejxUxT6wOsKdKmuZb6n2H1G7NbtMe3dnD7ftMm/I4wYrOKHA3R59RLHq5024T+FvaoHS/lDD7qszfiDL9DOBusEgo8zmgjQzjZsb/PAV0cHvNMR9/VL/8agjeDdbgAvb3cXt4cfHZyOvXmeQKWDd8e7w9MT+C3ObQDtB117KvIBx/7njwF+/Rs=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

