table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVlNc+LGFv0rKq9jlY09Zb/dNKKB9gg10Qc1QyqLRjRYHoEcCVETb98i9X7X/LGc2wIbJgHkoMpboAJE9eF+nXPv1S+/XFxf/HRxi9fVrXUZRkOGt2zAvA6z2JD53BF453CXd6QnJG6qhVpOlR3rVE+zZZJ9nOXJPNPFKtcpvs4W9iTHz64v6dCLX3/aR7A2ECMRSl/gZDYQrvvF6nBLumLEhQ9cd8QD/GadrLI8UbZK17qoB3PdMhfg+NLDP5ZDnEpndX3mOYK7rrAGzIExVpf7PsHh5ixXyzjRaZrYM53nOsnVQTiDcBrvIXIF85gVcvHZGNWRgRUwL5R096lME7VUdqGWq+ywaT9g3ZsLsEbMFV7fnDT0ReAIF0C+6EmrJwfGdc95UsQJTptniyO+M0caAGPH1W11BUTw/b/SciMxxpHemPXITW0/8nYNIU/2WYeSYpKXMGeh4kc1zT6qNFlosuwvkK3LCqQ25ifmC49byMFAuCNmfXKjHr7+qvJkqe2vaTl/H9qH6go08RAJCpT0OxSoDnPhRV8GzGrLbpeClOVTCtIkm81OgHzYgtCbu5a5AELyIOT40OMiQO4Jy0G0QuQF30+HuU4KpF+yzQcKlc5VrDK1TBYqfQP7cHn3lhNk2t2duQCsy8acqjaM/LZw+/ClCdkX5lkc9exF3LUeeBAFVGsDVALdn6kXTdU8SQ7lyO2lgaiN6LMuA1IX5g65NRQw0RrybaXlaqbSGUx91nUxyd7/3F9VVyIQ1pZIOstn3/+oIN3IYUhG/Bce7BIJbqVlrAo7S5M1FfVhxNZlBVEXEhXIib52iqHNXPwEX9P9tUo1UReuIMjKyasynyTpo8oO4lI20QuQqHAYROcih3zuMsMpVOoc2TNgYJShcJg0ZEKlrlEOzwlS5mCxt+rimBIEPXpQgYonGX12QTGeME5NXkCU6Qo1eNCj9eEeZMAt3omYDzSHhfjWwDyh2OxYrXBuXZgfVabL2kJaDxGUy7dCCJhncn6SZPYK2rU8U1Sorqis2tLvIfW2XI87GiJZ6tRe6eRbE3JCKYZ/L4kIHRmEzOqi4owcL40lmT1Dbh0O/vVRPznMdykmmyB8ZiPBfSolQxj4QazyNCvsJ12UNZS4DrEjnaRXkTr5K4UVhxlhj8hP5dOGgYjKN4yDQORZcTgI9SuDRf5uXzQS4AGqCFXmyl4nqPqjIFdX1/bVVcuGYNSBw+GfLVMegQQkBQII3+wiU/kRVd9Duq1Z8g5kSW65zGNgmigMq2qP0atk9lKBZsrV6ngp/t9xPxwT+16E0hlJa4CyguYPWBhEAxlSHc3LYqXWmb2AWCwPpcqe1p+ma9AOmLqKYIdLz5A1WuaFyu2pzg7Tz55Fd2/0QC9C6wx2cHiPj9FdgDp9yFJf/iCBeq5f0Fy8iuBhingFxev6BKjLIQ6+fK0FvIvIu+TKVGNCyDNbleTUI5z0HkDW8U3jVLWBnYhsheb6bWYIUk0ht5DAaZlDe5uBBPkF0Firx9o+HMxeu1CKoy4KqK1dJOm6IZdueItRIr0NQRv+Oj4DvQsnkBDYHt+hMSPxPhVIkUFs59qMQWixG/KjZOid4EnSliEawyCo0J4yNEPP6AaLojEwn/dQ2tSKvc4MO+2nnqO402nWaNyitiAuoX6wjYlIcCNweTlBAzjBSJToeUNQQTQWVlUJQJQ+B1VSuQcyGtP9onzBEJGVLw3hVZGTHTNb7mS/ZSKXZ1MCaQaK0oLS0t3V16FEKXhkIg1nrmjzitKQMZSmgHvOlqtj7eG7/kMP+u5QLKnLppD2wKeMhoo30+fQeghTkwlEwRzyjr+lNaIzzJ1NUhmUrs8x+m3Gso7AwBT8HAnSQdxeqNWjLgu7+K1MSP+aAcVcLVxUvG/miLcqxFSdpCj8HDLRUPb8mKNUjqHwDIFWWWriZUN5V8myISLt9GnJU+1crGAoA2Hkb/pI2x27eAZmU+pXjbhV5x+In6O98bZIfiubU/btEGA4ZRdMT0uVG+psEu5B0nDwmdoneJHZm2ltqw7faO3SlPKd2/69E472ZfJtkN4kJqfB7vsf9APamgFSowyWcUOgwg0wV7VZKChXoLoOKW2SFpiv8iSOG6JKkHXbcLXPogdyIBh5QgeqXJVPNbO+dSoVR1WT+VrVbTYeE5heVx3mRL28NIS1YcbXJbSDps9Q8WZbFatJXpeNb09W81iQaTRjb+d5JKRj9uspNJzM07mNTIyT7ONaTVW2AluCUvKVLv4xbg99g4CcblIS9daOjD/n6J2TZWJPyrruPAVlrKNMNMMP65GNRtdgF6WiAiOvaqb8KazNfudtFHHlkFdrdgxbuZ1mz3UZ5CSUDL7/z9p06g6DWDuYXPneZFCtrSDdsVquDu8D/g739OLxbArb3zjWWOiejfiXDfL9jbnsAlZ2NoNmjj/+1OTc7LzfRWjdmct2zzVkkVmtn4nRuruouWc4r6r3Vg33J9K/Tz3WttfCoAp5IaDHco5pf6GhL++mj2OWoYkDOQIQfX9ISuqhh3T6F9Sw5nFWYExd6lzHj+9dpBwDrXbGVM3bp4NmX0z949Gu5x9AfeL06LN6KOTtrRe+6jT9/cSMcQDwprrQ46co9IHXFehSXct8T7H7gtht2mPauzl9vm2Tf0cYMVjFj0fo8uY1jjd7bcK/CntTD5byhx50WdvxB1+gnQ02CQQfZzQRoJ1t2N7mgW9ODnjnIx7ql/6OQRvBu98CXt/vL26PPzo4H3v7PIFKB++Mtb/+CQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

