table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("lZTPTuMwEMZfxeqZRlAVlb0xTZxicOPISaoFxMFt3eLFiZH7R9q9ctgH48V2nBZt0QroHjJKbOv7ZWa+8f1956xz0unjc9on3bLKAV9hDFkCBHKQNGb4FlNOE5ExgZuqVs1cRTNt9dw1xl0uvFk6vVp7bXHZ1dHU47Gzbr/zcPJenuz1J6wUkqEsjBnntyShRHA2oUwilE9ogWe2Zu28UZGyW706gnHWawNCpMjwX0WOkkEolZDFjHLOyBhiTIOkVMrAws2FV83MaGtNtNDea+PVhywkfAm7rjiDDEhJ2fc2nUQUpICsFGH3x8Ya1ahopZq1+zipQ9BFGxA0Ac6yq1Yml6yIGUeKZCNBRmLcVuzZm9XMoNTS1Z+UDCWDepvBaX8XUb94fRGEV+wO9bI7GIXqDGWVHaYQCngFSXDB1G8wkVrNHtXcXSprah1y+ofX6wbIscAbkCyjBB1XMD4BcsOrES4/KW8aHT3ZzfI/UOe7iCh2XbHQHCGT0JwEOBZPigLIUKRpaIzz89CYqVssviCct4SgPei1AfUFLUqKHyPKCnQaIzF2qEQj0Pf9X2qzQrOZNwOE9mivZsqpxtTK/iWddwd7E4SCDQZtQFIKdzSMZlnJIeNXWMK2TbeQEYpDm1WUk2taVEWYqTGaftern6qJanQ5Dqv6pXF81xs/NfZRuQNn9LvIOZYpIQVkpZhtTknOMEOS07ex8mqhtI2e9X6ijoGGan67ON3FcFfAUKDXiITX3zsmr2JAD+LP0OLwzsAtu5mpVeSs2X4F7HUD5EgiDh0NF9XBCAyB4xFcDvtbZXW4pDB+Wto99OEP", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

