table dAcessoUsuarios
	lineageTag: 93534a41-6361-47de-9943-9f61e65b8d20

	column COLIGADA
		dataType: string
		lineageTag: 61029d6e-492e-4414-a1b6-0d4e6af8f6ab
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 6c67f783-1160-48a8-9081-cb8d43837548
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: b9bf5df3-191f-49f2-b5ee-9f683f482649
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 3939d34d-2fc0-459b-8500-48a6d4b348de
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: c787b63d-1cc5-406d-9420-d18fdbfe55f6
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column COLIGADA-FILIAL
		dataType: string
		lineageTag: c72cb7c8-15ed-4f9a-aace-43b0a0ec38d0
		summarizeBy: none
		sourceColumn: COLIGADA-FILIAL

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: string
		lineageTag: 9b4abc14-f0a8-4910-9562-f3ac7728d392
		summarizeBy: none
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	partition dAcessoUsuarios = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVlNc+rGEv0rKq9jlc3zLfvt7iAGPI7QEAlRN6SyGGCM5QiNow/qxtu3SL3fdf/YOz0CAzcB5FhVb8EURtQceqbPOd3tX365uL744eIGr6sb53IcjxjesiELesxhIxZyT+Cdx33ek4GQeKhWKlsod65TvTBZYj4/5snS6KLMdYqPzcqd5fja9SVtevHrD4cIzgZiIsYyFNiZDYXv/+z0uCN9MeEiBK4/4RG+s05KkyfKVelaF81grjt2AU4oA/xiOcKutFc/ZIEnuO8LZ8g8BOP0eRgSHB4+5iqbJzpNE/dR57lOcnUUziKcx3uIfcEC5oy5+GKD6snIiVgwlvT0uUoTlSm3UFlpjof2HdadXYA1Yb4I7u1Oo1BEnvABFIqBdAZyaI/uJU+KeYLdlmZ14uzslhbAxnF1U6+AiL79Rzp+LKbYMpiyAR1TN4yD/UDoJO9Zj5JillcIZ6XmT2phPqs0WWmK7C+QncsapDHmjywUAXeQg5HwJ8z50Y8H+Pg3lSeZdn9Lq+X70D7VK9DEQyzoomTYo4vqMR+nGMqIOV3Z79MlmXxBlzQzj49nQD5tQejNbccugJA8GnP8MeAiQu4Jx8NtjZEX/DAdljopkH7JNh/oqnSu5sqoLFmpdAf26fJ2lxMU2u2tXQDWZ1NOrB3HYVf49zhLe2U/s8Dh4HMQc9954FEcEdeGYEJ9b3+ozF0h9Q95fO2abJXMc1OYx5Lg6dhuLi1aY/CQ9RlA+4h8xJ2RQLTOiG9Jl6tHpVP3RW/4pl41dKWs8lmSPimzl6YHuBT+v++u6pX0hHUlctAJ2bc/a1g/9hhyE7+HR/u6gkdpNVeFa9JkTZiz5BgxOpc1RFNIEJKTmu1xo8t8fAUf0/O1SjUpGVZzKtJDXEouegEShEdAtC9SKuQ+sxJDzOdIpiGDwIyEx6TVFmK+BjteEmTQUe53muJYRkItA5hCLZuM/vahOIGwh5q8QjfTEpQ8eqLN4R5kxB3ei1kINI+N8amFeQb33LkqsW9TmO9Np8+6QjoPMYwsdMbws4DEH3lg3BJWln3QY4hmxLKuDAdIva3044mGZ1ZI9lInX9twF0ox/HpJuujJaMycPlhn3TmzkRj3Ebl1/PKvT56Tx0Kf7mRzCV/YRPCQqGT1A1+Yqzw1hfusi6qBMTfReaSTDGqNp/NKEYV7lJ8Hun4unzYqRMq+Ux0I2/FLaM4MFof7ZdJEQAeIEarKlbtOwPqTIFdX1+7VVceFfzSBw+ZfHEuPSAKSLgIIX93CqPyEyR8g3TSkvAeXklstCxiUJh6Pa7bPUboYN1OQmaosT1Px/4776ZT3D2JQZyKdIWiFEmDIxlE8lGPi0bIqSrU27gpmkR1LlQPrPy/XkB0odX2DPS4DK9aooFcqdxfaHJefg4hud/JAL0LrDfdw+IBPUWxAOkPY0r38zgL1Ur+i1ngzweMS8QaK1/UZUJ/DHEL5xgW8i+l06ShTjYYhN66q6FBPaNJ7AFkvtHVUXRX2YooVnht2mRVItYDdwgIXVQ7vbQcS4hfBY50B64Y4YPZWlNI96qKA27pFkq5bOtKNbjFKpF1PtNGv0y3Ru3AiCYMd8D0ZsxYfEkEKA7NdatsVoeJu6RwlQ+2EkyRvGaE4jKIa7dmgGHpBHVwUrYGFfABqUyn21kLslaB6CXKnC9PqvcVdQVpC9WAXDZLg1uDyaoYCcIYOKdHLlqCieCqcmglAlCGHVBLdIxlP6XlRvaKnMNVrS3j1zcmebTX3st+xN5ebBYG0A0VpQWnp7/vrSIIKAYVIvZovuryWNGQMpSngXkxWnioP3/UbBvB3j+6Sqmy60gH0lFFTsQt9Ca+HMbWZQHSZI94Lt7JGcoY2tE0pg9Pdc3SCm9asJ9AwRT/FgnwQj1eqfNJV4Ra/Vwn5XzugaLOFD8aHto/YsRBNdpKC+DlsoqXs+T5HiY5jEVgBrbPU3pcL5y2TrCUh7d3TzKcewTjRSEbC2t/iiYY9bvECzLbcr25x68o/Ej/FB+1tkfxetefs2ybAaso+mF5UKrfS2Sbcg6Tm4AuVTzhF5m66ta07fKUpTFvO99Hy751wND6Tu0Z6k5icGrtvf9IXaIgGSA0aZPOWQIUfoa/qsrGgXIHreuS0SVqgv8qT+bwlqYRYd61Whyx+oAOEIs9oQ5Wr6rlh1nfOpeKkLjLfWN1l0ymB6XVdYc7U62tLWBtlfJtJeyj6rBQ/wm1eaBAxy5uq8c1ZNk8FhUY99rafR0J6dtyewsMpPJ27yMR5Yj6v1UKZEmoJSclLXfxj3AHqBgE73aQk+NaN7XkuUTsnWeLOqqbHeQ7KRkeZaJsfNqAYra8hLkpFBUUuG6b8OazNfGfXivhyxOupO5qt3E3NS1MFOQslo2//dTaVusdg1h46V37QGdRjK1j3XGXl8XnA3+GeHzx+WMIOJ44NhrofRvzLFPnuX3bZB6zjbAfNbn/6nygfzc67fYTOrV22c64Ri+2k/YMYnduLhnOGj7H6YNRwdyb976nG2tZaaFRhLwT0VC3R7a80/OXd8nEqMhRxEEcAou4fk5MGqCG9+wsqWPO5KdCmZjrX86cGoAeDlFOg9cyY2Lz9Z6GdF1P92LDqqaF+/R8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COLIGADA = _t, CODFILIAL = _t, FILIAL = _t, NOME = _t, EMAIL = _t, #"COLIGADA-FILIAL" = _t, CODDEPARTAMENTO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"COLIGADA", type text}, {"CODFILIAL", type text}, {"FILIAL", type text}, {"NOME", type text}, {"EMAIL", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Exception

