table Medidas
	lineageTag: 170cedcf-a8b2-4ecf-a449-acfd70f565b4

	measure 'Valor HE' = SUM('Planilha NET- 27 – Acima de 10 Horas - Valor'[VALOR_HORAS_EXTRAS])
		lineageTag: 67bfedd3-b7e1-4e3e-a63e-97889d28a034

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtd faltas' = COUNTROWS('Planilha NET- 4 – Faltas')
		formatString: 0
		lineageTag: 5975bb6c-3498-478e-920d-464ebdb7c37a

	measure 'Qtd HE acima 10H' = COUNTROWS('Planilha NET- 27 – Acima de 10 Horas - Valor')
		formatString: 0
		lineageTag: cf515c32-2efb-4c47-abd4-94762f1c3345

	measure 'Saldo Positivo' = ```
			
			VAR MinutosPositivos = SUM('Planilha NET – 2 – Saldo de Banco de Horas – saldo_data'[MINUTOS_SALDO_POSITIVO])
			VAR Horas = TRUNC(MinutosPositivos / 60)
			VAR Minutos = MOD(MinutosPositivos, 60)
			RETURN
			    -- Retorna BLANK() se for vazio ou zero para ocultar linhas sem dados no filtro
			    IF(
			        ISBLANK(MinutosPositivos) || MinutosPositivos = 0, 
			        BLANK(), 
			        FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00")
			    )
			```
		lineageTag: 1596ab93-a5b6-4892-9a3e-17b81aeb88a8

	measure 'Saldo Negativo' = ```
			
			VAR MinutosNegativos = SUM('Planilha NET – 2 – Saldo de Banco de Horas – saldo_data'[MINUTOS_SALDO_NEGATIVO])
			VAR ValorAbsoluto = ABS(MinutosNegativos)
			VAR Horas = TRUNC(ValorAbsoluto / 60)
			VAR Minutos = MOD(ValorAbsoluto, 60)
			RETURN
			    -- Retorna BLANK() se for vazio ou zero para ocultar linhas sem dados no filtro
			    IF(
			        ISBLANK(MinutosNegativos) || MinutosNegativos = 0, 
			        BLANK(), 
			        "-" & FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00")
			    )
			```
		lineageTag: 0931e136-d8ae-4427-9df0-cc822f83a03c

	measure Qtd_Funcionarios_Saldo_Positivo =
			
			COUNTROWS(
			    FILTER(
			        VALUES('Planilha NET – 2 – Saldo de Banco de Horas – saldo_data'[CODFILIAL-CHAPA]),
			        CALCULATE(SUM('Planilha NET – 2 – Saldo de Banco de Horas – saldo_data'[MINUTOS_SALDO_POSITIVO])) > 0
			    )
			)
		formatString: 0
		lineageTag: 9062065b-6272-4c94-8ae5-d37e8a6c3a3b

	measure Qtd_Funcionarios_Saldo_Negativo =
			
			COUNTROWS(
			    FILTER(
			        VALUES('Planilha NET – 2 – Saldo de Banco de Horas – saldo_data'[CODFILIAL-CHAPA]),
			        CALCULATE(SUM('Planilha NET – 2 – Saldo de Banco de Horas – saldo_data'[MINUTOS_SALDO_NEGATIVO])) < 0
			    )
			)
		formatString: 0
		lineageTag: 5de009b8-83dd-4953-8577-d0b9181b9780

	measure 'R$ HE' = SUMX('Planilha NET 25 - Funcionários com batida','Planilha NET 25 - Funcionários com batida'[HE_TOTAL_VALOR])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 33722f3e-864f-4bea-b06b-be9d4822a4b8

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Filtro Slicer RLS' = ```
			
			VAR _UsuarioLogado = USERPRINCIPALNAME()
			
			-- 1. Verifica se o usuário logado está mapeado na tabela de restrições
			VAR _UsuarioEstaMapeado = 
			    NOT(ISBLANK(
			        CALCULATE(
			            COUNTROWS('dAcessoUsuarios'), 
			            ALL('dFilial'),
			            'dAcessoUsuarios'[EMAIL] = _UsuarioLogado
			        )
			    ))
			
			-- 2. Lista as filiais autorizadas para a Amanda
			VAR _FiliaisAutorizadas = 
			    CALCULATETABLE(
			        VALUES('dAcessoUsuarios'[COLIGADA-FILIAL]),
			        ALL('dFilial'),
			        'dAcessoUsuarios'[EMAIL] = _UsuarioLogado
			    )
			
			-- 3. Captura o ID da linha que a árvore do Slicer está renderizando
			VAR _FilialSendoDesenhada = SELECTEDVALUE('dFilial'[ID_FILIAL])
			
			RETURN
			    IF(
			        _UsuarioEstaMapeado = FALSE(),
			        1, -- Usuário Master: Vê todas as opções
			        
			        -- Para usuário restrito: Mostra o nó pai (BLANK) ou se a filial for a autorizada
			        IF(ISBLANK(_FilialSendoDesenhada) || _FilialSendoDesenhada IN _FiliaisAutorizadas, 1, 0)
			    )
			```
		formatString: 0
		lineageTag: 20da9c5f-d812-4499-9ff1-30a729a32d78

	measure 'Filtro Hierarquia RLS' = ```
			
			VAR _UsuarioLogado = USERPRINCIPALNAME()
			
			-- 1. Checa se o usuário logado está mapeado na tabela de restrições
			VAR _UsuarioEstaMapeado = 
			    NOT(ISBLANK(
			        CALCULATE(
			            COUNTROWS('dAcessoUsuarios'), 
			            ALL('dFilial'),
			            'dAcessoUsuarios'[EMAIL] = _UsuarioLogado
			        )
			    ))
			
			-- 2. Captura quantas filiais existem no total para a coligada que está no contexto
			VAR _TotalFiliaisDaColigada = CALCULATE(DISTINCTCOUNT('dFilial'[FILIAL]), ALLSELECTED('dFilial'[FILIAL]))
			
			-- 3. Verifica se o usuário selecionou uma quantidade menor de filiais do que o nó pai completo
			VAR _FilialEstaSelecionadaDiretamente = 
			    ISFILTERED('dFilial'[FILIAL]) && HASONEVALUE('dFilial'[FILIAL])
			
			RETURN
			    IF(
			        _UsuarioEstaMapeado = FALSE(),
			        1, -- Usuário Master: Vê tudo sempre livremente
			        
			        -- Para usuário restrito (Amanda):
			        IF(
			            _FilialEstaSelecionadaDiretamente = TRUE(),
			            1, -- Só retorna 1 se o nó folha (Filial) específico estiver ativamente filtrado individualmente
			            0  -- Se marcar o Pai inteiro (todas as filiais da coligada ativas) ou limpar, bloqueia
			        )
			    )
			```
		formatString: 0
		lineageTag: 4baf5fa0-e00b-4f70-b261-5edb9eb2be26

	column Column
		isHidden
		formatString: 0
		lineageTag: 620f7e22-301a-4327-8619-b6e9313191ec
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = fbaf4a9d0ac44d98a05f3a43a8a7d755

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

