table 'Planilha NET- 27 – Acima de 10 Horas - Valor'
	lineageTag: ce56e30c-6d95-4356-8022-69b6e76c8c50

	column CODCOLIGADA
		dataType: string
		lineageTag: c65138c9-ca54-426e-95d1-d0940f92dac8
		summarizeBy: none
		sourceColumn: CODCOLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: ce9ab5ec-4091-4e42-b24f-e178a0777a32
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column CHAPA
		dataType: string
		lineageTag: e42439db-9b61-4d0d-941c-08d0d8bda4ef
		summarizeBy: none
		sourceColumn: CHAPA

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: d2cce958-2a36-4330-905a-63c72f1a7725
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column CODSITUACAO
		dataType: string
		lineageTag: 77e42cdf-d128-48bb-b354-258b91b89c40
		summarizeBy: none
		sourceColumn: CODSITUACAO

		annotation SummarizationSetBy = Automatic

	column FUNCAO
		dataType: string
		lineageTag: d7d43e16-758e-4654-bca9-a1ddfac8d63c
		summarizeBy: none
		sourceColumn: FUNCAO

		annotation SummarizationSetBy = Automatic

	column NOME_SECAO
		dataType: string
		lineageTag: d0c2d3e1-9c42-4c51-89d0-41c57d6cc120
		summarizeBy: none
		sourceColumn: NOME_SECAO

		annotation SummarizationSetBy = Automatic

	column COD_JORNADA
		dataType: string
		lineageTag: ca848ac1-fe48-46b4-ab1a-6eae31ff26fb
		summarizeBy: none
		sourceColumn: COD_JORNADA

		annotation SummarizationSetBy = Automatic

	column DESC_JORNADA
		dataType: string
		lineageTag: 9f600fae-0556-40f2-891f-12dcd8b189ff
		summarizeBy: none
		sourceColumn: DESC_JORNADA

		annotation SummarizationSetBy = Automatic

	column DATAREFERENCIA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7c7265e4-28f0-42bc-b74f-10d254c15e3c
		summarizeBy: none
		sourceColumn: DATAREFERENCIA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DIA_DA_SEMANA
		dataType: string
		lineageTag: 734abc50-c505-4c95-8b0d-656e9af14dc5
		summarizeBy: none
		sourceColumn: DIA_DA_SEMANA

		annotation SummarizationSetBy = Automatic

	column ENT1
		dataType: string
		lineageTag: 0acf6103-9b7f-492a-857e-793fdd27910d
		summarizeBy: none
		sourceColumn: ENT1

		annotation SummarizationSetBy = Automatic

	column SAI1
		dataType: string
		lineageTag: 497f3500-d7f8-4f07-b409-b31ff581aeb9
		summarizeBy: none
		sourceColumn: SAI1

		annotation SummarizationSetBy = Automatic

	column ENT2
		dataType: string
		lineageTag: 7f6cf386-2a07-486f-bf28-5ebaedd77a50
		summarizeBy: none
		sourceColumn: ENT2

		annotation SummarizationSetBy = Automatic

	column SAI2
		dataType: string
		lineageTag: 34eff8c0-edc1-4c81-8072-f394a07d7198
		summarizeBy: none
		sourceColumn: SAI2

		annotation SummarizationSetBy = Automatic

	column ENT3
		dataType: string
		lineageTag: 7152e66e-29b5-480e-8883-06b05df6c923
		summarizeBy: none
		sourceColumn: ENT3

		annotation SummarizationSetBy = Automatic

	column SAI3
		dataType: string
		lineageTag: 9bac2b2e-2a35-45c6-a9c0-abb4ad51b6c1
		summarizeBy: none
		sourceColumn: SAI3

		annotation SummarizationSetBy = Automatic

	column ENT4
		dataType: string
		lineageTag: 9159c577-c6bf-4f1e-aa86-5d955fe896c3
		summarizeBy: none
		sourceColumn: ENT4

		annotation SummarizationSetBy = Automatic

	column SAI4
		dataType: string
		lineageTag: 4966beb9-9af6-49fc-a027-fec0e34d0a14
		summarizeBy: none
		sourceColumn: SAI4

		annotation SummarizationSetBy = Automatic

	column HORAS_BASE
		dataType: string
		lineageTag: 81f3fb51-2eba-4e21-b8e1-973c03ddd652
		summarizeBy: none
		sourceColumn: HORAS_BASE

		annotation SummarizationSetBy = Automatic

	column HORAS_TRAB
		dataType: dateTime
		formatString: Long Time
		lineageTag: 25351790-75f8-431c-9a50-d933f80701af
		summarizeBy: none
		sourceColumn: HORAS_TRAB

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column HORAS_EXTRAS
		dataType: dateTime
		formatString: Long Time
		lineageTag: fdc1ce4d-1330-401e-9ff6-77dc78864d7b
		summarizeBy: none
		sourceColumn: HORAS_EXTRAS

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column VALOR_HORAS_EXTRAS
		dataType: double
		lineageTag: 41d62f5e-0ac6-48dc-9627-d75fa68c392d
		summarizeBy: sum
		sourceColumn: VALOR_HORAS_EXTRAS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STATUS
		dataType: string
		lineageTag: 344b35db-2142-4863-8563-e5bf1b435c13
		summarizeBy: none
		sourceColumn: STATUS

		annotation SummarizationSetBy = Automatic

	column CODFILIAL-CHAPA
		dataType: string
		lineageTag: 435fe0ff-958e-4b23-95fd-fe9cdb0ff5ca
		summarizeBy: none
		sourceColumn: CODFILIAL-CHAPA

		annotation SummarizationSetBy = Automatic

	column DEPARTAMENTO
		dataType: string
		lineageTag: e081ccb8-c92e-44a1-8daa-9e6ea7787158
		summarizeBy: none
		sourceColumn: DEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column SETOR
		dataType: string
		lineageTag: 4e13cef4-f075-4381-a6b7-cbc20b35f94e
		summarizeBy: none
		sourceColumn: SETOR

		annotation SummarizationSetBy = Automatic

	column SECAO
		dataType: string
		lineageTag: 556a09f7-313d-4732-b3b5-51cdb9c75c0d
		summarizeBy: none
		sourceColumn: SECAO

		annotation SummarizationSetBy = Automatic

	column COLIGADA_FILIAL
		dataType: string
		lineageTag: 21b24ac5-cf12-4af2-8ff4-4b269ae2abc9
		summarizeBy: none
		sourceColumn: COLIGADA_FILIAL

		annotation SummarizationSetBy = Automatic

	column COLIGADA
		dataType: string
		lineageTag: bb8fa853-e4f8-4b42-b725-9353b76fa951
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: 1cc1c2cd-a73f-41c2-b788-ed60527d648b
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	partition 'Planilha NET- 27 – Acima de 10 Horas - Valor' = m
		mode: import
		source = ```
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="SELECT Q.CODCOLIGADA,#(lf)       Q.CODFILIAL,#(lf)       Q.CHAPA,#(lf)       Q.NOME,#(lf)       Q.CODSITUACAO,#(lf)       Q.FUNCAO,#(lf)       Q.NOME_SECAO,#(lf)       Q.COD_JORNADA,#(lf)       Q.DESC_JORNADA,#(lf)       Q.DATAREFERENCIA,#(lf)       Q.DIA_DA_SEMANA,#(lf)       -- Aplicação das máscaras de texto no bloco final garantindo compatibilidade com a tabela 25#(lf)       CASE WHEN Q.QUANT_BATIDAS >= 1 THEN LPAD(TRUNC(Q.E1/60), 2, '0') || ':' || LPAD(MOD(Q.E1, 60), 2, '0') END AS ENT1,#(lf)       CASE WHEN Q.QUANT_BATIDAS >= 2 THEN LPAD(TRUNC(Q.S1/60), 2, '0') || ':' || LPAD(MOD(Q.S1, 60), 2, '0') END AS SAI1,#(lf)       CASE WHEN Q.QUANT_BATIDAS >= 3 THEN LPAD(TRUNC(Q.E2/60), 2, '0') || ':' || LPAD(MOD(Q.E2, 60), 2, '0') END AS ENT2,#(lf)       CASE WHEN Q.QUANT_BATIDAS >= 4 THEN LPAD(TRUNC(Q.S2/60), 2, '0') || ':' || LPAD(MOD(Q.S2, 60), 2, '0') END AS SAI2,#(lf)       CASE WHEN Q.QUANT_BATIDAS >= 5 THEN LPAD(TRUNC(Q.E3/60), 2, '0') || ':' || LPAD(MOD(Q.E3, 60), 2, '0') END AS ENT3,#(lf)       CASE WHEN Q.QUANT_BATIDAS >= 6 THEN LPAD(TRUNC(Q.S3/60), 2, '0') || ':' || LPAD(MOD(Q.S3, 60), 2, '0') END AS SAI3,#(lf)       CASE WHEN Q.QUANT_BATIDAS >= 7 THEN LPAD(TRUNC(Q.E4/60), 2, '0') || ':' || LPAD(MOD(Q.E4, 60), 2, '0') END AS ENT4,#(lf)       CASE WHEN Q.QUANT_BATIDAS >= 8 THEN LPAD(TRUNC(Q.S4/60), 2, '0') || ':' || LPAD(MOD(Q.S4, 60), 2, '0') END AS SAI4,#(lf)       LPAD(TRUNC(Q.HORAS_BASE/60), 2, '0') || ':' || LPAD(MOD(Q.HORAS_BASE, 60), 2, '0') AS HORAS_BASE,#(lf)       LPAD(TRUNC(Q.HORAS_TRAB/60), 2, '0') || ':' || LPAD(MOD(Q.HORAS_TRAB, 60), 2, '0') AS HORAS_TRAB,#(lf)       LPAD(TRUNC(Q.HORAS_EXTRAS/60), 2, '0') || ':' || LPAD(MOD(Q.HORAS_EXTRAS, 60), 2, '0') AS HORAS_EXTRAS,#(lf)       Q.VALOR_HORAS_EXTRAS,#(lf)       Q.STATUS#(lf)FROM (#(lf)    SELECT T.CODCOLIGADA, T.CODFILIAL, T.CHAPA, T.NOME, T.CODSITUACAO, T.FUNCAO, T.NOME_SECAO, T.DATAREFERENCIA, T.HORAS_BASE, T.HORAS_TRAB, T.SALARIO_HORA, T.QUANT_BATIDAS,#(lf)           T.E1, T.S1, T.E2, T.S2, T.E3, T.S3, T.E4, T.S4,#(lf)           CASE WHEN T.HORAS_TRAB > T.HORAS_BASE THEN (T.HORAS_TRAB - T.HORAS_BASE) ELSE 0 END AS HORAS_EXTRAS,#(lf)           CASE WHEN T.HORAS_TRAB > T.HORAS_BASE THEN ((((T.HORAS_TRAB - T.HORAS_BASE) / 60) * T.SALARIO_HORA) * 1.50) ELSE 0 END AS VALOR_HORAS_EXTRAS,#(lf)           CASE TO_CHAR(T.DATAREFERENCIA, 'D')#(lf)              WHEN '1' THEN 'DOM' WHEN '2' THEN 'SEG' WHEN '3' THEN 'TER' WHEN '4' THEN 'QUA' WHEN '5' THEN 'QUI' WHEN '6' THEN 'SEX' ELSE 'SAB'#(lf)           END AS DIA_DA_SEMANA,#(lf)           #(lf)           -- Nova lógica dinâmica de STATUS baseada na carga horária e tolerância de 10 minutos#(lf)           CASE#(lf)              WHEN T.HORAS_BASE >= 600 THEN#(lf)                 CASE #(lf)                    WHEN T.HORAS_TRAB > (T.HORAS_BASE + 10) AND T.QUANT_BATIDAS > 2 THEN 'Trablhou mais de 10:00'#(lf)                    WHEN T.HORAS_TRAB > (T.HORAS_BASE + 10) AND T.QUANT_BATIDAS = 2 THEN 'Trablhou mais de 10:00 e foi embora'#(lf)                    ELSE 'OK'#(lf)                 END#(lf)              ELSE#(lf)                 CASE #(lf)                    WHEN T.HORAS_TRAB > 610 AND T.QUANT_BATIDAS > 2 THEN 'Trablhou mais de 10:00'#(lf)                    WHEN T.HORAS_TRAB > 610 AND T.QUANT_BATIDAS = 2 THEN 'Trablhou mais de 10:00 e foi embora'#(lf)                    ELSE 'OK'#(lf)                 END#(lf)           END AS STATUS,#(lf)           #(lf)           (SELECT J.CODHORARIO #(lf)            FROM AJORNADAFUN@RM J #(lf)            WHERE J.CODCOLIGADA = T.CODCOLIGADA #(lf)              AND J.CHAPA = T.CHAPA #(lf)              AND J.DATAMUDANCA = (SELECT MAX(K.DATAMUDANCA) FROM AJORNADAFUN@RM K WHERE K.CODCOLIGADA = J.CODCOLIGADA AND K.CHAPA = J.CHAPA AND K.DATAMUDANCA <= T.DATAREFERENCIA)) AS COD_JORNADA,#(lf)           (SELECT M.DESCRICAO #(lf)            FROM AJORNADAFUN@RM J#(lf)            JOIN AHORARIOJORNADA@RM M ON J.CODCOLIGADA = M.CODCOLIGADA AND J.CODHORARIO = M.CODHORARIO#(lf)            WHERE J.CODCOLIGADA = T.CODCOLIGADA #(lf)              AND J.CHAPA = T.CHAPA #(lf)              AND J.DATAMUDANCA = (SELECT MAX(K.DATAMUDANCA) FROM AJORNADAFUN@RM K WHERE K.CODCOLIGADA = J.CODCOLIGADA AND K.CHAPA = J.CHAPA AND K.DATAMUDANCA <= T.DATAREFERENCIA)) AS DESC_JORNADA#(lf)    FROM (#(lf)        SELECT W.CODCOLIGADA, W.CODFILIAL, W.CHAPA, W.NOME, W.CODSITUACAO, W.FUNCAO, W.NOME_SECAO, W.DATAREFERENCIA, W.SALARIO_HORA, W.QUANT_BATIDAS,#(lf)               W.E1, W.S1, W.E2, W.S2, W.E3, W.S3, W.E4, W.S4,#(lf)               H.HTRAB AS HORAS_TRAB,#(lf)               H.BASE AS HORAS_BASE#(lf)        FROM (#(lf)            SELECT X.CODCOLIGADA, X.CODFILIAL, X.CHAPA, X.NOME, X.CODSITUACAO, X.FUNCAO, X.NOME_SECAO, X.DATAREFERENCIA, X.SALARIO_HORA,#(lf)                   COUNT(X.QTDE_BATIDA) AS QUANT_BATIDAS,#(lf)                   MAX(CASE WHEN X.SEQUENCIA = 1 THEN X.BATIDA END) AS E1,#(lf)                   MAX(CASE WHEN X.SEQUENCIA = 2 THEN X.BATIDA END) AS S1,#(lf)                   MAX(CASE WHEN X.SEQUENCIA = 3 THEN X.BATIDA END) AS E2,#(lf)                   MAX(CASE WHEN X.SEQUENCIA = 4 THEN X.BATIDA END) AS S2,#(lf)                   MAX(CASE WHEN X.SEQUENCIA = 5 THEN X.BATIDA END) AS E3,#(lf)                   MAX(CASE WHEN X.SEQUENCIA = 6 THEN X.BATIDA END) AS S3,#(lf)                   MAX(CASE WHEN X.SEQUENCIA = 7 THEN X.BATIDA END) AS E4,#(lf)                   MAX(CASE WHEN X.SEQUENCIA = 8 THEN X.BATIDA END) AS S4#(lf)            FROM (#(lf)                SELECT ROW_NUMBER() OVER(PARTITION BY A.CHAPA, NVL(A.DATAREFERENCIA, A.DATA) ORDER BY A.DATA, A.BATIDA) SEQUENCIA,#(lf)                       A.CODCOLIGADA, B.CODFILIAL, A.CHAPA, B.NOME, B.CODSITUACAO, D.DESCRICAO AS NOME_SECAO, C.NOME AS FUNCAO,#(lf)                       (B.SALARIO / (B.JORNADAMENSAL / 60)) AS SALARIO_HORA,#(lf)                       NVL(A.DATAREFERENCIA, A.DATA) AS DATAREFERENCIA,#(lf)                       A.BATIDA, 1 AS QTDE_BATIDA#(lf)                FROM ABATFUN@RM A#(lf)                JOIN PFUNC@RM B ON A.CODCOLIGADA = B.CODCOLIGADA AND A.CHAPA = B.CHAPA#(lf)                JOIN PFUNCAO@RM C ON B.CODCOLIGADA = C.CODCOLIGADA AND B.CODFUNCAO = C.CODIGO#(lf)                JOIN PSECAO@RM D ON B.CODCOLIGADA = D.CODCOLIGADA AND B.CODSECAO = D.CODIGO#(lf)                WHERE B.CODCOLIGADA BETWEEN 0 AND 999#(lf)                  AND B.CODFILIAL BETWEEN 0 AND 999#(lf)                  AND (A.DATA >= TRUNC(SYSDATE) - 60 OR A.DATAREFERENCIA >= TRUNC(SYSDATE) - 60)#(lf)            ) X#(lf)            GROUP BY X.CODCOLIGADA, X.CODFILIAL, X.CHAPA, X.NOME, X.CODSITUACAO, X.FUNCAO, X.NOME_SECAO, X.DATAREFERENCIA, X.SALARIO_HORA#(lf)        ) W#(lf)        JOIN AAFHTFUN@RM H ON H.CODCOLIGADA = W.CODCOLIGADA AND H.CHAPA = W.CHAPA AND H.DATA = W.DATAREFERENCIA#(lf)        -- Ajuste no filtro Where para permitir a captura dinâmica de jornadas de 11h (660 min) ou superiores#(lf)        WHERE (H.BASE >= 600 AND H.HTRAB > (H.BASE + 10)) #(lf)           OR (H.BASE < 600 AND H.HTRAB > 610)#(lf)    ) T#(lf)) Q#(lf)WHERE COD_JORNADA <> '0009'#(lf)ORDER BY CODCOLIGADA, CODFILIAL, CHAPA, DATAREFERENCIA"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"CODCOLIGADA", type text}, {"CODFILIAL", type text}, {"DATAREFERENCIA", type date}, {"HORAS_TRAB", type time}, {"HORAS_EXTRAS", type time}}),
				    
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Tipo Alterado", "CODFILIAL-CHAPA", each Text.Combine({[CODFILIAL], [CHAPA]}, "-"), type text),
				    #"Valor Substituído" = Table.ReplaceValue(#"Coluna Mesclada Inserida","Trablhou mais de 10:00 e foi embora","Trablhou mais de 10:00",Replacer.ReplaceText,{"STATUS"}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Valor Substituído", {"NOME_SECAO"}, FPBI_DEPARTAMENTO, {"DESCRICAO"}, "FPBI_DEPARTAMENTO", JoinKind.LeftOuter),
				    #"FPBI_DEPARTAMENTO Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "FPBI_DEPARTAMENTO", {"DEPARTAMENTO", "SETOR", "SECAO"}, {"DEPARTAMENTO", "SETOR", "SECAO"}),
				    #"Coluna Mesclada Inserida1" = Table.AddColumn(#"FPBI_DEPARTAMENTO Expandido", "COLIGADA_FILIAL", each Text.Combine({[CODCOLIGADA], [CODFILIAL]}, "-"), type text),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Coluna Mesclada Inserida1", {"COLIGADA_FILIAL"}, dFilial, {"ID_FILIAL"}, "dFilial", JoinKind.LeftOuter),
				    #"dFilial Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "dFilial", {"COLIGADA", "FILIAL"}, {"COLIGADA", "FILIAL"})
				in
				    #"dFilial Expandido"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

