table 'Planilha NET 24 - Acima de 6 horas sem intervalo'
	lineageTag: 8c906ac8-aa8b-4fd4-a4e5-deecf772ee71

	column CODCOLIGADA
		dataType: string
		lineageTag: 03983d41-cb60-4c72-b2b9-f44e6ad3befc
		summarizeBy: none
		sourceColumn: CODCOLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: b088ee98-92c2-47e1-8f42-92217d8bc8e4
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column CHAPA
		dataType: string
		lineageTag: d1236cf2-94e7-4258-aeb9-207a0bb8040a
		summarizeBy: none
		sourceColumn: CHAPA

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 25625d87-a0a7-4200-9454-f6b822bc9768
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column CODSITUACAO
		dataType: string
		lineageTag: b1fc5d89-330a-4c3e-8e1a-e28ea240d9e3
		summarizeBy: none
		sourceColumn: CODSITUACAO

		annotation SummarizationSetBy = Automatic

	column FUNCAO
		dataType: string
		lineageTag: 0d558f0a-ad52-427e-9278-fec52baf8c75
		summarizeBy: none
		sourceColumn: FUNCAO

		annotation SummarizationSetBy = Automatic

	column NOME_SECAO
		dataType: string
		lineageTag: 37d6fff8-58ea-48c6-9260-7d580ee106ea
		summarizeBy: none
		sourceColumn: NOME_SECAO

		annotation SummarizationSetBy = Automatic

	column DATAREFERENCIA
		dataType: dateTime
		formatString: Long Date
		lineageTag: a3d83b1e-1331-43ac-83cf-fbeff36aab98
		summarizeBy: none
		sourceColumn: DATAREFERENCIA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DIA_DA_SEMANA
		dataType: string
		lineageTag: 18b3bc83-afc1-4057-a6e8-ae3c04c8045e
		summarizeBy: none
		sourceColumn: DIA_DA_SEMANA

		annotation SummarizationSetBy = Automatic

	column ENT1
		dataType: string
		lineageTag: 8654bb71-c750-42d9-8cff-7378d6bd6e8e
		summarizeBy: none
		sourceColumn: ENT1

		annotation SummarizationSetBy = Automatic

	column SAI1
		dataType: string
		lineageTag: 2b72a26e-6749-4de2-839b-e40f53f68684
		summarizeBy: none
		sourceColumn: SAI1

		annotation SummarizationSetBy = Automatic

	column ENT2
		dataType: string
		lineageTag: 5113d105-3545-4ef3-a2e1-818a877c63f8
		summarizeBy: none
		sourceColumn: ENT2

		annotation SummarizationSetBy = Automatic

	column SAI2
		dataType: string
		lineageTag: 85742138-a1dc-41da-9b3e-b69b90409811
		summarizeBy: none
		sourceColumn: SAI2

		annotation SummarizationSetBy = Automatic

	column ENT3
		dataType: string
		lineageTag: 3a911013-2e3e-4566-b837-a108f9b989a2
		summarizeBy: none
		sourceColumn: ENT3

		annotation SummarizationSetBy = Automatic

	column SAI3
		dataType: string
		lineageTag: 86f609ee-41d7-4844-bc93-79b081ac8869
		summarizeBy: none
		sourceColumn: SAI3

		annotation SummarizationSetBy = Automatic

	column HORAS_TRAB
		dataType: dateTime
		formatString: Long Time
		lineageTag: 0eea3207-3b1f-4203-9327-0818b1bf4ee3
		summarizeBy: none
		sourceColumn: HORAS_TRAB

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column HTRAB06
		dataType: dateTime
		formatString: Long Time
		lineageTag: 93e039f2-973c-43ef-801b-832f72725aa2
		summarizeBy: none
		sourceColumn: HTRAB06

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column STATUS
		dataType: string
		lineageTag: 31e2bf27-40d2-47da-bd34-46df0b6d0f66
		summarizeBy: none
		sourceColumn: STATUS

		annotation SummarizationSetBy = Automatic

	column CODFILIAL-CHAPA
		dataType: string
		lineageTag: d73912b7-9ef2-4dd4-9f84-eb852ce9596d
		summarizeBy: none
		sourceColumn: CODFILIAL-CHAPA

		annotation SummarizationSetBy = Automatic

	column DEPARTAMENTO
		dataType: string
		lineageTag: dbbe4304-6035-415a-b6fe-b5e6d7d1aa0a
		summarizeBy: none
		sourceColumn: DEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column SETOR
		dataType: string
		lineageTag: 22f37889-a753-443d-a536-956258b7753b
		summarizeBy: none
		sourceColumn: SETOR

		annotation SummarizationSetBy = Automatic

	column SECAO
		dataType: string
		lineageTag: 1fcebb07-691f-4cd7-8d1b-4284652a2bbf
		summarizeBy: none
		sourceColumn: SECAO

		annotation SummarizationSetBy = Automatic

	column COLIGADA_FILIAL
		dataType: string
		lineageTag: c65ff6de-9242-4965-aa5a-849157bd43cd
		summarizeBy: none
		sourceColumn: COLIGADA_FILIAL

		annotation SummarizationSetBy = Automatic

	column COLIGADA
		dataType: string
		lineageTag: 2d7b9505-c85e-4299-ab25-9fee3c0d1c70
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: 412ad340-aec0-4bee-96a1-1387da70878d
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	partition 'Planilha NET 24 - Acima de 6 horas sem intervalo' = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("RM", [HierarchicalNavigation=true, Query="SELECT CODCOLIGADA,#(lf)       CODFILIAL,#(lf)       CHAPA,#(lf)       NOME,#(lf)       CODSITUACAO,#(lf)       FUNCAO,#(lf)       NOME_SECAO,#(lf)       DATAREFERENCIA,#(lf)       DIA_DA_SEMANA,#(lf)       ENT1,#(lf)       SAI1,#(lf)       ENT2,#(lf)       SAI2,#(lf)       ENT3,#(lf)       SAI3,#(lf)       HORAS_TRAB,#(lf)       HTRAB06,#(lf)       STATUS#(lf)FROM (#(lf)    SELECT CODCOLIGADA,#(lf)           CODFILIAL,#(lf)           CHAPA,#(lf)           NOME,#(lf)           CODSITUACAO,#(lf)           FUNCAO,#(lf)           NOME_SECAO,#(lf)           DATAREFERENCIA,#(lf)           CASE#(lf)              WHEN TO_CHAR(DATAREFERENCIA, 'D') = '1' THEN 'DOM'#(lf)              WHEN TO_CHAR(DATAREFERENCIA, 'D') = '2' THEN 'SEG'#(lf)              WHEN TO_CHAR(DATAREFERENCIA, 'D') = '3' THEN 'TER'#(lf)              WHEN TO_CHAR(DATAREFERENCIA, 'D') = '4' THEN 'QUA'#(lf)              WHEN TO_CHAR(DATAREFERENCIA, 'D') = '5' THEN 'QUI'#(lf)              WHEN TO_CHAR(DATAREFERENCIA, 'D') = '6' THEN 'SEX'#(lf)           ELSE#(lf)              'SAB'#(lf)           END AS DIA_DA_SEMANA,#(lf)           ENT1,#(lf)           SAI1,#(lf)           ENT2,#(lf)           SAI2,#(lf)           ENT3,#(lf)           SAI3,#(lf)           -- Conversão simplificada de HORAS_TRAB (Minutos para HH:MM)#(lf)           LPAD(TRUNC(HORAS_TRAB / 60), 2, '0') || ':' || LPAD(MOD(HORAS_TRAB, 60), 2, '0') AS HORAS_TRAB,#(lf)           LPAD(TRUNC(HTRAB06 / 60), 2, '0') || ':' || LPAD(MOD(HTRAB06, 60), 2, '0') AS HTRAB06,#(lf)           STATUS#(lf)    FROM (#(lf)        SELECT CODCOLIGADA,#(lf)               CODFILIAL,#(lf)               CHAPA,#(lf)               NOME,#(lf)               CODSITUACAO,#(lf)               FUNCAO,#(lf)               NOME_SECAO,#(lf)               DATAREFERENCIA,#(lf)               -- Conversão simplificada de Batidas usando LPAD (Minutos para HH:MM)#(lf)               CASE WHEN QUANT_BATIDAS BETWEEN 1 AND 6 THEN LPAD(TRUNC(ENT1 / 60), 2, '0') || ':' || LPAD(MOD(ENT1, 60), 2, '0') END AS ENT1,#(lf)               CASE WHEN QUANT_BATIDAS BETWEEN 2 AND 6 THEN LPAD(TRUNC(SAI1 / 60), 2, '0') || ':' || LPAD(MOD(SAI1, 60), 2, '0') END AS SAI1,#(lf)               CASE WHEN QUANT_BATIDAS BETWEEN 3 AND 6 THEN LPAD(TRUNC(ENT2 / 60), 2, '0') || ':' || LPAD(MOD(ENT2, 60), 2, '0') END AS ENT2,#(lf)               CASE WHEN QUANT_BATIDAS BETWEEN 4 AND 6 THEN LPAD(TRUNC(SAI2 / 60), 2, '0') || ':' || LPAD(MOD(SAI2, 60), 2, '0') END AS SAI2,#(lf)               CASE WHEN QUANT_BATIDAS BETWEEN 5 AND 6 THEN LPAD(TRUNC(ENT3 / 60), 2, '0') || ':' || LPAD(MOD(ENT3, 60), 2, '0') END AS ENT3,#(lf)               CASE WHEN QUANT_BATIDAS = 6             THEN LPAD(TRUNC(SAI3 / 60), 2, '0') || ':' || LPAD(MOD(SAI3, 60), 2, '0') END AS SAI3,#(lf)               HORAS_TRAB,#(lf)               QUANT_BATIDAS,#(lf)               CASE#(lf)                  WHEN HORAS_TRAB > 360 AND QUANT_BATIDAS > 2 AND CASE WHEN SAI1 > ENT1 THEN SAI1 - ENT1 ELSE 1440 + SAI1 - ENT1 END > 360 THEN 'Trabalhou mais de 6:00'#(lf)                  WHEN HORAS_TRAB > 360 AND QUANT_BATIDAS = 2 THEN 'Trabalhou mais de 6:00'#(lf)               ELSE#(lf)                  'OK'#(lf)               END AS STATUS,#(lf)               CASE#(lf)                  WHEN HORAS_TRAB > 360 AND QUANT_BATIDAS > 2 THEN CASE WHEN SAI1 > ENT1 THEN SAI1 - ENT1 ELSE 1440 + SAI1 - ENT1 END#(lf)                  WHEN HORAS_TRAB > 360 AND QUANT_BATIDAS = 2 THEN CASE WHEN SAI1 > ENT1 THEN SAI1 - ENT1 ELSE 1440 + SAI1 - ENT1 END#(lf)               ELSE#(lf)                  0#(lf)               END AS HTRAB06#(lf)        FROM (#(lf)            SELECT CODCOLIGADA,#(lf)                   CODFILIAL,#(lf)                   CHAPA,#(lf)                   NOME,#(lf)                   CODSITUACAO,#(lf)                   FUNCAO,#(lf)                   NOME_SECAO,#(lf)                   DATAREFERENCIA,#(lf)                   SUM(CASE WHEN SEQUENCIA = 1 THEN BATIDA ELSE 0 END) AS ENT1,#(lf)                   SUM(CASE WHEN SEQUENCIA = 2 THEN BATIDA ELSE 0 END) AS SAI1,#(lf)                   SUM(CASE WHEN SEQUENCIA = 3 THEN BATIDA ELSE 0 END) AS ENT2,#(lf)                   SUM(CASE WHEN SEQUENCIA = 4 THEN BATIDA ELSE 0 END) AS SAI2,#(lf)                   SUM(CASE WHEN SEQUENCIA = 5 THEN BATIDA ELSE 0 END) AS ENT3,#(lf)                   SUM(CASE WHEN SEQUENCIA = 6 THEN BATIDA ELSE 0 END) AS SAI3,#(lf)                   COUNT(QTDE_BATIDA) AS QUANT_BATIDAS,#(lf)                   (SELECT H.HTRAB#(lf)                    FROM AAFHTFUN H#(lf)                    WHERE H.CODCOLIGADA = X.CODCOLIGADA#(lf)                      AND H.CHAPA       = X.CHAPA#(lf)                      AND H.DATA        = X.DATAREFERENCIA) AS HORAS_TRAB#(lf)            FROM (#(lf)                SELECT ROW_NUMBER() OVER(PARTITION BY A.CODCOLIGADA, B.CODFILIAL, A.CHAPA, CASE WHEN A.DATAREFERENCIA IS NOT NULL THEN A.DATAREFERENCIA ELSE A.DATA END ORDER BY A.CHAPA, CASE WHEN A.DATAREFERENCIA IS NOT NULL THEN A.DATAREFERENCIA ELSE A.DATA END, A.DATA, A.BATIDA) SEQUENCIA,#(lf)                       A.CODCOLIGADA,#(lf)                       B.CODFILIAL,#(lf)                       A.CHAPA,#(lf)                       B.CODHORARIO,#(lf)                       B.NOME,#(lf)                       B.CODSITUACAO,#(lf)                       D.DESCRICAO AS NOME_SECAO,#(lf)                       C.NOME AS FUNCAO,#(lf)                       A.DATA,#(lf)                       CASE WHEN A.DATAREFERENCIA IS NOT NULL THEN A.DATAREFERENCIA ELSE A.DATA END AS DATAREFERENCIA,#(lf)                       (SELECT G.DESCRICAO#(lf)                        FROM PFHSTHOR E, AHORARIO G#(lf)                        WHERE E.CODCOLIGADA = A.CODCOLIGADA#(lf)                          AND E.CHAPA       = A.CHAPA#(lf)                          AND E.CODCOLIGADA = G.CODCOLIGADA#(lf)                          AND E.CODHORARIO  = G.CODIGO#(lf)                          AND E.DTMUDANCA   = (SELECT MAX(F.DTMUDANCA)#(lf)                                               FROM PFHSTHOR F#(lf)                                               WHERE F.CODCOLIGADA = A.CODCOLIGADA#(lf)                                                 AND F.CHAPA       = A.CHAPA#(lf)                                                 AND F.DTMUDANCA  <= CASE WHEN A.DATAREFERENCIA IS NOT NULL THEN A.DATAREFERENCIA ELSE A.DATA END )) AS HORARIO_BASE,#(lf)                       A.BATIDA,#(lf)                       1 AS QTDE_BATIDA#(lf)                FROM ABATFUN A, PFUNC B, PFUNCAO C, PSECAO D#(lf)                WHERE A.CODCOLIGADA   = B.CODCOLIGADA#(lf)                  AND A.CHAPA         = B.CHAPA#(lf)                  AND B.CODCOLIGADA   = C.CODCOLIGADA#(lf)                  AND B.CODFUNCAO     = C.CODIGO#(lf)                  AND B.CODCOLIGADA   = D.CODCOLIGADA#(lf)                  AND B.CODSECAO      = D.CODIGO#(lf)                  -- Filtro Dinâmico: Traz apenas os registros onde a Data ou Data de Referência estejam nos últimos 60 dias#(lf)                  AND (#(lf)                       A.DATA >= TRUNC(SYSDATE) - 60 #(lf)                       OR A.DATAREFERENCIA >= TRUNC(SYSDATE) - 60#(lf)                      )#(lf)            ) X#(lf)            GROUP BY CODCOLIGADA, CODFILIAL, CHAPA, NOME, CODSITUACAO, FUNCAO, NOME_SECAO, DATAREFERENCIA, HORARIO_BASE#(lf)        ) W#(lf)    ) T#(lf)) Q#(lf)WHERE STATUS <> 'OK'#(lf)ORDER BY CODCOLIGADA, CODFILIAL, CHAPA, DATAREFERENCIA"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"CODCOLIGADA", type text}, {"CODFILIAL", type text}, {"CHAPA", type text}, {"DATAREFERENCIA", type date}, {"HORAS_TRAB", type time}, {"HTRAB06", type time}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Tipo Alterado", "CODFILIAL-CHAPA", each Text.Combine({[CODFILIAL], [CHAPA]}, "-"), type text),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Coluna Mesclada Inserida", {"NOME_SECAO"}, FPBI_DEPARTAMENTO, {"DESCRICAO"}, "FPBI_DEPARTAMENTO", JoinKind.LeftOuter),
				    #"Valor Substituído" = Table.ReplaceValue(#"Consultas Mescladas","Trablhou mais de 10:00 e foi embora","Trablhou mais de 10:00",Replacer.ReplaceText,{"STATUS"}),
				    #"FPBI_DEPARTAMENTO Expandido" = Table.ExpandTableColumn(#"Valor Substituído", "FPBI_DEPARTAMENTO", {"DEPARTAMENTO", "SETOR", "SECAO"}, {"DEPARTAMENTO", "SETOR", "SECAO"}),
				    #"Coluna Mesclada Inserida1" = Table.AddColumn(#"FPBI_DEPARTAMENTO Expandido", "COLIGADA_FILIAL", each Text.Combine({[CODCOLIGADA], [CODFILIAL]}, "-"), type text),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Coluna Mesclada Inserida1", {"COLIGADA_FILIAL"}, dFilial, {"ID_FILIAL"}, "dFilial", JoinKind.LeftOuter),
				    #"dFilial Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "dFilial", {"COLIGADA", "FILIAL"}, {"COLIGADA", "FILIAL"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"dFilial Expandido", each ([STATUS] <> "OK"))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

