table 'Planilha NET 18 - Hora extra dia'
	lineageTag: bbdde433-ebda-4a69-9e83-9f8b97fd04ac

	column CODCOLIGADA
		dataType: string
		lineageTag: 5d45e497-c721-4899-b219-241346f98dcd
		summarizeBy: none
		sourceColumn: CODCOLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 4bb97393-218c-4a8f-8587-6007c2c30a97
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column CODSECAO
		dataType: string
		lineageTag: 489733a3-b547-4f65-9024-6ff303bee72d
		summarizeBy: none
		sourceColumn: CODSECAO

		annotation SummarizationSetBy = Automatic

	column SECAO
		dataType: string
		lineageTag: c5427308-98bd-4ccf-8055-c8554176ac86
		summarizeBy: none
		sourceColumn: SECAO

		annotation SummarizationSetBy = Automatic

	column CHAPA
		dataType: string
		lineageTag: 9746ee4d-51dd-4d4a-8327-eeb9eb1c496b
		summarizeBy: none
		sourceColumn: CHAPA

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: f5d417bc-fdb5-4e96-b435-65a7244979ad
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2f7aa7d5-de1c-4145-9e88-62cf8522f937
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HE_50
		dataType: dateTime
		formatString: Long Time
		lineageTag: 3eed589f-aada-4420-ab0c-25746975d8ba
		summarizeBy: none
		sourceColumn: HE_50

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column HE_50_VALOR
		dataType: double
		lineageTag: e78f3dc1-8427-4f19-8245-caf68eb643ed
		summarizeBy: sum
		sourceColumn: HE_50_VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HE_100
		dataType: dateTime
		formatString: Long Time
		lineageTag: f0ebf180-f912-4f31-8279-f6c544d52483
		summarizeBy: none
		sourceColumn: HE_100

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column HE_100_VALOR
		dataType: double
		lineageTag: d8e96b12-cbdc-427a-af83-d07a805b47b0
		summarizeBy: sum
		sourceColumn: HE_100_VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HE_TOTAL
		dataType: dateTime
		formatString: Long Time
		lineageTag: 54dc4fed-ecc4-4fdd-950e-97861f86439d
		summarizeBy: none
		sourceColumn: HE_TOTAL

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column HE_TOTAL_VALOR
		dataType: double
		lineageTag: 368a1905-7183-4a82-a3e1-cf40b83c51a0
		summarizeBy: sum
		sourceColumn: HE_TOTAL_VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DEPARTAMENTO
		dataType: string
		lineageTag: 9ecd31aa-1b32-4b11-a3a7-40bbdbd1f066
		summarizeBy: none
		sourceColumn: DEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column SETOR
		dataType: string
		lineageTag: 043a9554-533a-4bfc-9e7b-a85701bf5abe
		summarizeBy: none
		sourceColumn: SETOR

		annotation SummarizationSetBy = Automatic

	column 'SECAO.1'
		dataType: string
		lineageTag: cdbb5765-572f-4d73-bb2b-40f36ba15d35
		summarizeBy: none
		sourceColumn: SECAO.1

		annotation SummarizationSetBy = Automatic

	column COLIGADA_FILIAL
		dataType: string
		lineageTag: ad3f43ce-9ae3-4d24-b8af-306d0f0058e9
		summarizeBy: none
		sourceColumn: COLIGADA_FILIAL

		annotation SummarizationSetBy = Automatic

	column COLIGADA
		dataType: string
		lineageTag: e7a18ba0-9424-4c9a-ac57-79a206578d58
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: 5f75fb42-a8c3-408f-a572-966c5c1ba68f
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	partition 'Planilha NET 18 - Hora extra dia' = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="SELECT CODCOLIGADA,#(lf)       CODFILIAL,#(lf)       CODSECAO,#(lf)       SECAO,#(lf)       CHAPA,#(lf)       NOME,#(lf)       DATA,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((HE_50/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((HE_50/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((HE_50/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((HE_50 - (TRUNC((HE_50/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((HE_50 - (TRUNC((HE_50/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((HE_50 - (TRUNC((HE_50/60), 0) * 60)) AS VARCHAR(2)) END AS HE_50,#(lf)       (((HE_50 / 60) * SAL_HORA) * 1.50) AS HE_50_VALOR,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((HE_100/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((HE_100/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((HE_100/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((HE_100 - (TRUNC((HE_100/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((HE_100 - (TRUNC((HE_100/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((HE_100 - (TRUNC((HE_100/60), 0) * 60)) AS VARCHAR(2)) END AS HE_100,#(lf)       (((HE_100 / 60) * SAL_HORA) * 2.00) AS HE_100_VALOR,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((HE_TOTAL/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((HE_TOTAL/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((HE_TOTAL/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((HE_TOTAL - (TRUNC((HE_TOTAL/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((HE_TOTAL - (TRUNC((HE_TOTAL/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((HE_TOTAL - (TRUNC((HE_TOTAL/60), 0) * 60)) AS VARCHAR(2)) END AS HE_TOTAL,#(lf)       ((((HE_50 / 60) * SAL_HORA) * 1.50) + (((HE_100 / 60) * SAL_HORA) * 2.00)) AS HE_TOTAL_VALOR#(lf)FROM (#(lf)    SELECT CODCOLIGADA,#(lf)           CODFILIAL,#(lf)           CODSECAO,#(lf)           SECAO,#(lf)           CHAPA,#(lf)           NOME,#(lf)           SAL_HORA,#(lf)           DATA,#(lf)           SUM(HE_50 + HE_COMP) AS HE_50,#(lf)           SUM(HE_100 + HE_DESC + HE_FER) AS HE_100,#(lf)           SUM(HE_50 + HE_100 + HE_DESC + HE_FER + HE_COMP) AS HE_TOTAL#(lf)    FROM (#(lf)        -- Bloco 1: Movimento Diário de Eventos (AMOVFUNDIA) - Mantido 60 dias#(lf)        SELECT CODCOLIGADA,#(lf)               CODFILIAL,#(lf)               CODSECAO,#(lf)               SECAO,#(lf)               CHAPA,#(lf)               NOME,#(lf)               SAL_HORA,#(lf)               DATA,#(lf)               SUM(HE_50) AS HE_50,#(lf)               SUM(HE_100) AS HE_100,#(lf)               SUM(HE_DESC) AS HE_DESC,#(lf)               SUM(HE_FER) AS HE_FER,#(lf)               SUM(HE_COMP) AS HE_COMP#(lf)        FROM (#(lf)            SELECT A.CODCOLIGADA,#(lf)                   C.CODFILIAL,#(lf)                   C.CODSECAO,#(lf)                   SUBSTR(D.DESCRICAO, 21, LENGTH(D.DESCRICAO) - 20) AS SECAO,#(lf)                   A.CHAPA,#(lf)                   C.NOME,#(lf)                   (C.SALARIO / (C.JORNADAMENSAL / 60)) AS SAL_HORA,#(lf)                   A.DATA,#(lf)                   CASE WHEN A.CODEVE = '1301' THEN A.NUMHORAS ELSE 0 END AS HE_50,#(lf)                   CASE WHEN A.CODEVE = '1304' THEN A.NUMHORAS ELSE 0 END AS HE_100,#(lf)                   0 AS HE_DESC,#(lf)                   0 AS HE_FER,#(lf)                   0 AS HE_COMP#(lf)            FROM AMOVFUNDIA@RM A, PEVENTO@RM B, PFUNC@RM C, PSECAO@RM D#(lf)            WHERE A.CODCOLIGADA = B.CODCOLIGADA#(lf)              AND A.CODEVE      = B.CODIGO#(lf)              AND A.CODCOLIGADA = C.CODCOLIGADA#(lf)              AND A.CHAPA       = C.CHAPA#(lf)              AND C.CODCOLIGADA = D.CODCOLIGADA#(lf)              AND C.CODSECAO    = D.CODIGO#(lf)              AND A.CODCOLIGADA BETWEEN 0 AND 999#(lf)              AND C.CODFILIAL BETWEEN 0 AND 999#(lf)              AND SUBSTR(C.CODSECAO, 1, 10) BETWEEN '0' AND 'ZZZZZZZZZZZZ'#(lf)              AND A.DATA BETWEEN TRUNC(SYSDATE) - 60 AND TRUNC(SYSDATE)#(lf)              AND A.CODEVE IN ('1301', '1304')#(lf)        ) Q#(lf)        GROUP BY CODCOLIGADA, CODFILIAL, CODSECAO, SECAO, CHAPA, NOME, SAL_HORA, DATA#(lf)#(lf)        UNION ALL#(lf)#(lf)        -- Bloco 2: Detalhe do Banco de Horas (ABANCOHORFUNDETALHE) - Alterado para 60 dias#(lf)        SELECT A.CODCOLIGADA,#(lf)               C.CODFILIAL,#(lf)               C.CODSECAO,#(lf)               SUBSTR(D.DESCRICAO, 21, LENGTH(D.DESCRICAO) - 20) AS SECAO,#(lf)               A.CHAPA,#(lf)               C.NOME,#(lf)               (C.SALARIO / (C.JORNADAMENSAL / 60)) AS SAL_HORA,#(lf)               A.DATA,#(lf)               SUM(CASE WHEN A.CODEVENTOPONTO IN ('0018', '0026', '0047') THEN CASE WHEN (A.VALOR - A.VALORCOMPENSADO - A.VALORLANCADO) = 0 THEN A.VALOR ELSE (A.VALOR - A.VALORCOMPENSADO - A.VALORLANCADO) END ELSE 0 END) AS HE_50,#(lf)               SUM(CASE WHEN A.CODEVENTOPONTO IN ('0019', '0022', '0024', '0048', '0050') THEN CASE WHEN (A.VALOR - A.VALORCOMPENSADO - A.VALORLANCADO) = 0 THEN A.VALOR ELSE (A.VALOR - A.VALORCOMPENSADO - A.VALORLANCADO) END ELSE 0 END) AS HE_100,#(lf)               0 AS HE_DESC,#(lf)               0 AS HE_FER,#(lf)               0 AS HE_COMP#(lf)        FROM ABANCOHORFUNDETALHE@RM A, PFUNC@RM C, PSECAO@RM D#(lf)        WHERE A.CODCOLIGADA = C.CODCOLIGADA#(lf)          AND A.CHAPA       = C.CHAPA#(lf)          AND C.CODCOLIGADA = D.CODCOLIGADA#(lf)          AND C.CODSECAO    = D.CODIGO#(lf)          AND A.CODCOLIGADA BETWEEN 0 AND 999#(lf)          AND C.CODFILIAL BETWEEN 0 AND 999#(lf)          AND SUBSTR(C.CODSECAO, 1, 10) BETWEEN '0' AND 'ZZZZZZZZZZZZ'#(lf)          -- ALTERADO DE -10 PARA -60 PARA PEGAR TODO O HISTÓRICO IGUAL À OUTRA TABELA#(lf)          AND A.DATA BETWEEN TRUNC(SYSDATE) - 60 AND TRUNC(SYSDATE)#(lf)        GROUP BY A.CODCOLIGADA, C.CODFILIAL, C.CODSECAO, D.DESCRICAO, A.CHAPA, C.NOME, C.SALARIO, C.JORNADAMENSAL, A.DATA#(lf)    ) X#(lf)    GROUP BY CODCOLIGADA, CODFILIAL, CODSECAO, SECAO, CHAPA, NOME, SAL_HORA, DATA#(lf)) W#(lf)ORDER BY CODCOLIGADA, CODFILIAL, CODSECAO, CHAPA, DATA"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"CODCOLIGADA", type text}, {"CODFILIAL", type text}, {"DATA", type date}, {"HE_50", type time}, {"HE_100", type time}, {"HE_TOTAL", type time}}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado", {"CODSECAO"}, FPBI_DEPARTAMENTO, {"CODIGO"}, "FPBI_DEPARTAMENTO", JoinKind.LeftOuter),
				    #"FPBI_DEPARTAMENTO Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "FPBI_DEPARTAMENTO", {"DEPARTAMENTO", "SETOR", "SECAO"}, {"DEPARTAMENTO", "SETOR", "SECAO.1"}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"FPBI_DEPARTAMENTO Expandido", "COLIGADA_FILIAL", each Text.Combine({[CODCOLIGADA], [CODFILIAL]}, "-"), type text),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Coluna Mesclada Inserida", {"COLIGADA_FILIAL"}, dFilial, {"ID_FILIAL"}, "dFilial", JoinKind.LeftOuter),
				    #"dFilial Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "dFilial", {"COLIGADA", "FILIAL"}, {"COLIGADA", "FILIAL"})
				in
				    #"dFilial Expandido"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

