table 'Planilha NET- 4 – Faltas'
	lineageTag: 455df675-a460-4ea2-a8d9-912076b5bf73

	column CODCOLIGADA
		dataType: string
		lineageTag: c04a9fc0-b8e2-462d-b990-cad778bc7553
		summarizeBy: none
		sourceColumn: CODCOLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 972c371c-dcb1-46c5-9a5a-bd2d803e3351
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column CHAPA
		dataType: string
		lineageTag: f52bbc5b-fcb8-4a29-a97e-588fe4ba6607
		summarizeBy: none
		sourceColumn: CHAPA

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: aa26fdff-7a9e-4848-957c-c8535e267a7a
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column SECAO
		dataType: string
		lineageTag: c2dc880d-c710-4c9c-9202-43e768d3268a
		summarizeBy: none
		sourceColumn: SECAO

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 03408e2f-354f-4147-b105-bd880669eca0
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CODFILIAL-CHAPA
		dataType: string
		lineageTag: b615ad3c-19b2-4778-bf33-e2bef49bdb3e
		summarizeBy: none
		sourceColumn: CODFILIAL-CHAPA

		annotation SummarizationSetBy = Automatic

	column DEPARTAMENTO
		dataType: string
		lineageTag: d6f577e3-bf2f-42ce-887e-130d98a710f7
		summarizeBy: none
		sourceColumn: DEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column SETOR
		dataType: string
		lineageTag: 9218b608-0060-4916-850e-3d15102268bc
		summarizeBy: none
		sourceColumn: SETOR

		annotation SummarizationSetBy = Automatic

	column 'SECAO.1'
		dataType: string
		lineageTag: d091c8c0-5c72-48f2-a692-09434d1e53cc
		summarizeBy: none
		sourceColumn: SECAO.1

		annotation SummarizationSetBy = Automatic

	column COLIGADA_FILIAL
		dataType: string
		lineageTag: ca14e34f-63d0-4931-a7c3-1b92d6ad5d82
		summarizeBy: none
		sourceColumn: COLIGADA_FILIAL

		annotation SummarizationSetBy = Automatic

	column COLIGADA
		dataType: string
		lineageTag: bacc0220-3d56-4a9b-8a80-8c0d0ba45cbb
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: a410661f-4440-48bf-83c4-2c5796a83b1a
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column CODSECAO
		dataType: string
		lineageTag: 89198f72-b04a-4c44-9f30-1eff86084080
		summarizeBy: none
		sourceColumn: CODSECAO

		annotation SummarizationSetBy = Automatic

	column HE_50
		dataType: string
		lineageTag: ac8bb68e-2d50-43c2-add0-38ce51f14ae3
		summarizeBy: none
		sourceColumn: HE_50

		annotation SummarizationSetBy = Automatic

	column HE_50_VALOR
		dataType: double
		lineageTag: aee4784e-8b4c-43ba-a53d-c161f5ea8be4
		summarizeBy: sum
		sourceColumn: HE_50_VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HE_100
		dataType: string
		lineageTag: 90ce739c-a022-43f3-b8ed-34802ca2cb8a
		summarizeBy: none
		sourceColumn: HE_100

		annotation SummarizationSetBy = Automatic

	column HE_100_VALOR
		dataType: double
		lineageTag: 399cde83-f329-45e1-bce2-92bc3252c20f
		summarizeBy: sum
		sourceColumn: HE_100_VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HE_TOTAL
		dataType: string
		lineageTag: fd407c6e-9cdf-405e-989d-d51669bd5c8f
		summarizeBy: none
		sourceColumn: HE_TOTAL

		annotation SummarizationSetBy = Automatic

	column HE_TOTAL_VALOR
		dataType: double
		lineageTag: 557cb5ba-8f18-42f5-bc12-62684fcfc7a3
		summarizeBy: sum
		sourceColumn: HE_TOTAL_VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Planilha NET- 4 – Faltas' = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="SELECT CODCOLIGADA,#(lf)       CODFILIAL,#(lf)       CODSECAO,#(lf)       SECAO,#(lf)       CHAPA,#(lf)       NOME,#(lf)       DATA,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((HE_50/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((HE_50/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((HE_50/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((HE_50 - (TRUNC((HE_50/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((HE_50 - (TRUNC((HE_50/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((HE_50 - (TRUNC((HE_50/60), 0) * 60)) AS VARCHAR(2)) END AS HE_50,#(lf)       (((HE_50 / 60) * SAL_HORA) * 1.50) AS HE_50_VALOR,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((HE_100/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((HE_100/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((HE_100/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((HE_100 - (TRUNC((HE_100/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((HE_100 - (TRUNC((HE_100/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((HE_100 - (TRUNC((HE_100/60), 0) * 60)) AS VARCHAR(2)) END AS HE_100,#(lf)       (((HE_100 / 60) * SAL_HORA) * 2.00) AS HE_100_VALOR,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((HE_TOTAL/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((HE_TOTAL/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((HE_TOTAL/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((HE_TOTAL - (TRUNC((HE_TOTAL/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((HE_TOTAL - (TRUNC((HE_TOTAL/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((HE_TOTAL - (TRUNC((HE_TOTAL/60), 0) * 60)) AS VARCHAR(2)) END AS HE_TOTAL,#(lf)       ((((HE_50 / 60) * SAL_HORA) * 1.50) + (((HE_100 / 60) * SAL_HORA) * 2.00)) AS HE_TOTAL_VALOR#(lf)FROM (#(lf)    SELECT CODCOLIGADA,#(lf)           CODFILIAL,#(lf)           CODSECAO,#(lf)           SECAO,#(lf)           CHAPA,#(lf)           NOME,#(lf)           SAL_HORA,#(lf)           DATA,#(lf)           SUM(HE_50 + HE_COMP) AS HE_50,#(lf)           SUM(HE_100 + HE_DESC + HE_FER) AS HE_100,#(lf)           SUM(HE_50 + HE_100 + HE_DESC + HE_FER + HE_COMP) AS HE_TOTAL#(lf)    FROM (#(lf)        -- Bloco 1: Movimento Diário de Eventos (AMOVFUNDIA)#(lf)        SELECT CODCOLIGADA,#(lf)               CODFILIAL,#(lf)               CODSECAO,#(lf)               SECAO,#(lf)               CHAPA,#(lf)               NOME,#(lf)               SAL_HORA,#(lf)               DATA,#(lf)               SUM(HE_50) AS HE_50,#(lf)               SUM(HE_100) AS HE_100,#(lf)               SUM(HE_DESC) AS HE_DESC,#(lf)               SUM(HE_FER) AS HE_FER,#(lf)               SUM(HE_COMP) AS HE_COMP#(lf)        FROM (#(lf)            SELECT A.CODCOLIGADA,#(lf)                   C.CODFILIAL,#(lf)                   C.CODSECAO,#(lf)                   SUBSTR(D.DESCRICAO, 21, LENGTH(D.DESCRICAO) - 20) AS SECAO,#(lf)                   A.CHAPA,#(lf)                   C.NOME,#(lf)                   (C.SALARIO / (C.JORNADAMENSAL / 60)) AS SAL_HORA,#(lf)                   A.DATA,#(lf)                   CASE WHEN A.CODEVE = '1301' THEN A.NUMHORAS ELSE 0 END AS HE_50,#(lf)                   CASE WHEN A.CODEVE = '1304' THEN A.NUMHORAS ELSE 0 END AS HE_100,#(lf)                   0 AS HE_DESC,#(lf)                   0 AS HE_FER,#(lf)                   0 AS HE_COMP#(lf)            FROM AMOVFUNDIA@RM A, PEVENTO@RM B, PFUNC@RM C, PSECAO@RM D#(lf)            WHERE A.CODCOLIGADA = B.CODCOLIGADA#(lf)              AND A.CODEVE      = B.CODIGO#(lf)              AND A.CODCOLIGADA = C.CODCOLIGADA#(lf)              AND A.CHAPA       = C.CHAPA#(lf)              AND C.CODCOLIGADA = D.CODCOLIGADA#(lf)              AND C.CODSECAO    = D.CODIGO#(lf)              AND A.CODCOLIGADA BETWEEN 0 AND 999#(lf)              AND C.CODFILIAL BETWEEN 0 AND 999#(lf)              AND SUBSTR(C.CODSECAO, 1, 10) BETWEEN '0' AND 'ZZZZZZZZZZZZ'#(lf)              AND A.DATA BETWEEN TRUNC(SYSDATE) - 60 AND TRUNC(SYSDATE)#(lf)              AND A.CODEVE IN ('1301', '1304')#(lf)        ) Q#(lf)        GROUP BY CODCOLIGADA, CODFILIAL, CODSECAO, SECAO, CHAPA, NOME, SAL_HORA, DATA#(lf)#(lf)        UNION ALL#(lf)#(lf)        -- Bloco 2: Detalhamento do Banco de Horas (ABANCOHORFUNDETALHE)#(lf)        -- Nota: Bloco antigo do ABANCOHORFUN foi removido para evitar a duplicidade crônica de saldos.#(lf)        SELECT A.CODCOLIGADA,#(lf)               C.CODFILIAL,#(lf)               C.CODSECAO,#(lf)               SUBSTR(D.DESCRICAO, 21, LENGTH(D.DESCRICAO) - 20) AS SECAO,#(lf)               A.CHAPA,#(lf)                   C.NOME,#(lf)               (C.SALARIO / (C.JORNADAMENSAL / 60)) AS SAL_HORA,#(lf)               A.DATA,#(lf)               SUM(CASE WHEN A.CODEVENTOPONTO IN ('0018', '0026', '0047') THEN CASE WHEN (A.VALOR - A.VALORCOMPENSADO - A.VALORLANCADO) = 0 THEN A.VALOR ELSE (A.VALOR - A.VALORCOMPENSADO - A.VALORLANCADO) END ELSE 0 END) AS HE_50,#(lf)               SUM(CASE WHEN A.CODEVENTOPONTO IN ('0019', '0022', '0024', '0048', '0050') THEN CASE WHEN (A.VALOR - A.VALORCOMPENSADO - A.VALORLANCADO) = 0 THEN A.VALOR ELSE (A.VALOR - A.VALORCOMPENSADO - A.VALORLANCADO) END ELSE 0 END) AS HE_100,#(lf)               0 AS HE_DESC,#(lf)               0 AS HE_FER,#(lf)               0 AS HE_COMP#(lf)        FROM ABANCOHORFUNDETALHE@RM A, PFUNC@RM C, PSECAO@RM D#(lf)        WHERE A.CODCOLIGADA = C.CODCOLIGADA#(lf)          AND A.CHAPA       = C.CHAPA#(lf)          AND C.CODCOLIGADA = D.CODCOLIGADA#(lf)          AND C.CODSECAO    = D.CODIGO#(lf)          AND A.CODCOLIGADA BETWEEN 0 AND 999#(lf)          AND C.CODFILIAL BETWEEN 0 AND 999#(lf)          AND SUBSTR(C.CODSECAO, 1, 10) BETWEEN '0' AND 'ZZZZZZZZZZZZ'#(lf)          AND A.DATA BETWEEN TRUNC(SYSDATE) - 10 AND TRUNC(SYSDATE)#(lf)        GROUP BY A.CODCOLIGADA, C.CODFILIAL, C.CODSECAO, D.DESCRICAO, A.CHAPA, C.NOME, C.SALARIO, C.JORNADAMENSAL, A.DATA#(lf)    ) X#(lf)    GROUP BY CODCOLIGADA, CODFILIAL, CODSECAO, SECAO, CHAPA, NOME, SAL_HORA, DATA#(lf)) W#(lf)ORDER BY CODCOLIGADA, CODFILIAL, CODSECAO, CHAPA, DATA"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"CODCOLIGADA", type text}, {"CODFILIAL", type text}, {"DATA", type date}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Tipo Alterado", "CODFILIAL-CHAPA", each Text.Combine({[CODFILIAL], [CHAPA]}, "-"), type text),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Coluna Mesclada Inserida", {"SECAO"}, FPBI_DEPARTAMENTO, {"DESCRICAO"}, "FPBI_DEPARTAMENTO", JoinKind.LeftOuter),
				    #"FPBI_DEPARTAMENTO Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "FPBI_DEPARTAMENTO", {"DEPARTAMENTO", "SETOR", "SECAO"}, {"DEPARTAMENTO", "SETOR", "SECAO.1"}),
				    #"Coluna Mesclada Inserida1" = Table.AddColumn(#"FPBI_DEPARTAMENTO Expandido", "COLIGADA_FILIAL", each Text.Combine({[CODCOLIGADA], [CODFILIAL]}, "-"), type text),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Coluna Mesclada Inserida1", {"COLIGADA_FILIAL"}, dFilial, {"ID_FILIAL"}, "dFilial", JoinKind.LeftOuter),
				    #"dFilial Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "dFilial", {"COLIGADA", "FILIAL"}, {"COLIGADA", "FILIAL"})
				in
				    #"dFilial Expandido"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

