table 'Planilha NET 26 - Funcionários com Jornada'
	lineageTag: c2f08de6-f508-4102-a920-eee2f5b3d2c4

	column CODCOLIGADA
		dataType: string
		lineageTag: 925ca6d2-7707-4d17-939c-04f4b6e0e14e
		summarizeBy: none
		sourceColumn: CODCOLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 617dc9f4-66a1-4e80-aa6b-daae263370ef
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column CODSECAO
		dataType: string
		lineageTag: 044c1209-acad-4de9-8753-fcf47d241bb9
		summarizeBy: none
		sourceColumn: CODSECAO

		annotation SummarizationSetBy = Automatic

	column SECAO
		dataType: string
		lineageTag: 888709e0-de37-4aa6-85e0-2310cf2d7fd9
		summarizeBy: none
		sourceColumn: SECAO

		annotation SummarizationSetBy = Automatic

	column CHAPA
		dataType: string
		lineageTag: e03e6d22-592e-41c1-936d-888b9a7bfae0
		summarizeBy: none
		sourceColumn: CHAPA

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 8315dfc4-a32b-493c-9470-d834402c765b
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column DATAADMISSAO
		dataType: dateTime
		formatString: Long Date
		lineageTag: fd0b85b6-44c2-45cf-b353-34404fd0e5d9
		summarizeBy: none
		sourceColumn: DATAADMISSAO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CODTIPO
		dataType: string
		lineageTag: 05b3c201-1938-4162-870b-6e5bc80b2b92
		summarizeBy: none
		sourceColumn: CODTIPO

		annotation SummarizationSetBy = Automatic

	column CODSITUACAO
		dataType: string
		lineageTag: a594df7d-b6c9-41e5-bba3-45a0dab2d59d
		summarizeBy: none
		sourceColumn: CODSITUACAO

		annotation SummarizationSetBy = Automatic

	column DATAMUDANCA
		dataType: dateTime
		formatString: Long Date
		lineageTag: 505f5a10-bf11-4b9a-a087-bdaa6009b3d2
		summarizeBy: none
		sourceColumn: DATAMUDANCA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column JORNADA
		dataType: string
		lineageTag: cea1200b-5ad8-4357-b614-3ce6cf8f1cb9
		summarizeBy: none
		sourceColumn: JORNADA

		annotation SummarizationSetBy = Automatic

	column DESC_JORNADA
		dataType: string
		lineageTag: 13259a10-bd8b-453f-bf67-fa36587ed1df
		summarizeBy: none
		sourceColumn: DESC_JORNADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL-CHAPA
		dataType: string
		lineageTag: 32ae2c22-6517-4433-a475-1b5ab768b5aa
		summarizeBy: none
		sourceColumn: CODFILIAL-CHAPA

		annotation SummarizationSetBy = Automatic

	partition 'Planilha NET 26 - Funcionários com Jornada' = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="SELECT A.CODCOLIGADA,#(lf)       A.CODFILIAL,#(lf)       A.CODSECAO,#(lf)       SUBSTR(B.DESCRICAO, 21, LENGTH(B.DESCRICAO) - 20) AS SECAO,#(lf)       A.CHAPA,#(lf)       A.NOME,#(lf)       A.DATAADMISSAO,#(lf)       A.CODTIPO,#(lf)       A.CODSITUACAO,#(lf)       (SELECT MAX(E.DATAMUDANCA)#(lf)        FROM AJORNADAFUN@RM E#(lf)        WHERE E.CODCOLIGADA = A.CODCOLIGADA#(lf)          AND E.CHAPA       = A.CHAPA ) DATAMUDANCA,#(lf)       (SELECT F.CODHORARIO#(lf)        FROM AJORNADAFUN@RM F#(lf)        WHERE F.CODCOLIGADA = A.CODCOLIGADA#(lf)          AND F.CHAPA       = A.CHAPA#(lf)          AND F.DATAMUDANCA = (SELECT MAX(E.DATAMUDANCA)#(lf)                               FROM AJORNADAFUN@RM E#(lf)                               WHERE E.CODCOLIGADA = F.CODCOLIGADA#(lf)                                 AND E.CHAPA       = F.CHAPA )) AS JORNADA,#(lf)       (SELECT D.DESCRICAO#(lf)        FROM AHORARIOJORNADA@RM D#(lf)        WHERE D.CODCOLIGADA = A.CODCOLIGADA#(lf)          AND D.CODHORARIO  = (SELECT F.CODHORARIO#(lf)                               FROM AJORNADAFUN@RM F#(lf)                               WHERE F.CODCOLIGADA = A.CODCOLIGADA#(lf)                                 AND F.CHAPA       = A.CHAPA#(lf)                                 AND F.DATAMUDANCA = (SELECT MAX(E.DATAMUDANCA)#(lf)                                                      FROM AJORNADAFUN@RM E#(lf)                                                      WHERE E.CODCOLIGADA = A.CODCOLIGADA#(lf)                                                        AND E.CHAPA       = A.CHAPA ))) AS DESC_JORNADA#(lf)FROM  PFUNC@RM A, PSECAO@RM B#(lf)WHERE A.CODCOLIGADA  = B.CODCOLIGADA#(lf)  AND A.CODSECAO     = B.CODIGO#(lf)  #(lf)  -- Lógica do sistema RM para aceitar ""0"" e trazer todas as estruturas#(lf)  AND A.CODCOLIGADA BETWEEN 0 AND 999#(lf)  AND A.CODFILIAL   BETWEEN 0 AND 999#(lf)  #(lf)  -- Filtros originais de situação e tipo de funcionário#(lf)  AND A.CODSITUACAO <> 'D'#(lf)  AND A.CODTIPO NOT IN ('A', 'D')#(lf)ORDER BY A.CODCOLIGADA, A.CODFILIAL, A.CODSECAO, A.CHAPA"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"DATAADMISSAO", type date}, {"DATAMUDANCA", type date}, {"CODCOLIGADA", type text}, {"CODFILIAL", type text}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Tipo Alterado", "CODFILIAL-CHAPA", each Text.Combine({[CODFILIAL], [CHAPA]}, "-"), type text)
				in
				    #"Coluna Mesclada Inserida"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

