table 'Planilha NET – 2 – Saldo de Banco de Horas – saldo_data'
	lineageTag: f9686605-3ffa-47fb-a760-c1c755b9be1f

	column CODCOLIGADA
		dataType: string
		lineageTag: 9ca8a656-b649-4afe-9fd2-ee34856fe515
		summarizeBy: none
		sourceColumn: CODCOLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: c237510c-eebe-48eb-bc5a-9a05a8cc7d0d
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column CHAPA
		dataType: string
		lineageTag: 21240331-2aaa-4ac4-a5aa-46f4b8e34303
		summarizeBy: none
		sourceColumn: CHAPA

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: d6cd5eb1-f83b-4947-866b-ef780f594f4b
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column SECAO
		dataType: string
		lineageTag: 031a3d13-6f1d-4554-aee4-4cefebcf3a23
		summarizeBy: none
		sourceColumn: SECAO

		annotation SummarizationSetBy = Automatic

	column DATAADMISSAO
		dataType: dateTime
		formatString: Short Date
		lineageTag: 9b5273b0-65b3-42b8-83cf-73d8a1b3ee8e
		summarizeBy: none
		sourceColumn: DATAADMISSAO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DATADEMISSAO
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7be58ca1-cd42-4d4b-a9c8-b31bdc700458
		summarizeBy: none
		sourceColumn: DATADEMISSAO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CODTIPO
		dataType: string
		lineageTag: ec5aba71-e865-478e-b357-24214e3c3ab8
		summarizeBy: none
		sourceColumn: CODTIPO

		annotation SummarizationSetBy = Automatic

	column CODSITUACAO
		dataType: string
		lineageTag: ac6faf5b-1e43-47a6-b594-b095e1cc4f0b
		summarizeBy: none
		sourceColumn: CODSITUACAO

		annotation SummarizationSetBy = Automatic

	column HORA_EXTRA
		dataType: dateTime
		formatString: Long Time
		lineageTag: 6a20be6c-f810-48d5-8cfe-9ec9ccc697b8
		summarizeBy: none
		sourceColumn: HORA_EXTRA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column ATRASO
		dataType: dateTime
		formatString: Long Time
		lineageTag: 5febe739-57dd-4eb9-a566-f11e8c01d2a8
		summarizeBy: none
		sourceColumn: ATRASO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column FALTA
		dataType: dateTime
		formatString: Long Time
		lineageTag: b81d623c-f0c4-4180-af5b-597f7004b08f
		summarizeBy: none
		sourceColumn: FALTA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column SALDO_GERAL_POSITIVO
		dataType: dateTime
		formatString: Long Time
		lineageTag: 51a34409-4392-4ac4-9ebe-feae74514304
		summarizeBy: none
		sourceColumn: SALDO_GERAL_POSITIVO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column SALDO_GERAL_NEGATIVO
		dataType: dateTime
		formatString: Long Time
		lineageTag: cbe74e20-b758-4677-acac-07d8fa78e80c
		summarizeBy: none
		sourceColumn: SALDO_GERAL_NEGATIVO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column CODFILIAL-CHAPA
		dataType: string
		lineageTag: d7408187-ca22-4bb8-9301-f5b98a5fcebd
		summarizeBy: none
		sourceColumn: CODFILIAL-CHAPA

		annotation SummarizationSetBy = Automatic

	partition 'Planilha NET – 2 – Saldo de Banco de Horas – saldo_data' = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="SELECT CODCOLIGADA, CODFILIAL, CHAPA, NOME, SECAO,#(lf)       DATAADMISSAO, DATADEMISSAO, CODTIPO, CODSITUACAO,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((HORA_EXTRA/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((HORA_EXTRA/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((HORA_EXTRA/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((HORA_EXTRA - (TRUNC((HORA_EXTRA/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((HORA_EXTRA - (TRUNC((HORA_EXTRA/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((HORA_EXTRA - (TRUNC((HORA_EXTRA/60), 0) * 60)) AS VARCHAR(2)) END AS HORA_EXTRA,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((ATRASO/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((ATRASO/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((ATRASO/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((ATRASO - (TRUNC((ATRASO/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((ATRASO - (TRUNC((ATRASO/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((ATRASO - (TRUNC((ATRASO/60), 0) * 60)) AS VARCHAR(2)) END AS ATRASO,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((FALTA/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((FALTA/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((FALTA/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((FALTA - (TRUNC((FALTA/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((FALTA - (TRUNC((FALTA/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((FALTA - (TRUNC((FALTA/60), 0) * 60)) AS VARCHAR(2)) END AS FALTA,#(lf)       CASE WHEN SALDO_GERAL >= 0 THEN#(lf)          CASE WHEN LENGTH(CAST(TRUNC((SALDO_GERAL/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((SALDO_GERAL/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((SALDO_GERAL/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((SALDO_GERAL - (TRUNC((SALDO_GERAL/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((SALDO_GERAL - (TRUNC((SALDO_GERAL/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((SALDO_GERAL - (TRUNC((SALDO_GERAL/60), 0) * 60)) AS VARCHAR(2)) END#(lf)       ELSE#(lf)          '00:00'#(lf)       END AS SALDO_GERAL_POSITIVO,#(lf)       CASE WHEN SALDO_GERAL < 0 THEN#(lf)          CASE WHEN LENGTH(CAST(TRUNC(((SALDO_GERAL * (-1))/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC(((SALDO_GERAL * (-1))/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC(((SALDO_GERAL * (-1))/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST(((SALDO_GERAL * (-1)) - (TRUNC(((SALDO_GERAL * (-1))/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST(((SALDO_GERAL * (-1)) - (TRUNC(((SALDO_GERAL * (-1))/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST(((SALDO_GERAL * (-1)) - (TRUNC(((SALDO_GERAL * (-1))/60), 0) * 60)) AS VARCHAR(2)) END#(lf)       ELSE#(lf)          '00:00'#(lf)       END AS SALDO_GERAL_NEGATIVO#(lf)FROM (#(lf)SELECT A.CODCOLIGADA, B.CODFILIAL, A.CHAPA, B.NOME, C.DESCRICAO AS SECAO,#(lf)       B.DATAADMISSAO, B.DATADEMISSAO, B.CODTIPO, B.CODSITUACAO,#(lf)       SUM(A.EXTRAFAIXA1 + A.EXTRAFAIXA2 + A.EXTRAFAIXA3 + A.EXTRAFAIXA4 + A.EXTRAFAIXA5 + A.EXTRACOMP1 + A.EXTRACOMP2 + A.EXTRADESC1 + A.EXTRADESC2 + A.EXTRAFER1 + A.EXTRAFER2) AS HORA_EXTRA,#(lf)       SUM(A.ATRASO) AS ATRASO,#(lf)       SUM(A.FALTA) AS FALTA,#(lf)       SUM(A.EXTRAFAIXA1 + A.EXTRAFAIXA2 + A.EXTRAFAIXA3 + A.EXTRAFAIXA4 + A.EXTRAFAIXA5 + A.EXTRACOMP1 + A.EXTRACOMP2 + A.EXTRADESC1 + A.EXTRADESC2 + A.EXTRAFER1 + A.EXTRAFER2 - A.FALTA - A.ATRASO) AS SALDO_GERAL#(lf)FROM ABANCOHORFUN@RM A, PFUNC@RM B, PSECAO@RM C#(lf)WHERE A.CODCOLIGADA = B.CODCOLIGADA#(lf)  AND A.CHAPA       = B.CHAPA#(lf)  AND B.CODCOLIGADA = C.CODCOLIGADA#(lf)  AND B.CODSECAO    = C.CODIGO#(lf)  #(lf)  -- Lógica do sistema RM para aceitar ""0"" e trazer todas as estruturas#(lf)  AND A.CODCOLIGADA BETWEEN 0 AND 999#(lf)  AND B.CODFILIAL   BETWEEN 0 AND 999#(lf)  #(lf)  -- Regra para demitidos (traz ativos ou quem foi demitido dentro do limite da análise)#(lf)  AND (B.CODSITUACAO  <> 'D'#(lf)  OR  (B.CODSITUACAO   = 'D'#(lf)  AND  B.DATADEMISSAO >= TRUNC(SYSDATE) - 10 ))#(lf)  #(lf)  -- Restrição de período dinâmico (Últimos 10 dias)#(lf)  AND A.DATA BETWEEN TRUNC(SYSDATE) - 10 AND TRUNC(SYSDATE)#(lf)  #(lf)  -- Filtro de chapa aberto dinamicamente para quem já estava admitido#(lf)  AND A.CHAPA IN (SELECT H.CHAPA#(lf)                  FROM PFUNC@RM H#(lf)                  WHERE H.CODCOLIGADA = B.CODCOLIGADA#(lf)                    AND H.CHAPA       = B.CHAPA#(lf)                    AND H.CODSITUACAO = B.CODSITUACAO#(lf)                    AND H.DATAADMISSAO <= TRUNC(SYSDATE))#(lf)GROUP BY A.CODCOLIGADA, B.CODFILIAL, A.CHAPA, B.NOME, C.DESCRICAO, B.DATAADMISSAO, B.DATADEMISSAO, B.CODTIPO, B.CODSITUACAO#(lf)#(lf)) X"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"CODCOLIGADA", type text}, {"CODFILIAL", type text}, {"CHAPA", type text}, {"DATAADMISSAO", type date}, {"DATADEMISSAO", type date}, {"HORA_EXTRA", type time}, {"ATRASO", type time}, {"FALTA", type time}, {"SALDO_GERAL_POSITIVO", type time}, {"SALDO_GERAL_NEGATIVO", type time}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Tipo Alterado", "CODFILIAL-CHAPA", each Text.Combine({[CODFILIAL], [CHAPA]}, "-"), type text)
				in
				    #"Coluna Mesclada Inserida"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

