table 'Planilha NET- 27 – Acima de 10 Horas - Func'
	lineageTag: 647e33bf-830c-4f19-9dcd-e50010189c8d

	column CODCOLIGADA
		dataType: string
		lineageTag: c9d2c7a9-c984-4086-8b4e-0db04c6adcf2
		summarizeBy: none
		sourceColumn: CODCOLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: 480099e9-f5bd-44bf-86b6-325e4b6b20b4
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column CHAPA
		dataType: string
		lineageTag: 15938215-3b4f-4c2f-a9ab-909e7fe7000a
		summarizeBy: none
		sourceColumn: CHAPA

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: f8c2657e-152c-4935-a430-de49609b8d92
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column CODSITUACAO
		dataType: string
		lineageTag: 37d1ab41-ede4-4171-8bda-43f6e8f9f0ac
		summarizeBy: none
		sourceColumn: CODSITUACAO

		annotation SummarizationSetBy = Automatic

	column FUNCAO
		dataType: string
		lineageTag: 213572e9-70ca-4ba6-a914-b95180e094aa
		summarizeBy: none
		sourceColumn: FUNCAO

		annotation SummarizationSetBy = Automatic

	column NOME_SECAO
		dataType: string
		lineageTag: f2a4af27-a107-4566-969e-6ace0936a84a
		summarizeBy: none
		sourceColumn: NOME_SECAO

		annotation SummarizationSetBy = Automatic

	column COD_JORNADA
		dataType: string
		lineageTag: 127f2713-c9e6-4111-b128-d18ffd3121cf
		summarizeBy: none
		sourceColumn: COD_JORNADA

		annotation SummarizationSetBy = Automatic

	column DESC_JORNADA
		dataType: string
		lineageTag: b54b3c80-6acd-4a82-9c6c-683a7ac3979a
		summarizeBy: none
		sourceColumn: DESC_JORNADA

		annotation SummarizationSetBy = Automatic

	column DATAREFERENCIA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5596344f-0620-448c-a258-b6cef23f0944
		summarizeBy: none
		sourceColumn: DATAREFERENCIA

		annotation SummarizationSetBy = Automatic

	column DIA_DA_SEMANA
		dataType: string
		lineageTag: f284bba7-8802-4d1c-a905-8a9edddbb981
		summarizeBy: none
		sourceColumn: DIA_DA_SEMANA

		annotation SummarizationSetBy = Automatic

	column ENT1
		dataType: string
		lineageTag: 6bd7b780-b007-4b4c-8d3a-14f69464ba24
		summarizeBy: none
		sourceColumn: ENT1

		annotation SummarizationSetBy = Automatic

	column SAI1
		dataType: string
		lineageTag: 47c68be7-b4ac-4146-80bf-1e5da4fa8638
		summarizeBy: none
		sourceColumn: SAI1

		annotation SummarizationSetBy = Automatic

	column ENT2
		dataType: string
		lineageTag: 784f3e9d-924b-4ef3-bde2-b3f32509cdb6
		summarizeBy: none
		sourceColumn: ENT2

		annotation SummarizationSetBy = Automatic

	column SAI2
		dataType: string
		lineageTag: 623d35bf-9104-44d1-a0b1-e637b6768d54
		summarizeBy: none
		sourceColumn: SAI2

		annotation SummarizationSetBy = Automatic

	column ENT3
		dataType: string
		lineageTag: f8ea6086-0ca8-49de-82e9-2b0648bd4261
		summarizeBy: none
		sourceColumn: ENT3

		annotation SummarizationSetBy = Automatic

	column SAI3
		dataType: string
		lineageTag: 81b92a32-fcab-4ed1-809e-10371bebbd58
		summarizeBy: none
		sourceColumn: SAI3

		annotation SummarizationSetBy = Automatic

	column ENT4
		dataType: string
		lineageTag: d4eb38d4-6461-4263-8be0-34a9e2b3e2d8
		summarizeBy: none
		sourceColumn: ENT4

		annotation SummarizationSetBy = Automatic

	column SAI4
		dataType: string
		lineageTag: b7b89004-6a8a-4716-b6a9-c8e34a94f1fd
		summarizeBy: none
		sourceColumn: SAI4

		annotation SummarizationSetBy = Automatic

	column HORAS_TRAB
		dataType: dateTime
		formatString: Long Time
		lineageTag: b7ed7780-7029-4d97-b0f3-9c00713e0ca9
		summarizeBy: none
		sourceColumn: HORAS_TRAB

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column STATUS
		dataType: string
		lineageTag: 2aa25245-0935-497c-8225-2c710e9bcf1c
		summarizeBy: none
		sourceColumn: STATUS

		annotation SummarizationSetBy = Automatic

	column CODFILIAL-CHAPA
		dataType: string
		lineageTag: e1504e2c-12df-40ff-ae11-a404e5ec4292
		summarizeBy: none
		sourceColumn: CODFILIAL-CHAPA

		annotation SummarizationSetBy = Automatic

	partition 'Planilha NET- 27 – Acima de 10 Horas - Func' = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="SELECT CODCOLIGADA,#(lf)       CODFILIAL,#(lf)       CHAPA,#(lf)       NOME,#(lf)       CODSITUACAO,#(lf)       FUNCAO,#(lf)       NOME_SECAO,#(lf)       COD_JORNADA,#(lf)       DESC_JORNADA,#(lf)       DATAREFERENCIA,#(lf)       DIA_DA_SEMANA,#(lf)       ENT1,#(lf)       SAI1,#(lf)       ENT2,#(lf)       SAI2,#(lf)       ENT3,#(lf)       SAI3,#(lf)       ENT4,#(lf)       SAI4,#(lf)       HORAS_TRAB,#(lf)       STATUS#(lf)FROM (#(lf)SELECT CODCOLIGADA,#(lf)       CODFILIAL,#(lf)       CHAPA,#(lf)       NOME,#(lf)       CODSITUACAO,#(lf)       FUNCAO,#(lf)       NOME_SECAO,#(lf)       DATAREFERENCIA,#(lf)       CASE#(lf)          WHEN TO_CHAR(DATAREFERENCIA, 'D') = '1' THEN 'DOM'#(lf)          WHEN TO_CHAR(DATAREFERENCIA, 'D') = '2' THEN 'SEG'#(lf)          WHEN TO_CHAR(DATAREFERENCIA, 'D') = '3' THEN 'TER'#(lf)          WHEN TO_CHAR(DATAREFERENCIA, 'D') = '4' THEN 'QUA'#(lf)          WHEN TO_CHAR(DATAREFERENCIA, 'D') = '5' THEN 'QUI'#(lf)          WHEN TO_CHAR(DATAREFERENCIA, 'D') = '6' THEN 'SEX'#(lf)       ELSE#(lf)          'SAB'#(lf)       END AS DIA_DA_SEMANA,#(lf)       ENT1,#(lf)       SAI1,#(lf)       ENT2,#(lf)       SAI2,#(lf)       ENT3,#(lf)       SAI3,#(lf)       ENT4,#(lf)       SAI4,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((HORAS_TRAB/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((HORAS_TRAB/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((HORAS_TRAB/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((HORAS_TRAB - (TRUNC((HORAS_TRAB/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((HORAS_TRAB - (TRUNC((HORAS_TRAB/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((HORAS_TRAB - (TRUNC((HORAS_TRAB/60), 0) * 60)) AS VARCHAR(2)) END AS HORAS_TRAB,#(lf)       CASE#(lf)          WHEN HORAS_TRAB > 600 AND QUANT_BATIDAS > 2 THEN 'Trablhou mais de 10:00'#(lf)          WHEN HORAS_TRAB > 600 AND QUANT_BATIDAS = 2 THEN 'Trablhou mais de 10:00 e foi embora'#(lf)       ELSE#(lf)          'OK'#(lf)       END AS STATUS,#(lf)       (SELECT J.CODHORARIO#(lf)        FROM AJORNADAFUN@RM J#(lf)        WHERE J.CODCOLIGADA = T.CODCOLIGADA#(lf)          AND J.CHAPA       = T.CHAPA#(lf)          AND J.DATAMUDANCA = (SELECT MAX(K.DATAMUDANCA)#(lf)                               FROM AJORNADAFUN@RM K#(lf)                               WHERE K.CODCOLIGADA = J.CODCOLIGADA#(lf)                                 AND K.CHAPA       = J.CHAPA )) AS COD_JORNADA,#(lf)       (SELECT M.DESCRICAO#(lf)        FROM AJORNADAFUN@RM J, AHORARIOJORNADA@RM M#(lf)        WHERE J.CODCOLIGADA = M.CODCOLIGADA#(lf)          AND J.CODHORARIO  = M.CODHORARIO#(lf)          AND J.CODCOLIGADA = T.CODCOLIGADA#(lf)          AND J.CHAPA       = T.CHAPA#(lf)          AND J.DATAMUDANCA = (SELECT MAX(K.DATAMUDANCA)#(lf)                               FROM AJORNADAFUN@RM K#(lf)                               WHERE K.CODCOLIGADA = J.CODCOLIGADA#(lf)                                 AND K.CHAPA       = J.CHAPA )) AS DESC_JORNADA#(lf)FROM (#(lf)SELECT CODCOLIGADA,#(lf)       CODFILIAL,#(lf)       CHAPA,#(lf)       NOME,#(lf)       CODSITUACAO,#(lf)       FUNCAO,#(lf)       NOME_SECAO,#(lf)       DATAREFERENCIA,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 1 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((ENT1/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((ENT1/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((ENT1/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((ENT1 - (TRUNC((ENT1/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((ENT1 - (TRUNC((ENT1/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((ENT1 - (TRUNC((ENT1/60), 0) * 60)) AS VARCHAR(2)) END END AS ENT1,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 2 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((SAI1/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((SAI1/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((SAI1/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((SAI1 - (TRUNC((SAI1/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((SAI1 - (TRUNC((SAI1/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((SAI1 - (TRUNC((SAI1/60), 0) * 60)) AS VARCHAR(2)) END END AS SAI1,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 3 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((ENT2/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((ENT2/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((ENT2/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((ENT2 - (TRUNC((ENT2/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((ENT2 - (TRUNC((ENT2/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((ENT2 - (TRUNC((ENT2/60), 0) * 60)) AS VARCHAR(2)) END END AS ENT2,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 4 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((SAI2/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((SAI2/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((SAI2/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((SAI2 - (TRUNC((SAI2/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((SAI2 - (TRUNC((SAI2/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((SAI2 - (TRUNC((SAI2/60), 0) * 60)) AS VARCHAR(2)) END END AS SAI2,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 5 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((ENT3/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((ENT3/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((ENT3/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((ENT3 - (TRUNC((ENT3/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((ENT3 - (TRUNC((ENT3/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((ENT3 - (TRUNC((ENT3/60), 0) * 60)) AS VARCHAR(2)) END END AS ENT3,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 6 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((SAI3/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((SAI3/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((SAI3/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((SAI3 - (TRUNC((SAI3/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((SAI3 - (TRUNC((SAI3/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((SAI3 - (TRUNC((SAI3/60), 0) * 60)) AS VARCHAR(2)) END END AS SAI3,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 7 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((ENT4/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((ENT4/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((ENT4/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((ENT4 - (TRUNC((ENT4/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((ENT4 - (TRUNC((ENT4/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((ENT4 - (TRUNC((ENT4/60), 0) * 60)) AS VARCHAR(2)) END END AS ENT4,#(lf)       CASE WHEN QUANT_BATIDAS = 8 THEN CASE WHEN LENGTH(CAST(TRUNC((SAI4/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((SAI4/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((SAI4/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((SAI4 - (TRUNC((SAI4/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((SAI4 - (TRUNC((SAI4/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((SAI4 - (TRUNC((SAI4/60), 0) * 60)) AS VARCHAR(2)) END END AS SAI4,#(lf)       (SELECT H.HTRAB#(lf)        FROM AAFHTFUN@RM H#(lf)        WHERE H.CODCOLIGADA = W.CODCOLIGADA#(lf)          AND H.CHAPA       = W.CHAPA#(lf)          AND H.DATA        = W.DATAREFERENCIA  )  AS HORAS_TRAB,#(lf)       QUANT_BATIDAS#(lf)FROM (#(lf)SELECT CODCOLIGADA,#(lf)       CODFILIAL,#(lf)       CHAPA,#(lf)       NOME,#(lf)       CODSITUACAO,#(lf)       FUNCAO,#(lf)       NOME_SECAO,#(lf)       DATAREFERENCIA,#(lf)       SUM(CASE WHEN SEQUENCIA = 1 THEN BATIDA ELSE 0 END) AS ENT1,#(lf)       SUM(CASE WHEN SEQUENCIA = 2 THEN BATIDA ELSE 0 END) AS SAI1,#(lf)       SUM(CASE WHEN SEQUENCIA = 3 THEN BATIDA ELSE 0 END) AS ENT2,#(lf)       SUM(CASE WHEN SEQUENCIA = 4 THEN BATIDA ELSE 0 END) AS SAI2,#(lf)       SUM(CASE WHEN SEQUENCIA = 5 THEN BATIDA ELSE 0 END) AS ENT3,#(lf)       SUM(CASE WHEN SEQUENCIA = 6 THEN BATIDA ELSE 0 END) AS SAI3,#(lf)       SUM(CASE WHEN SEQUENCIA = 7 THEN BATIDA ELSE 0 END) AS ENT4,#(lf)       SUM(CASE WHEN SEQUENCIA = 8 THEN BATIDA ELSE 0 END) AS SAI4,#(lf)       COUNT(QTDE_BATIDA) AS QUANT_BATIDAS#(lf)FROM (#(lf)SELECT ROW_NUMBER() OVER(PARTITION BY A.CHAPA, CASE WHEN A.DATAREFERENCIA IS NOT NULL THEN A.DATAREFERENCIA ELSE A.DATA END ORDER BY A.CHAPA, CASE WHEN A.DATAREFERENCIA IS NOT NULL THEN A.DATAREFERENCIA ELSE A.DATA END, A.DATA, A.BATIDA) SEQUENCIA,#(lf)       A.CODCOLIGADA,#(lf)       B.CODFILIAL,#(lf)       A.CHAPA,#(lf)       B.CODHORARIO,#(lf)       B.NOME,#(lf)       B.CODSITUACAO,#(lf)       D.DESCRICAO AS NOME_SECAO,#(lf)       C.NOME AS FUNCAO,#(lf)       A.DATA,#(lf)       CASE WHEN A.DATAREFERENCIA IS NOT NULL THEN A.DATAREFERENCIA ELSE A.DATA END  AS DATAREFERENCIA,#(lf)       (SELECT G.DESCRICAO#(lf)        FROM PFHSTHOR@RM E, AHORARIO@RM G#(lf)        WHERE E.CODCOLIGADA = A.CODCOLIGADA#(lf)          AND E.CHAPA       = A.CHAPA#(lf)          AND E.CODCOLIGADA = G.CODCOLIGADA#(lf)          AND E.CODHORARIO  = G.CODIGO#(lf)          AND E.DTMUDANCA   = (SELECT MAX(F.DTMUDANCA)#(lf)                               FROM PFHSTHOR@RM F#(lf)                               WHERE F.CODCOLIGADA = A.CODCOLIGADA#(lf)                                 AND F.CHAPA       = A.CHAPA#(lf)                                 AND F.DTMUDANCA  <= CASE WHEN A.DATAREFERENCIA IS NOT NULL THEN A.DATAREFERENCIA ELSE A.DATA END )) AS HORARIO_BASE,#(lf)       A.BATIDA,#(lf)       1 AS QTDE_BATIDA#(lf)FROM ABATFUN@RM A, PFUNC@RM B, PFUNCAO@RM C, PSECAO@RM D#(lf) WHERE A.CODCOLIGADA   = B.CODCOLIGADA#(lf)   AND A.CHAPA         = B.CHAPA#(lf)   AND B.CODCOLIGADA   = C.CODCOLIGADA#(lf)   AND B.CODFUNCAO     = C.CODIGO#(lf)   AND B.CODCOLIGADA   = D.CODCOLIGADA#(lf)   AND B.CODSECAO      = D.CODIGO#(lf)   #(lf)   -- Lógica do sistema RM para aceitar ""0"" e trazer todas as estruturas#(lf)   AND B.CODCOLIGADA BETWEEN 0 AND 999#(lf)   AND B.CODFILIAL   BETWEEN 0 AND 999#(lf)   AND B.CODSECAO    BETWEEN '0' AND 'ZZZZZZZZZZZZ'#(lf)   #(lf)   -- Período dinâmico protegido (Últimos 10 dias) aplicado a DATA e DATAREFERENCIA#(lf)   AND (A.DATA BETWEEN TRUNC(SYSDATE) - 10 AND TRUNC(SYSDATE)#(lf)   OR   A.DATAREFERENCIA BETWEEN TRUNC(SYSDATE) - 10 AND TRUNC(SYSDATE))#(lf)#(lf)) X#(lf)GROUP BY CODCOLIGADA, CODFILIAL, CHAPA, NOME, CODSITUACAO, FUNCAO, NOME_SECAO, DATAREFERENCIA, HORARIO_BASE#(lf)#(lf)) W#(lf)#(lf)) T#(lf)#(lf)) Q#(lf)WHERE STATUS      <> 'OK'#(lf)  AND COD_JORNADA <> '0009'#(lf)ORDER BY CODCOLIGADA, CODFILIAL, CHAPA, DATAREFERENCIA"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"CODCOLIGADA", type text}, {"CODFILIAL", type text}, {"HORAS_TRAB", type time}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Tipo Alterado", "CODFILIAL-CHAPA", each Text.Combine({[CODFILIAL], [CHAPA]}, "-"), type text)
				in
				    #"Coluna Mesclada Inserida"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

