table 'Planilha NET- 27 – Acima de 10 Horas - Valor'
	lineageTag: ce56e30c-6d95-4356-8022-69b6e76c8c50

	column CODCOLIGADA
		dataType: string
		lineageTag: c65138c9-ca54-426e-95d1-d0940f92dac8
		summarizeBy: none
		sourceColumn: CODCOLIGADA

		annotation SummarizationSetBy = Automatic

	column CODFILIAL
		dataType: string
		lineageTag: ce9ab5ec-4091-4e42-b24f-e178a0777a32
		summarizeBy: none
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

	column CHAPA
		dataType: string
		lineageTag: e42439db-9b61-4d0d-941c-08d0d8bda4ef
		summarizeBy: none
		sourceColumn: CHAPA

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: d2cce958-2a36-4330-905a-63c72f1a7725
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column CODSITUACAO
		dataType: string
		lineageTag: 77e42cdf-d128-48bb-b354-258b91b89c40
		summarizeBy: none
		sourceColumn: CODSITUACAO

		annotation SummarizationSetBy = Automatic

	column FUNCAO
		dataType: string
		lineageTag: d7d43e16-758e-4654-bca9-a1ddfac8d63c
		summarizeBy: none
		sourceColumn: FUNCAO

		annotation SummarizationSetBy = Automatic

	column NOME_SECAO
		dataType: string
		lineageTag: d0c2d3e1-9c42-4c51-89d0-41c57d6cc120
		summarizeBy: none
		sourceColumn: NOME_SECAO

		annotation SummarizationSetBy = Automatic

	column COD_JORNADA
		dataType: string
		lineageTag: ca848ac1-fe48-46b4-ab1a-6eae31ff26fb
		summarizeBy: none
		sourceColumn: COD_JORNADA

		annotation SummarizationSetBy = Automatic

	column DESC_JORNADA
		dataType: string
		lineageTag: 9f600fae-0556-40f2-891f-12dcd8b189ff
		summarizeBy: none
		sourceColumn: DESC_JORNADA

		annotation SummarizationSetBy = Automatic

	column DATAREFERENCIA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7c7265e4-28f0-42bc-b74f-10d254c15e3c
		summarizeBy: none
		sourceColumn: DATAREFERENCIA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DIA_DA_SEMANA
		dataType: string
		lineageTag: 734abc50-c505-4c95-8b0d-656e9af14dc5
		summarizeBy: none
		sourceColumn: DIA_DA_SEMANA

		annotation SummarizationSetBy = Automatic

	column ENT1
		dataType: string
		lineageTag: 0acf6103-9b7f-492a-857e-793fdd27910d
		summarizeBy: none
		sourceColumn: ENT1

		annotation SummarizationSetBy = Automatic

	column SAI1
		dataType: string
		lineageTag: 497f3500-d7f8-4f07-b409-b31ff581aeb9
		summarizeBy: none
		sourceColumn: SAI1

		annotation SummarizationSetBy = Automatic

	column ENT2
		dataType: string
		lineageTag: 7f6cf386-2a07-486f-bf28-5ebaedd77a50
		summarizeBy: none
		sourceColumn: ENT2

		annotation SummarizationSetBy = Automatic

	column SAI2
		dataType: string
		lineageTag: 34eff8c0-edc1-4c81-8072-f394a07d7198
		summarizeBy: none
		sourceColumn: SAI2

		annotation SummarizationSetBy = Automatic

	column ENT3
		dataType: string
		lineageTag: 7152e66e-29b5-480e-8883-06b05df6c923
		summarizeBy: none
		sourceColumn: ENT3

		annotation SummarizationSetBy = Automatic

	column SAI3
		dataType: string
		lineageTag: 9bac2b2e-2a35-45c6-a9c0-abb4ad51b6c1
		summarizeBy: none
		sourceColumn: SAI3

		annotation SummarizationSetBy = Automatic

	column ENT4
		dataType: string
		lineageTag: 9159c577-c6bf-4f1e-aa86-5d955fe896c3
		summarizeBy: none
		sourceColumn: ENT4

		annotation SummarizationSetBy = Automatic

	column SAI4
		dataType: string
		lineageTag: 4966beb9-9af6-49fc-a027-fec0e34d0a14
		summarizeBy: none
		sourceColumn: SAI4

		annotation SummarizationSetBy = Automatic

	column HORAS_BASE
		dataType: string
		lineageTag: 81f3fb51-2eba-4e21-b8e1-973c03ddd652
		summarizeBy: none
		sourceColumn: HORAS_BASE

		annotation SummarizationSetBy = Automatic

	column HORAS_TRAB
		dataType: dateTime
		formatString: Long Time
		lineageTag: 25351790-75f8-431c-9a50-d933f80701af
		summarizeBy: none
		sourceColumn: HORAS_TRAB

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column HORAS_EXTRAS
		dataType: dateTime
		formatString: Long Time
		lineageTag: fdc1ce4d-1330-401e-9ff6-77dc78864d7b
		summarizeBy: none
		sourceColumn: HORAS_EXTRAS

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column VALOR_HORAS_EXTRAS
		dataType: double
		lineageTag: 41d62f5e-0ac6-48dc-9627-d75fa68c392d
		summarizeBy: sum
		sourceColumn: VALOR_HORAS_EXTRAS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STATUS
		dataType: string
		lineageTag: 344b35db-2142-4863-8563-e5bf1b435c13
		summarizeBy: none
		sourceColumn: STATUS

		annotation SummarizationSetBy = Automatic

	column CODFILIAL-CHAPA
		dataType: string
		lineageTag: 435fe0ff-958e-4b23-95fd-fe9cdb0ff5ca
		summarizeBy: none
		sourceColumn: CODFILIAL-CHAPA

		annotation SummarizationSetBy = Automatic

	partition 'Planilha NET- 27 – Acima de 10 Horas - Valor' = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="SELECT CODCOLIGADA,#(lf)       CODFILIAL,#(lf)       CHAPA,#(lf)       NOME,#(lf)       CODSITUACAO,#(lf)       FUNCAO,#(lf)       NOME_SECAO,#(lf)       COD_JORNADA,#(lf)       DESC_JORNADA,#(lf)       DATAREFERENCIA,#(lf)       DIA_DA_SEMANA,#(lf)       ENT1,#(lf)       SAI1,#(lf)       ENT2,#(lf)       SAI2,#(lf)       ENT3,#(lf)       SAI3,#(lf)       ENT4,#(lf)       SAI4,#(lf)       HORAS_BASE,#(lf)       HORAS_TRAB,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((HORAS_EXTRAS/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((HORAS_EXTRAS/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((HORAS_EXTRAS/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((HORAS_EXTRAS - (TRUNC((HORAS_EXTRAS/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((HORAS_EXTRAS - (TRUNC((HORAS_EXTRAS/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((HORAS_EXTRAS - (TRUNC((HORAS_EXTRAS/60), 0) * 60)) AS VARCHAR(2)) END AS HORAS_EXTRAS,#(lf)       VALOR_HORAS_EXTRAS,#(lf)       STATUS#(lf)FROM (#(lf)SELECT CODCOLIGADA,#(lf)       CODFILIAL,#(lf)       CHAPA,#(lf)       NOME,#(lf)       CODSITUACAO,#(lf)       FUNCAO,#(lf)       NOME_SECAO,#(lf)       DATAREFERENCIA,#(lf)       SALARIO_HORA,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((HORAS_BASE/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((HORAS_BASE/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((HORAS_BASE/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((HORAS_BASE - (TRUNC((HORAS_BASE/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((HORAS_BASE - (TRUNC((HORAS_BASE/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((HORAS_BASE - (TRUNC((HORAS_BASE/60), 0) * 60)) AS VARCHAR(2)) END AS HORAS_BASE,#(lf)       CASE WHEN HORAS_TRAB > HORAS_BASE THEN (HORAS_TRAB - HORAS_BASE) ELSE 0 END AS HORAS_EXTRAS,#(lf)       CASE WHEN HORAS_TRAB > HORAS_BASE THEN ((((HORAS_TRAB - HORAS_BASE) / 60) * SALARIO_HORA) * 1.50) ELSE 0 END AS VALOR_HORAS_EXTRAS,#(lf)       CASE#(lf)          WHEN TO_CHAR(DATAREFERENCIA, 'D') = '1' THEN 'DOM'#(lf)          WHEN TO_CHAR(DATAREFERENCIA, 'D') = '2' THEN 'SEG'#(lf)          WHEN TO_CHAR(DATAREFERENCIA, 'D') = '3' THEN 'TER'#(lf)          WHEN TO_CHAR(DATAREFERENCIA, 'D') = '4' THEN 'QUA'#(lf)          WHEN TO_CHAR(DATAREFERENCIA, 'D') = '5' THEN 'QUI'#(lf)          WHEN TO_CHAR(DATAREFERENCIA, 'D') = '6' THEN 'SEX'#(lf)       ELSE#(lf)          'SAB'#(lf)       END AS DIA_DA_SEMANA,#(lf)       ENT1,#(lf)       SAI1,#(lf)       ENT2,#(lf)       SAI2,#(lf)       ENT3,#(lf)       SAI3,#(lf)       ENT4,#(lf)       SAI4,#(lf)       CASE WHEN LENGTH(CAST(TRUNC((HORAS_TRAB/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((HORAS_TRAB/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((HORAS_TRAB/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((HORAS_TRAB - (TRUNC((HORAS_TRAB/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((HORAS_TRAB - (TRUNC((HORAS_TRAB/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((HORAS_TRAB - (TRUNC((HORAS_TRAB/60), 0) * 60)) AS VARCHAR(2)) END AS HORAS_TRAB,#(lf)       CASE#(lf)          WHEN HORAS_TRAB > 600 AND QUANT_BATIDAS > 2 THEN 'Trablhou mais de 10:00'#(lf)          WHEN HORAS_TRAB > 600 AND QUANT_BATIDAS = 2 THEN 'Trablhou mais de 10:00 e foi embora'#(lf)       ELSE#(lf)          'OK'#(lf)       END AS STATUS,#(lf)       (SELECT J.CODHORARIO#(lf)        FROM AJORNADAFUN@RM J#(lf)        WHERE J.CODCOLIGADA = T.CODCOLIGADA#(lf)          AND J.CHAPA       = T.CHAPA#(lf)          AND J.DATAMUDANCA = (SELECT MAX(K.DATAMUDANCA)#(lf)                               FROM AJORNADAFUN@RM K#(lf)                               WHERE K.CODCOLIGADA = J.CODCOLIGADA#(lf)                                 AND K.CHAPA       = J.CHAPA )) AS COD_JORNADA,#(lf)       (SELECT M.DESCRICAO#(lf)        FROM AJORNADAFUN@RM J, AHORARIOJORNADA@RM M#(lf)        WHERE J.CODCOLIGADA = M.CODCOLIGADA#(lf)          AND J.CODHORARIO  = M.CODHORARIO#(lf)          AND J.CODCOLIGADA = T.CODCOLIGADA#(lf)          AND J.CHAPA       = T.CHAPA#(lf)          AND J.DATAMUDANCA = (SELECT MAX(K.DATAMUDANCA)#(lf)                               FROM AJORNADAFUN@RM K#(lf)                               WHERE K.CODCOLIGADA = J.CODCOLIGADA#(lf)                                 AND K.CHAPA       = J.CHAPA )) AS DESC_JORNADA#(lf)FROM (#(lf)SELECT CODCOLIGADA,#(lf)       CODFILIAL,#(lf)       CHAPA,#(lf)       NOME,#(lf)       CODSITUACAO,#(lf)       FUNCAO,#(lf)       NOME_SECAO,#(lf)       DATAREFERENCIA,#(lf)       SALARIO_HORA,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 1 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((ENT1/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((ENT1/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((ENT1/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((ENT1 - (TRUNC((ENT1/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((ENT1 - (TRUNC((ENT1/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((ENT1 - (TRUNC((ENT1/60), 0) * 60)) AS VARCHAR(2)) END END AS ENT1,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 2 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((SAI1/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((SAI1/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((SAI1/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((SAI1 - (TRUNC((SAI1/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((SAI1 - (TRUNC((SAI1/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((SAI1 - (TRUNC((SAI1/60), 0) * 60)) AS VARCHAR(2)) END END AS SAI1,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 3 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((ENT2/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((ENT2/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((ENT2/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((ENT2 - (TRUNC((ENT2/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((ENT2 - (TRUNC((ENT2/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((ENT2 - (TRUNC((ENT2/60), 0) * 60)) AS VARCHAR(2)) END END AS ENT2,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 4 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((SAI2/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((SAI2/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((SAI2/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((SAI2 - (TRUNC((SAI2/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((SAI2 - (TRUNC((SAI2/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((SAI2 - (TRUNC((SAI2/60), 0) * 60)) AS VARCHAR(2)) END END AS SAI2,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 5 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((ENT3/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((ENT3/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((ENT3/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((ENT3 - (TRUNC((ENT3/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((ENT3 - (TRUNC((ENT3/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((ENT3 - (TRUNC((ENT3/60), 0) * 60)) AS VARCHAR(2)) END END AS ENT3,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 6 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((SAI3/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((SAI3/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((SAI3/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((SAI3 - (TRUNC((SAI3/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((SAI3 - (TRUNC((SAI3/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((SAI3 - (TRUNC((SAI3/60), 0) * 60)) AS VARCHAR(2)) END END AS SAI3,#(lf)       CASE WHEN QUANT_BATIDAS BETWEEN 7 AND 8 THEN CASE WHEN LENGTH(CAST(TRUNC((ENT4/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((ENT4/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((ENT4/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((ENT4 - (TRUNC((ENT4/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((ENT4 - (TRUNC((ENT4/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((ENT4 - (TRUNC((ENT4/60), 0) * 60)) AS VARCHAR(2)) END END AS ENT4,#(lf)       CASE WHEN QUANT_BATIDAS = 8 THEN CASE WHEN LENGTH(CAST(TRUNC((SAI4/60), 0) AS VARCHAR(5))) = 2 THEN CAST(TRUNC((SAI4/60), 0) AS VARCHAR(5)) ELSE '0' || CAST(TRUNC((SAI4/60), 0) AS VARCHAR(5)) END || ':' || CASE WHEN LENGTH(CAST((SAI4 - (TRUNC((SAI4/60), 0) * 60)) AS VARCHAR(2))) = 2 THEN CAST((SAI4 - (TRUNC((SAI4/60), 0) * 60)) AS VARCHAR(2)) ELSE '0' || CAST((SAI4 - (TRUNC((SAI4/60), 0) * 60)) AS VARCHAR(2)) END END AS SAI4,#(lf)       (SELECT H.HTRAB#(lf)        FROM AAFHTFUN@RM H#(lf)        WHERE H.CODCOLIGADA = W.CODCOLIGADA#(lf)          AND H.CHAPA       = W.CHAPA#(lf)          AND H.DATA        = W.DATAREFERENCIA  )  AS HORAS_TRAB,#(lf)       (SELECT H.BASE#(lf)        FROM AAFHTFUN@RM H#(lf)        WHERE H.CODCOLIGADA = W.CODCOLIGADA#(lf)          AND H.CHAPA       = W.CHAPA#(lf)          AND H.DATA        = W.DATAREFERENCIA  )  AS HORAS_BASE,#(lf)       QUANT_BATIDAS#(lf)FROM (#(lf)SELECT CODCOLIGADA,#(lf)       CODFILIAL,#(lf)       CHAPA,#(lf)       NOME,#(lf)       CODSITUACAO,#(lf)       FUNCAO,#(lf)       NOME_SECAO,#(lf)       DATAREFERENCIA,#(lf)       SALARIO_HORA,#(lf)       SUM(CASE WHEN SEQUENCIA = 1 THEN BATIDA ELSE 0 END) AS ENT1,#(lf)       SUM(CASE WHEN SEQUENCIA = 2 THEN BATIDA ELSE 0 END) AS SAI1,#(lf)       SUM(CASE WHEN SEQUENCIA = 3 THEN BATIDA ELSE 0 END) AS ENT2,#(lf)       SUM(CASE WHEN SEQUENCIA = 4 THEN BATIDA ELSE 0 END) AS SAI2,#(lf)       SUM(CASE WHEN SEQUENCIA = 5 THEN BATIDA ELSE 0 END) AS ENT3,#(lf)       SUM(CASE WHEN SEQUENCIA = 6 THEN BATIDA ELSE 0 END) AS SAI3,#(lf)       SUM(CASE WHEN SEQUENCIA = 7 THEN BATIDA ELSE 0 END) AS ENT4,#(lf)       SUM(CASE WHEN SEQUENCIA = 8 THEN BATIDA ELSE 0 END) AS SAI4,#(lf)       COUNT(QTDE_BATIDA) AS QUANT_BATIDAS#(lf)FROM (#(lf)SELECT ROW_NUMBER() OVER(PARTITION BY A.CHAPA, CASE WHEN A.DATAREFERENCIA IS NOT NULL THEN A.DATAREFERENCIA ELSE A.DATA END ORDER BY A.CHAPA, CASE WHEN A.DATAREFERENCIA IS NOT NULL THEN A.DATAREFERENCIA ELSE A.DATA END, A.DATA, A.BATIDA) SEQUENCIA,#(lf)       A.CODCOLIGADA,#(lf)       B.CODFILIAL,#(lf)       A.CHAPA,#(lf)       B.CODHORARIO,#(lf)       B.NOME,#(lf)       B.CODSITUACAO,#(lf)       D.DESCRICAO AS NOME_SECAO,#(lf)       C.NOME AS FUNCAO,#(lf)       A.DATA,#(lf)       (B.SALARIO / (B.JORNADAMENSAL / 60)) AS SALARIO_HORA,#(lf)       CASE WHEN A.DATAREFERENCIA IS NOT NULL THEN A.DATAREFERENCIA ELSE A.DATA END  AS DATAREFERENCIA,#(lf)       (SELECT G.DESCRICAO#(lf)        FROM PFHSTHOR@RM E, AHORARIO@RM G#(lf)        WHERE E.CODCOLIGADA = A.CODCOLIGADA#(lf)          AND E.CHAPA       = A.CHAPA#(lf)          AND E.CODCOLIGADA = G.CODCOLIGADA#(lf)          AND E.CODHORARIO  = G.CODIGO#(lf)          AND E.DTMUDANCA   = (SELECT MAX(F.DTMUDANCA)#(lf)                               FROM PFHSTHOR@RM F#(lf)                               WHERE F.CODCOLIGADA = A.CODCOLIGADA#(lf)                                 AND F.CHAPA       = A.CHAPA#(lf)                                 AND F.DTMUDANCA  <= CASE WHEN A.DATAREFERENCIA IS NOT NULL THEN A.DATAREFERENCIA ELSE A.DATA END )) AS HORARIO_BASE,#(lf)       A.BATIDA,#(lf)       1 AS QTDE_BATIDA#(lf)FROM ABATFUN@RM A, PFUNC@RM B, PFUNCAO@RM C, PSECAO@RM D#(lf) WHERE A.CODCOLIGADA   = B.CODCOLIGADA#(lf)   AND A.CHAPA         = B.CHAPA#(lf)   AND B.CODCOLIGADA   = C.CODCOLIGADA#(lf)   AND B.CODFUNCAO     = C.CODIGO#(lf)   AND B.CODCOLIGADA   = D.CODCOLIGADA#(lf)   AND B.CODSECAO      = D.CODIGO#(lf)   #(lf)   -- Lógica do sistema RM para aceitar ""0"" e trazer todas as estruturas#(lf)   AND B.CODCOLIGADA BETWEEN 0 AND 999#(lf)   AND B.CODFILIAL   BETWEEN 0 AND 999#(lf)   AND B.CODSECAO    BETWEEN '0' AND 'ZZZZZZZZZZZZ'#(lf)   #(lf)   -- Período dinâmico protegido (Últimos 10 dias) aplicado a DATA e DATAREFERENCIA#(lf)   AND (A.DATA BETWEEN TRUNC(SYSDATE) - 10 AND TRUNC(SYSDATE)#(lf)   OR   A.DATAREFERENCIA BETWEEN TRUNC(SYSDATE) - 10 AND TRUNC(SYSDATE))#(lf)#(lf)) X#(lf)GROUP BY CODCOLIGADA, CODFILIAL, CHAPA, NOME, CODSITUACAO, FUNCAO, NOME_SECAO, DATAREFERENCIA, HORARIO_BASE, SALARIO_HORA#(lf)#(lf)) W#(lf)#(lf)) T#(lf)#(lf)) Q#(lf)WHERE COD_JORNADA <> '0009'#(lf)ORDER BY CODCOLIGADA, CODFILIAL, CHAPA, DATAREFERENCIA"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"CODCOLIGADA", type text}, {"CODFILIAL", type text}, {"DATAREFERENCIA", type date}, {"HORAS_TRAB", type time}, {"HORAS_EXTRAS", type time}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Tipo Alterado", "CODFILIAL-CHAPA", each Text.Combine({[CODFILIAL], [CHAPA]}, "-"), type text),
				    #"Valor Substituído" = Table.ReplaceValue(#"Coluna Mesclada Inserida","Trablhou mais de 10:00 e foi embora","Trablhou mais de 10:00",Replacer.ReplaceText,{"STATUS"})
				in
				    #"Valor Substituído"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

